var annotated_dup =
[
    [ "cgv", "namespacecgv.html", [
      [ "app", null, [
        [ "application_plugin_base", "classcgv_1_1app_1_1application__plugin__base.html", "classcgv_1_1app_1_1application__plugin__base" ],
        [ "generic_application_plugin", "classcgv_1_1app_1_1generic__application__plugin.html", "classcgv_1_1app_1_1generic__application__plugin" ],
        [ "application_plugin", "classcgv_1_1app_1_1application__plugin.html", "classcgv_1_1app_1_1application__plugin" ]
      ] ],
      [ "audio", null, [
        [ "OALContext", "classcgv_1_1audio_1_1OALContext.html", "classcgv_1_1audio_1_1OALContext" ],
        [ "OALListener", "classcgv_1_1audio_1_1OALListener.html", "classcgv_1_1audio_1_1OALListener" ],
        [ "OALSource", "classcgv_1_1audio_1_1OALSource.html", "classcgv_1_1audio_1_1OALSource" ]
      ] ],
      [ "base", "namespacecgv_1_1base.html", [
        [ "action", "classcgv_1_1base_1_1action.html", "classcgv_1_1base_1_1action" ],
        [ "base_method_action", "classcgv_1_1base_1_1base__method__action.html", "classcgv_1_1base_1_1base__method__action" ],
        [ "method_action", "classcgv_1_1base_1_1method__action.html", "classcgv_1_1base_1_1method__action" ],
        [ "single_method_action", "classcgv_1_1base_1_1single__method__action.html", "classcgv_1_1base_1_1single__method__action" ],
        [ "matched_method_action", "classcgv_1_1base_1_1matched__method__action.html", "classcgv_1_1base_1_1matched__method__action" ],
        [ "method_action_2", "classcgv_1_1base_1_1method__action__2.html", "classcgv_1_1base_1_1method__action__2" ],
        [ "single_method_action_2", "classcgv_1_1base_1_1single__method__action__2.html", "classcgv_1_1base_1_1single__method__action__2" ],
        [ "attach_slot", "classcgv_1_1base_1_1attach__slot.html", "classcgv_1_1base_1_1attach__slot" ],
        [ "base", "classcgv_1_1base_1_1base.html", "classcgv_1_1base_1_1base" ],
        [ "base_generator", "classcgv_1_1base_1_1base__generator.html", "classcgv_1_1base_1_1base__generator" ],
        [ "console", "classcgv_1_1base_1_1console.html", "classcgv_1_1base_1_1console" ],
        [ "find_action", "classcgv_1_1base_1_1find__action.html", "classcgv_1_1base_1_1find__action" ],
        [ "group", "classcgv_1_1base_1_1group.html", "classcgv_1_1base_1_1group" ],
        [ "user_feedback", "structcgv_1_1base_1_1user__feedback.html", "structcgv_1_1base_1_1user__feedback" ],
        [ "named", "classcgv_1_1base_1_1named.html", "classcgv_1_1base_1_1named" ],
        [ "node", "classcgv_1_1base_1_1node.html", "classcgv_1_1base_1_1node" ],
        [ "registration_order_definition", "structcgv_1_1base_1_1registration__order__definition.html", null ],
        [ "object_constructor", "structcgv_1_1base_1_1object__constructor.html", "structcgv_1_1base_1_1object__constructor" ],
        [ "object_registration", "structcgv_1_1base_1_1object__registration.html", "structcgv_1_1base_1_1object__registration" ],
        [ "object_registration_1", "structcgv_1_1base_1_1object__registration__1.html", "structcgv_1_1base_1_1object__registration__1" ],
        [ "object_registration_2", "structcgv_1_1base_1_1object__registration__2.html", "structcgv_1_1base_1_1object__registration__2" ],
        [ "server", "structcgv_1_1base_1_1server.html", null ],
        [ "driver", "structcgv_1_1base_1_1driver.html", null ],
        [ "registration_listener", "structcgv_1_1base_1_1registration__listener.html", "structcgv_1_1base_1_1registration__listener" ],
        [ "factory", "structcgv_1_1base_1_1factory.html", "structcgv_1_1base_1_1factory" ],
        [ "factory_impl", "structcgv_1_1base_1_1factory__impl.html", "structcgv_1_1base_1_1factory__impl" ],
        [ "factory_impl_1", "structcgv_1_1base_1_1factory__impl__1.html", "structcgv_1_1base_1_1factory__impl__1" ],
        [ "factory_impl_2", "structcgv_1_1base_1_1factory__impl__2.html", "structcgv_1_1base_1_1factory__impl__2" ],
        [ "factory_registration", "structcgv_1_1base_1_1factory__registration.html", "structcgv_1_1base_1_1factory__registration" ],
        [ "factory_registration_1", "structcgv_1_1base_1_1factory__registration__1.html", "structcgv_1_1base_1_1factory__registration__1" ],
        [ "factory_registration_2", "structcgv_1_1base_1_1factory__registration__2.html", "structcgv_1_1base_1_1factory__registration__2" ],
        [ "test", "classcgv_1_1base_1_1test.html", "classcgv_1_1base_1_1test" ],
        [ "test_registration", "structcgv_1_1base_1_1test__registration.html", "structcgv_1_1base_1_1test__registration" ],
        [ "resource_file_info", "structcgv_1_1base_1_1resource__file__info.html", "structcgv_1_1base_1_1resource__file__info" ],
        [ "resource_file_registration", "structcgv_1_1base_1_1resource__file__registration.html", "structcgv_1_1base_1_1resource__file__registration" ],
        [ "resource_string_registration", "structcgv_1_1base_1_1resource__string__registration.html", "structcgv_1_1base_1_1resource__string__registration" ],
        [ "argument_handler", "structcgv_1_1base_1_1argument__handler.html", "structcgv_1_1base_1_1argument__handler" ],
        [ "command_info", "structcgv_1_1base_1_1command__info.html", "structcgv_1_1base_1_1command__info" ],
        [ "config_file_observer", "structcgv_1_1base_1_1config__file__observer.html", "structcgv_1_1base_1_1config__file__observer" ],
        [ "config_file_driver", "structcgv_1_1base_1_1config__file__driver.html", "structcgv_1_1base_1_1config__file__driver" ],
        [ "traverse_policy", "classcgv_1_1base_1_1traverse__policy.html", "classcgv_1_1base_1_1traverse__policy" ],
        [ "traverse_callback_handler", "classcgv_1_1base_1_1traverse__callback__handler.html", "classcgv_1_1base_1_1traverse__callback__handler" ],
        [ "traverser", "classcgv_1_1base_1_1traverser.html", "classcgv_1_1base_1_1traverser" ]
      ] ],
      [ "data", "namespacecgv_1_1data.html", [
        [ "ascii_reflection_handler", "classcgv_1_1data_1_1ascii__reflection__handler.html", "classcgv_1_1data_1_1ascii__reflection__handler" ],
        [ "ascii_read_reflection_handler", "classcgv_1_1data_1_1ascii__read__reflection__handler.html", "classcgv_1_1data_1_1ascii__read__reflection__handler" ],
        [ "ascii_write_reflection_handler", "classcgv_1_1data_1_1ascii__write__reflection__handler.html", "classcgv_1_1data_1_1ascii__write__reflection__handler" ],
        [ "binary_reflection_handler", "classcgv_1_1data_1_1binary__reflection__handler.html", "classcgv_1_1data_1_1binary__reflection__handler" ],
        [ "binary_read_reflection_handler", "classcgv_1_1data_1_1binary__read__reflection__handler.html", "classcgv_1_1data_1_1binary__read__reflection__handler" ],
        [ "binary_write_reflection_handler", "classcgv_1_1data_1_1binary__write__reflection__handler.html", "classcgv_1_1data_1_1binary__write__reflection__handler" ],
        [ "component_format", "classcgv_1_1data_1_1component__format.html", "classcgv_1_1data_1_1component__format" ],
        [ "data_format", "classcgv_1_1data_1_1data__format.html", "classcgv_1_1data_1_1data__format" ],
        [ "data_view_base", "classcgv_1_1data_1_1data__view__base.html", "classcgv_1_1data_1_1data__view__base" ],
        [ "data_view_impl", "classcgv_1_1data_1_1data__view__impl.html", "classcgv_1_1data_1_1data__view__impl" ],
        [ "data_view", "classcgv_1_1data_1_1data__view.html", "classcgv_1_1data_1_1data__view" ],
        [ "const_data_view", "classcgv_1_1data_1_1const__data__view.html", "classcgv_1_1data_1_1const__data__view" ],
        [ "dynamic_priority_queue", "classcgv_1_1data_1_1dynamic__priority__queue.html", "classcgv_1_1data_1_1dynamic__priority__queue" ],
        [ "interval_map", "classcgv_1_1data_1_1interval__map.html", "classcgv_1_1data_1_1interval__map" ],
        [ "io_reflection_handler", "classcgv_1_1data_1_1io__reflection__handler.html", "classcgv_1_1data_1_1io__reflection__handler" ],
        [ "packing_info", "classcgv_1_1data_1_1packing__info.html", "classcgv_1_1data_1_1packing__info" ],
        [ "ref_counted", "classcgv_1_1data_1_1ref__counted.html", "classcgv_1_1data_1_1ref__counted" ],
        [ "ref_ptr", "classcgv_1_1data_1_1ref__ptr.html", "classcgv_1_1data_1_1ref__ptr" ],
        [ "ref_ptr_tag", "classcgv_1_1data_1_1ref__ptr__tag.html", "classcgv_1_1data_1_1ref__ptr__tag" ]
      ] ],
      [ "gui", "namespacecgv_1_1gui.html", [
        [ "vr_calibration", "classcgv_1_1gui_1_1vr__calibration.html", "classcgv_1_1gui_1_1vr__calibration" ],
        [ "vr_event_extension", "classcgv_1_1gui_1_1vr__event__extension.html", "classcgv_1_1gui_1_1vr__event__extension" ],
        [ "vr_key_event", "classcgv_1_1gui_1_1vr__key__event.html", "classcgv_1_1gui_1_1vr__key__event" ],
        [ "vr_throttle_event", "classcgv_1_1gui_1_1vr__throttle__event.html", "classcgv_1_1gui_1_1vr__throttle__event" ],
        [ "vr_stick_event", "classcgv_1_1gui_1_1vr__stick__event.html", "classcgv_1_1gui_1_1vr__stick__event" ],
        [ "vr_pose_event", "classcgv_1_1gui_1_1vr__pose__event.html", "classcgv_1_1gui_1_1vr__pose__event" ],
        [ "vr_server", "classcgv_1_1gui_1_1vr__server.html", "classcgv_1_1gui_1_1vr__server" ],
        [ "monitor_description", "structcgv_1_1gui_1_1monitor__description.html", null ],
        [ "application", "classcgv_1_1gui_1_1application.html", "classcgv_1_1gui_1_1application" ],
        [ "button", "classcgv_1_1gui_1_1button.html", "classcgv_1_1gui_1_1button" ],
        [ "choice_event", "classcgv_1_1gui_1_1choice__event.html", "classcgv_1_1gui_1_1choice__event" ],
        [ "abst_control", "classcgv_1_1gui_1_1abst__control.html", "classcgv_1_1gui_1_1abst__control" ],
        [ "abst_control_provider", "structcgv_1_1gui_1_1abst__control__provider.html", "structcgv_1_1gui_1_1abst__control__provider" ],
        [ "control_provider", "structcgv_1_1gui_1_1control__provider.html", "structcgv_1_1gui_1_1control__provider" ],
        [ "control", "classcgv_1_1gui_1_1control.html", "classcgv_1_1gui_1_1control" ],
        [ "dialog", "classcgv_1_1gui_1_1dialog.html", "classcgv_1_1gui_1_1dialog" ],
        [ "event", "classcgv_1_1gui_1_1event.html", "classcgv_1_1gui_1_1event" ],
        [ "event_handler", "classcgv_1_1gui_1_1event__handler.html", "classcgv_1_1gui_1_1event__handler" ],
        [ "file_helper", "classcgv_1_1gui_1_1file__helper.html", "classcgv_1_1gui_1_1file__helper" ],
        [ "directory_helper", "classcgv_1_1gui_1_1directory__helper.html", "classcgv_1_1gui_1_1directory__helper" ],
        [ "gui_creator", "structcgv_1_1gui_1_1gui__creator.html", "structcgv_1_1gui_1_1gui__creator" ],
        [ "gui_creator_registration", "classcgv_1_1gui_1_1gui__creator__registration.html", null ],
        [ "gui_driver", "classcgv_1_1gui_1_1gui__driver.html", "classcgv_1_1gui_1_1gui__driver" ],
        [ "gui_group", "classcgv_1_1gui_1_1gui__group.html", "classcgv_1_1gui_1_1gui__group" ],
        [ "key_event", "classcgv_1_1gui_1_1key__event.html", "classcgv_1_1gui_1_1key__event" ],
        [ "menu_provider", "classcgv_1_1gui_1_1menu__provider.html", "classcgv_1_1gui_1_1menu__provider" ],
        [ "mouse_event", "classcgv_1_1gui_1_1mouse__event.html", "classcgv_1_1gui_1_1mouse__event" ],
        [ "pose_event", "classcgv_1_1gui_1_1pose__event.html", "classcgv_1_1gui_1_1pose__event" ],
        [ "with_index_struct", "structcgv_1_1gui_1_1with__index__struct.html", null ],
        [ "provider", "classcgv_1_1gui_1_1provider.html", "classcgv_1_1gui_1_1provider" ],
        [ "shortcut", "classcgv_1_1gui_1_1shortcut.html", "classcgv_1_1gui_1_1shortcut" ],
        [ "stick_event", "classcgv_1_1gui_1_1stick__event.html", "classcgv_1_1gui_1_1stick__event" ],
        [ "subprovider", "classcgv_1_1gui_1_1subprovider.html", "classcgv_1_1gui_1_1subprovider" ],
        [ "text_editor_callback_handler", "structcgv_1_1gui_1_1text__editor__callback__handler.html", "structcgv_1_1gui_1_1text__editor__callback__handler" ],
        [ "text_style", "structcgv_1_1gui_1_1text__style.html", "structcgv_1_1gui_1_1text__style" ],
        [ "text_editor", "classcgv_1_1gui_1_1text__editor.html", "classcgv_1_1gui_1_1text__editor" ],
        [ "throttle_event", "classcgv_1_1gui_1_1throttle__event.html", "classcgv_1_1gui_1_1throttle__event" ],
        [ "trigger", "classcgv_1_1gui_1_1trigger.html", "classcgv_1_1gui_1_1trigger" ],
        [ "abst_view", "classcgv_1_1gui_1_1abst__view.html", "classcgv_1_1gui_1_1abst__view" ],
        [ "view", "classcgv_1_1gui_1_1view.html", "classcgv_1_1gui_1_1view" ],
        [ "window", "classcgv_1_1gui_1_1window.html", "classcgv_1_1gui_1_1window" ],
        [ "gamepad_key_event", "classcgv_1_1gui_1_1gamepad__key__event.html", "classcgv_1_1gui_1_1gamepad__key__event" ],
        [ "gamepad_throttle_event", "classcgv_1_1gui_1_1gamepad__throttle__event.html", "classcgv_1_1gui_1_1gamepad__throttle__event" ],
        [ "gamepad_stick_event", "classcgv_1_1gui_1_1gamepad__stick__event.html", "classcgv_1_1gui_1_1gamepad__stick__event" ]
      ] ],
      [ "math", "namespacecgv_1_1math.html", [
        [ "adjacency_list", "classcgv_1_1math_1_1adjacency__list.html", "classcgv_1_1math_1_1adjacency__list" ],
        [ "pinhole", "classcgv_1_1math_1_1pinhole.html", "classcgv_1_1math_1_1pinhole" ],
        [ "distorted_pinhole_types", "classcgv_1_1math_1_1distorted__pinhole__types.html", "classcgv_1_1math_1_1distorted__pinhole__types" ],
        [ "distorted_pinhole", "classcgv_1_1math_1_1distorted__pinhole.html", "classcgv_1_1math_1_1distorted__pinhole" ],
        [ "camera", "classcgv_1_1math_1_1camera.html", "classcgv_1_1math_1_1camera" ],
        [ "diag_mat", "structcgv_1_1math_1_1diag__mat.html", "structcgv_1_1math_1_1diag__mat" ],
        [ "fibo_heap", "classcgv_1_1math_1_1fibo__heap.html", "classcgv_1_1math_1_1fibo__heap" ],
        [ "fmat", "classcgv_1_1math_1_1fmat.html", "classcgv_1_1math_1_1fmat" ],
        [ "vec", "classcgv_1_1math_1_1vec.html", "classcgv_1_1math_1_1vec" ],
        [ "fvec", "classcgv_1_1math_1_1fvec.html", "classcgv_1_1math_1_1fvec" ],
        [ "interval", "classcgv_1_1math_1_1interval.html", "classcgv_1_1math_1_1interval" ],
        [ "mat", "classcgv_1_1math_1_1mat.html", "classcgv_1_1math_1_1mat" ],
        [ "mfunc", "classcgv_1_1math_1_1mfunc.html", "classcgv_1_1math_1_1mfunc" ],
        [ "v2_func", "classcgv_1_1math_1_1v2__func.html", "classcgv_1_1math_1_1v2__func" ],
        [ "v3_func", "classcgv_1_1math_1_1v3__func.html", "classcgv_1_1math_1_1v3__func" ],
        [ "perm_mat", "structcgv_1_1math_1_1perm__mat.html", "structcgv_1_1math_1_1perm__mat" ],
        [ "qem", "classcgv_1_1math_1_1qem.html", "classcgv_1_1math_1_1qem" ],
        [ "quaternion", "classcgv_1_1math_1_1quaternion.html", "classcgv_1_1math_1_1quaternion" ],
        [ "random", "structcgv_1_1math_1_1random.html", "structcgv_1_1math_1_1random" ],
        [ "ray", "classcgv_1_1math_1_1ray.html", "classcgv_1_1math_1_1ray" ],
        [ "ray< T, 3 >", "classcgv_1_1math_1_1ray_3_01T_00_013_01_4.html", "classcgv_1_1math_1_1ray_3_01T_00_013_01_4" ],
        [ "rigid_transform", "classcgv_1_1math_1_1rigid__transform.html", "classcgv_1_1math_1_1rigid__transform" ],
        [ "sparse_les_factory", "classcgv_1_1math_1_1sparse__les__factory.html", "classcgv_1_1math_1_1sparse__les__factory" ],
        [ "sparse_les", "classcgv_1_1math_1_1sparse__les.html", "classcgv_1_1math_1_1sparse__les" ],
        [ "sparse_les_factory_impl", "classcgv_1_1math_1_1sparse__les__factory__impl.html", "classcgv_1_1math_1_1sparse__les__factory__impl" ],
        [ "register_sparse_les_factory", "structcgv_1_1math_1_1register__sparse__les__factory.html", null ],
        [ "thin_plate_spline", "structcgv_1_1math_1_1thin__plate__spline.html", "structcgv_1_1math_1_1thin__plate__spline" ],
        [ "thin_hyper_plate_spline", "structcgv_1_1math_1_1thin__hyper__plate__spline.html", "structcgv_1_1math_1_1thin__hyper__plate__spline" ],
        [ "tri_diag_mat", "classcgv_1_1math_1_1tri__diag__mat.html", "classcgv_1_1math_1_1tri__diag__mat" ],
        [ "union_find", "structcgv_1_1math_1_1union__find.html", "structcgv_1_1math_1_1union__find" ]
      ] ],
      [ "media", null, [
        [ "font", "namespacecgv_1_1media_1_1font.html", [
          [ "font_face", "classcgv_1_1media_1_1font_1_1font__face.html", "classcgv_1_1media_1_1font_1_1font__face" ],
          [ "font", "classcgv_1_1media_1_1font_1_1font.html", "classcgv_1_1media_1_1font_1_1font" ],
          [ "font_server", "classcgv_1_1media_1_1font_1_1font__server.html", "classcgv_1_1media_1_1font_1_1font__server" ]
        ] ],
        [ "illum", null, [
          [ "light_source", "classcgv_1_1media_1_1illum_1_1light__source.html", "classcgv_1_1media_1_1illum_1_1light__source" ],
          [ "obj_material", "classcgv_1_1media_1_1illum_1_1obj__material.html", "classcgv_1_1media_1_1illum_1_1obj__material" ],
          [ "phong_material", "classcgv_1_1media_1_1illum_1_1phong__material.html", "classcgv_1_1media_1_1illum_1_1phong__material" ],
          [ "surface_material", "classcgv_1_1media_1_1illum_1_1surface__material.html", "classcgv_1_1media_1_1illum_1_1surface__material" ],
          [ "textured_surface_material", "classcgv_1_1media_1_1illum_1_1textured__surface__material.html", "classcgv_1_1media_1_1illum_1_1textured__surface__material" ]
        ] ],
        [ "image", "namespacecgv_1_1media_1_1image.html", [
          [ "bmp_reader", "classcgv_1_1media_1_1image_1_1bmp__reader.html", "classcgv_1_1media_1_1image_1_1bmp__reader" ],
          [ "bmp_writer", "classcgv_1_1media_1_1image_1_1bmp__writer.html", "classcgv_1_1media_1_1image_1_1bmp__writer" ],
          [ "reader_listener", "structcgv_1_1media_1_1image_1_1reader__listener.html", "structcgv_1_1media_1_1image_1_1reader__listener" ],
          [ "abst_image_reader", "classcgv_1_1media_1_1image_1_1abst__image__reader.html", "classcgv_1_1media_1_1image_1_1abst__image__reader" ],
          [ "image_reader", "classcgv_1_1media_1_1image_1_1image__reader.html", "classcgv_1_1media_1_1image_1_1image__reader" ],
          [ "writer_listener", "structcgv_1_1media_1_1image_1_1writer__listener.html", "structcgv_1_1media_1_1image_1_1writer__listener" ],
          [ "abst_image_writer", "classcgv_1_1media_1_1image_1_1abst__image__writer.html", "classcgv_1_1media_1_1image_1_1abst__image__writer" ],
          [ "image_writer", "classcgv_1_1media_1_1image_1_1image__writer.html", "classcgv_1_1media_1_1image_1_1image__writer" ]
        ] ],
        [ "mesh", null, [
          [ "convex_polyhedron", "classcgv_1_1media_1_1mesh_1_1convex__polyhedron.html", "classcgv_1_1media_1_1mesh_1_1convex__polyhedron" ],
          [ "c_slice_info", "structcgv_1_1media_1_1mesh_1_1c__slice__info.html", null ],
          [ "cuberille", "classcgv_1_1media_1_1mesh_1_1cuberille.html", "classcgv_1_1media_1_1mesh_1_1cuberille" ],
          [ "cell_info", "structcgv_1_1media_1_1mesh_1_1cell__info.html", null ],
          [ "dc_slice_info", "structcgv_1_1media_1_1mesh_1_1dc__slice__info.html", "structcgv_1_1media_1_1mesh_1_1dc__slice__info" ],
          [ "dual_contouring", "classcgv_1_1media_1_1mesh_1_1dual__contouring.html", "classcgv_1_1media_1_1mesh_1_1dual__contouring" ],
          [ "dynamic_mesh", "classcgv_1_1media_1_1mesh_1_1dynamic__mesh.html", "classcgv_1_1media_1_1mesh_1_1dynamic__mesh" ],
          [ "slice_info", "structcgv_1_1media_1_1mesh_1_1slice__info.html", "structcgv_1_1media_1_1mesh_1_1slice__info" ],
          [ "marching_cubes_base", "classcgv_1_1media_1_1mesh_1_1marching__cubes__base.html", "classcgv_1_1media_1_1mesh_1_1marching__cubes__base" ],
          [ "marching_cubes", "classcgv_1_1media_1_1mesh_1_1marching__cubes.html", "classcgv_1_1media_1_1mesh_1_1marching__cubes" ],
          [ "face_info", "structcgv_1_1media_1_1mesh_1_1face__info.html", "structcgv_1_1media_1_1mesh_1_1face__info" ],
          [ "line_info", "structcgv_1_1media_1_1mesh_1_1line__info.html", "structcgv_1_1media_1_1mesh_1_1line__info" ],
          [ "group_info", "structcgv_1_1media_1_1mesh_1_1group__info.html", "structcgv_1_1media_1_1mesh_1_1group__info" ],
          [ "obj_loader_generic", "classcgv_1_1media_1_1mesh_1_1obj__loader__generic.html", "classcgv_1_1media_1_1mesh_1_1obj__loader__generic" ],
          [ "obj_reader_base", "classcgv_1_1media_1_1mesh_1_1obj__reader__base.html", "classcgv_1_1media_1_1mesh_1_1obj__reader__base" ],
          [ "obj_reader_generic", "classcgv_1_1media_1_1mesh_1_1obj__reader__generic.html", "classcgv_1_1media_1_1mesh_1_1obj__reader__generic" ],
          [ "simple_mesh_base", "classcgv_1_1media_1_1mesh_1_1simple__mesh__base.html", "classcgv_1_1media_1_1mesh_1_1simple__mesh__base" ],
          [ "simple_mesh", "classcgv_1_1media_1_1mesh_1_1simple__mesh.html", "classcgv_1_1media_1_1mesh_1_1simple__mesh" ],
          [ "streaming_mesh_callback_handler", "structcgv_1_1media_1_1mesh_1_1streaming__mesh__callback__handler.html", "structcgv_1_1media_1_1mesh_1_1streaming__mesh__callback__handler" ],
          [ "streaming_mesh", "classcgv_1_1media_1_1mesh_1_1streaming__mesh.html", "classcgv_1_1media_1_1mesh_1_1streaming__mesh" ]
        ] ],
        [ "video", "namespacecgv_1_1media_1_1video.html", [
          [ "video_reader_listener", "structcgv_1_1media_1_1video_1_1video__reader__listener.html", "structcgv_1_1media_1_1video_1_1video__reader__listener" ],
          [ "abst_video_reader", "classcgv_1_1media_1_1video_1_1abst__video__reader.html", "classcgv_1_1media_1_1video_1_1abst__video__reader" ],
          [ "video_reader", "classcgv_1_1media_1_1video_1_1video__reader.html", "classcgv_1_1media_1_1video_1_1video__reader" ],
          [ "video_writer_listener", "structcgv_1_1media_1_1video_1_1video__writer__listener.html", "structcgv_1_1media_1_1video_1_1video__writer__listener" ],
          [ "abst_video_writer", "classcgv_1_1media_1_1video_1_1abst__video__writer.html", "classcgv_1_1media_1_1video_1_1abst__video__writer" ],
          [ "video_writer", "classcgv_1_1media_1_1video_1_1video__writer.html", "classcgv_1_1media_1_1video_1_1video__writer" ]
        ] ],
        [ "volume", null, [
          [ "ooc_sliced_volume", "structcgv_1_1media_1_1volume_1_1ooc__sliced__volume.html", "structcgv_1_1media_1_1volume_1_1ooc__sliced__volume" ]
        ] ],
        [ "axis_aligned_box", "classcgv_1_1media_1_1axis__aligned__box.html", "classcgv_1_1media_1_1axis__aligned__box" ],
        [ "color", "classcgv_1_1media_1_1color.html", "classcgv_1_1media_1_1color" ],
        [ "dummy_alpha", "structcgv_1_1media_1_1dummy__alpha.html", null ],
        [ "rgb_color_interface", "structcgv_1_1media_1_1rgb__color__interface.html", null ],
        [ "rgb_color_interface< color< T, cm, am > >", "structcgv_1_1media_1_1rgb__color__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1rgb__color__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4" ],
        [ "rgb_color_interface< color< T, RGB, am > >", "structcgv_1_1media_1_1rgb__color__interface_3_01color_3_01T_00_01RGB_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1rgb__color__interface_3_01color_3_01T_00_01RGB_00_01am_01_4_01_4" ],
        [ "hls_color_interface", "structcgv_1_1media_1_1hls__color__interface.html", null ],
        [ "hls_color_interface< color< T, cm, am > >", "structcgv_1_1media_1_1hls__color__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1hls__color__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4" ],
        [ "hls_color_interface< color< T, HLS, am > >", "structcgv_1_1media_1_1hls__color__interface_3_01color_3_01T_00_01HLS_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1hls__color__interface_3_01color_3_01T_00_01HLS_00_01am_01_4_01_4" ],
        [ "xyz_color_interface", "structcgv_1_1media_1_1xyz__color__interface.html", null ],
        [ "xyz_color_interface< color< T, cm, am > >", "structcgv_1_1media_1_1xyz__color__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1xyz__color__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4" ],
        [ "xyz_color_interface< color< T, XYZ, am > >", "structcgv_1_1media_1_1xyz__color__interface_3_01color_3_01T_00_01XYZ_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1xyz__color__interface_3_01color_3_01T_00_01XYZ_00_01am_01_4_01_4" ],
        [ "opacity_alpha_interface", "structcgv_1_1media_1_1opacity__alpha__interface.html", null ],
        [ "opacity_alpha_interface< color< T, cm, am > >", "structcgv_1_1media_1_1opacity__alpha__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1opacity__alpha__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4" ],
        [ "opacity_alpha_interface< color< T, cm, OPACITY > >", "structcgv_1_1media_1_1opacity__alpha__interface_3_01color_3_01T_00_01cm_00_01OPACITY_01_4_01_4.html", "structcgv_1_1media_1_1opacity__alpha__interface_3_01color_3_01T_00_01cm_00_01OPACITY_01_4_01_4" ],
        [ "transparency_alpha_interface", "structcgv_1_1media_1_1transparency__alpha__interface.html", null ],
        [ "transparency_alpha_interface< color< T, cm, am > >", "structcgv_1_1media_1_1transparency__alpha__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1transparency__alpha__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4" ],
        [ "transparency_alpha_interface< color< T, cm, TRANSPARENCY > >", "structcgv_1_1media_1_1transparency__alpha__interface_3_01color_3_01T_00_01cm_00_01TRANSPARENCY_01_4_01_4.html", "structcgv_1_1media_1_1transparency__alpha__interface_3_01color_3_01T_00_01cm_00_01TRANSPARENCY_01_4_01_4" ],
        [ "extinction_alpha_interface", "structcgv_1_1media_1_1extinction__alpha__interface.html", null ],
        [ "extinction_alpha_interface< color< T, cm, am > >", "structcgv_1_1media_1_1extinction__alpha__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4.html", "structcgv_1_1media_1_1extinction__alpha__interface_3_01color_3_01T_00_01cm_00_01am_01_4_01_4" ],
        [ "extinction_alpha_interface< color< T, cm, EXTINCTION > >", "structcgv_1_1media_1_1extinction__alpha__interface_3_01color_3_01T_00_01cm_00_01EXTINCTION_01_4_01_4.html", "structcgv_1_1media_1_1extinction__alpha__interface_3_01color_3_01T_00_01cm_00_01EXTINCTION_01_4_01_4" ],
        [ "color_storage_traits", "structcgv_1_1media_1_1color__storage__traits.html", null ],
        [ "color_storage_types", "structcgv_1_1media_1_1color__storage__types.html", "structcgv_1_1media_1_1color__storage__types" ],
        [ "abst_color_storage", "classcgv_1_1media_1_1abst__color__storage.html", "classcgv_1_1media_1_1abst__color__storage" ],
        [ "color_storage", "classcgv_1_1media_1_1color__storage.html", "classcgv_1_1media_1_1color__storage" ],
        [ "colored_model", "classcgv_1_1media_1_1colored__model.html", "classcgv_1_1media_1_1colored__model" ],
        [ "plane", "classcgv_1_1media_1_1plane.html", "classcgv_1_1media_1_1plane" ],
        [ "ray", "classcgv_1_1media_1_1ray.html", "classcgv_1_1media_1_1ray" ],
        [ "fourcc", "structcgv_1_1media_1_1fourcc.html", "structcgv_1_1media_1_1fourcc" ],
        [ "riff_handler", "structcgv_1_1media_1_1riff__handler.html", "structcgv_1_1media_1_1riff__handler" ],
        [ "riff_reader", "classcgv_1_1media_1_1riff__reader.html", "classcgv_1_1media_1_1riff__reader" ],
        [ "sphere", "classcgv_1_1media_1_1sphere.html", "classcgv_1_1media_1_1sphere" ]
      ] ],
      [ "os", null, [
        [ "display_mode", "structcgv_1_1os_1_1display__mode.html", "structcgv_1_1os_1_1display__mode" ],
        [ "display_position", "structcgv_1_1os_1_1display__position.html", "structcgv_1_1os_1_1display__position" ],
        [ "display_configuration", "structcgv_1_1os_1_1display__configuration.html", "structcgv_1_1os_1_1display__configuration" ],
        [ "display", "classcgv_1_1os_1_1display.html", "classcgv_1_1os_1_1display" ],
        [ "http_request", "structcgv_1_1os_1_1http__request.html", "structcgv_1_1os_1_1http__request" ],
        [ "mutex", "structcgv_1_1os_1_1mutex.html", "structcgv_1_1os_1_1mutex" ],
        [ "condition_mutex", "structcgv_1_1os_1_1condition__mutex.html", "structcgv_1_1os_1_1condition__mutex" ],
        [ "socket", "classcgv_1_1os_1_1socket.html", "classcgv_1_1os_1_1socket" ],
        [ "socket_client", "classcgv_1_1os_1_1socket__client.html", "classcgv_1_1os_1_1socket__client" ],
        [ "socket_server", "classcgv_1_1os_1_1socket__server.html", "classcgv_1_1os_1_1socket__server" ],
        [ "thread", "classcgv_1_1os_1_1thread.html", "classcgv_1_1os_1_1thread" ],
        [ "web_server", "classcgv_1_1os_1_1web__server.html", "classcgv_1_1os_1_1web__server" ],
        [ "web_server_thread", "classcgv_1_1os_1_1web__server__thread.html", "classcgv_1_1os_1_1web__server__thread" ],
        [ "web_server_provider", "classcgv_1_1os_1_1web__server__provider.html", null ],
        [ "web_server_provider_registration", "structcgv_1_1os_1_1web__server__provider__registration.html", null ]
      ] ],
      [ "plot", null, [
        [ "tick_config", "structcgv_1_1plot_1_1tick__config.html", "structcgv_1_1plot_1_1tick__config" ],
        [ "axis_config", "classcgv_1_1plot_1_1axis__config.html", "classcgv_1_1plot_1_1axis__config" ],
        [ "plot2d_config", "structcgv_1_1plot_1_1plot2d__config.html", "structcgv_1_1plot_1_1plot2d__config" ],
        [ "plot2d", "classcgv_1_1plot_1_1plot2d.html", "classcgv_1_1plot_1_1plot2d" ],
        [ "plot3d_config", "structcgv_1_1plot_1_1plot3d__config.html", "structcgv_1_1plot_1_1plot3d__config" ],
        [ "plot3d", "classcgv_1_1plot_1_1plot3d.html", "classcgv_1_1plot_1_1plot3d" ],
        [ "plot_base_config", "structcgv_1_1plot_1_1plot__base__config.html", "structcgv_1_1plot_1_1plot__base__config" ],
        [ "attribute_source", "structcgv_1_1plot_1_1attribute__source.html", "structcgv_1_1plot_1_1attribute__source" ],
        [ "attribute_source_array", "structcgv_1_1plot_1_1attribute__source__array.html", null ],
        [ "plot_base", "classcgv_1_1plot_1_1plot__base.html", "classcgv_1_1plot_1_1plot__base" ]
      ] ],
      [ "ppp", null, [
        [ "ph_processor", "classcgv_1_1ppp_1_1ph__processor.html", null ],
        [ "namespace_info", "structcgv_1_1ppp_1_1namespace__info.html", null ]
      ] ],
      [ "reflect", "namespacecgv_1_1reflect.html", [
        [ "debug_reflection_handler", "classcgv_1_1reflect_1_1debug__reflection__handler.html", "classcgv_1_1reflect_1_1debug__reflection__handler" ],
        [ "find_reflection_handler", "classcgv_1_1reflect_1_1find__reflection__handler.html", "classcgv_1_1reflect_1_1find__reflection__handler" ],
        [ "get_reflection_handler", "classcgv_1_1reflect_1_1get__reflection__handler.html", "classcgv_1_1reflect_1_1get__reflection__handler" ],
        [ "abst_enum_reflection_traits", "structcgv_1_1reflect_1_1abst__enum__reflection__traits.html", "structcgv_1_1reflect_1_1abst__enum__reflection__traits" ],
        [ "enum_reflection_traits", "structcgv_1_1reflect_1_1enum__reflection__traits.html", "structcgv_1_1reflect_1_1enum__reflection__traits" ],
        [ "extern_reflection_traits_impl", "structcgv_1_1reflect_1_1extern__reflection__traits__impl.html", "structcgv_1_1reflect_1_1extern__reflection__traits__impl" ],
        [ "extern_reflection_traits", "structcgv_1_1reflect_1_1extern__reflection__traits.html", "structcgv_1_1reflect_1_1extern__reflection__traits" ],
        [ "extern_string_reflection_traits", "structcgv_1_1reflect_1_1extern__string__reflection__traits.html", "structcgv_1_1reflect_1_1extern__string__reflection__traits" ],
        [ "method_interface", "structcgv_1_1reflect_1_1method__interface.html", null ],
        [ "method_interface_impl", "structcgv_1_1reflect_1_1method__interface__impl.html", null ],
        [ "reflection_handler", "classcgv_1_1reflect_1_1reflection__handler.html", "classcgv_1_1reflect_1_1reflection__handler" ],
        [ "abst_reflection_traits", "structcgv_1_1reflect_1_1abst__reflection__traits.html", "structcgv_1_1reflect_1_1abst__reflection__traits" ],
        [ "reflection_traits_impl", "structcgv_1_1reflect_1_1reflection__traits__impl.html", "structcgv_1_1reflect_1_1reflection__traits__impl" ],
        [ "reflection_traits_impl< T, B, true >", "structcgv_1_1reflect_1_1reflection__traits__impl_3_01T_00_01B_00_01true_01_4.html", "structcgv_1_1reflect_1_1reflection__traits__impl_3_01T_00_01B_00_01true_01_4" ],
        [ "reflection_traits_string_impl", "structcgv_1_1reflect_1_1reflection__traits__string__impl.html", "structcgv_1_1reflect_1_1reflection__traits__string__impl" ],
        [ "reflection_traits_string_impl< true, T, B >", "structcgv_1_1reflect_1_1reflection__traits__string__impl_3_01true_00_01T_00_01B_01_4.html", "structcgv_1_1reflect_1_1reflection__traits__string__impl_3_01true_00_01T_00_01B_01_4" ],
        [ "reflection_traits", "structcgv_1_1reflect_1_1reflection__traits.html", "structcgv_1_1reflect_1_1reflection__traits" ],
        [ "reflection_traits_info", "structcgv_1_1reflect_1_1reflection__traits__info.html", null ],
        [ "self_reflection_tag", "structcgv_1_1reflect_1_1self__reflection__tag.html", null ]
      ] ],
      [ "render", "namespacecgv_1_1render.html", [
        [ "gl", "namespacecgv_1_1render_1_1gl.html", [
          [ "gl_traits", "structcgv_1_1render_1_1gl_1_1gl__traits.html", null ],
          [ "gl_context", "classcgv_1_1render_1_1gl_1_1gl__context.html", "classcgv_1_1render_1_1gl_1_1gl__context" ],
          [ "gl_cursor", "classcgv_1_1render_1_1gl_1_1gl__cursor.html", "classcgv_1_1render_1_1gl_1_1gl__cursor" ],
          [ "gl_depth_peeler", "classcgv_1_1render_1_1gl_1_1gl__depth__peeler.html", "classcgv_1_1render_1_1gl_1_1gl__depth__peeler" ],
          [ "gl_implicit_surface_drawable_base", "classcgv_1_1render_1_1gl_1_1gl__implicit__surface__drawable__base.html", "classcgv_1_1render_1_1gl_1_1gl__implicit__surface__drawable__base" ],
          [ "gl_transparent_renderer", "classcgv_1_1render_1_1gl_1_1gl__transparent__renderer.html", "classcgv_1_1render_1_1gl_1_1gl__transparent__renderer" ],
          [ "image_drawable", "classcgv_1_1render_1_1gl_1_1image__drawable.html", "classcgv_1_1render_1_1gl_1_1image__drawable" ],
          [ "mesh_drawable", "classcgv_1_1render_1_1gl_1_1mesh__drawable.html", "classcgv_1_1render_1_1gl_1_1mesh__drawable" ]
        ] ],
        [ "attribute_array_binding", "classcgv_1_1render_1_1attribute__array__binding.html", "classcgv_1_1render_1_1attribute__array__binding" ],
        [ "callback_drawable", "structcgv_1_1render_1_1callback__drawable.html", "structcgv_1_1render_1_1callback__drawable" ],
        [ "clipped_view", "classcgv_1_1render_1_1clipped__view.html", "classcgv_1_1render_1_1clipped__view" ],
        [ "type_descriptor", "structcgv_1_1render_1_1type__descriptor.html", "structcgv_1_1render_1_1type__descriptor" ],
        [ "render_component", "classcgv_1_1render_1_1render__component.html", "classcgv_1_1render_1_1render__component" ],
        [ "render_buffer_base", "classcgv_1_1render_1_1render__buffer__base.html", "classcgv_1_1render_1_1render__buffer__base" ],
        [ "texture_base", "classcgv_1_1render_1_1texture__base.html", "classcgv_1_1render_1_1texture__base" ],
        [ "shader_program_base", "classcgv_1_1render_1_1shader__program__base.html", "classcgv_1_1render_1_1shader__program__base" ],
        [ "attribute_array_binding_base", "classcgv_1_1render_1_1attribute__array__binding__base.html", "classcgv_1_1render_1_1attribute__array__binding__base" ],
        [ "vertex_buffer_base", "classcgv_1_1render_1_1vertex__buffer__base.html", "classcgv_1_1render_1_1vertex__buffer__base" ],
        [ "frame_buffer_base", "classcgv_1_1render_1_1frame__buffer__base.html", "classcgv_1_1render_1_1frame__buffer__base" ],
        [ "context_config", "structcgv_1_1render_1_1context__config.html", "structcgv_1_1render_1_1context__config" ],
        [ "render_config", "structcgv_1_1render_1_1render__config.html", "structcgv_1_1render_1_1render__config" ],
        [ "window_transformation", "structcgv_1_1render_1_1window__transformation.html", "structcgv_1_1render_1_1window__transformation" ],
        [ "context", "classcgv_1_1render_1_1context.html", "classcgv_1_1render_1_1context" ],
        [ "drawable", "classcgv_1_1render_1_1drawable.html", "classcgv_1_1render_1_1drawable" ],
        [ "multi_pass_drawable", "classcgv_1_1render_1_1multi__pass__drawable.html", "classcgv_1_1render_1_1multi__pass__drawable" ],
        [ "frame_buffer", "classcgv_1_1render_1_1frame__buffer.html", "classcgv_1_1render_1_1frame__buffer" ],
        [ "managed_frame_buffer", "classcgv_1_1render_1_1managed__frame__buffer.html", "classcgv_1_1render_1_1managed__frame__buffer" ],
        [ "performance_monitor", "classcgv_1_1render_1_1performance__monitor.html", "classcgv_1_1render_1_1performance__monitor" ],
        [ "render_buffer", "classcgv_1_1render_1_1render__buffer.html", "classcgv_1_1render_1_1render__buffer" ],
        [ "textured_rectangle", "structcgv_1_1render_1_1textured__rectangle.html", null ],
        [ "shader_config", "structcgv_1_1render_1_1shader__config.html", "structcgv_1_1render_1_1shader__config" ],
        [ "shader_code", "classcgv_1_1render_1_1shader__code.html", "classcgv_1_1render_1_1shader__code" ],
        [ "shader_library", "classcgv_1_1render_1_1shader__library.html", null ],
        [ "shader_program", "classcgv_1_1render_1_1shader__program.html", "classcgv_1_1render_1_1shader__program" ],
        [ "stereo_view", "classcgv_1_1render_1_1stereo__view.html", "classcgv_1_1render_1_1stereo__view" ],
        [ "texture", "classcgv_1_1render_1_1texture.html", "classcgv_1_1render_1_1texture" ],
        [ "textured_material", "classcgv_1_1render_1_1textured__material.html", "classcgv_1_1render_1_1textured__material" ],
        [ "vertex_buffer", "classcgv_1_1render_1_1vertex__buffer.html", "classcgv_1_1render_1_1vertex__buffer" ],
        [ "view", "classcgv_1_1render_1_1view.html", "classcgv_1_1render_1_1view" ],
        [ "a_buffer", "classcgv_1_1render_1_1a__buffer.html", "classcgv_1_1render_1_1a__buffer" ],
        [ "arrow_render_style", "structcgv_1_1render_1_1arrow__render__style.html", "structcgv_1_1render_1_1arrow__render__style" ],
        [ "arrow_renderer", "classcgv_1_1render_1_1arrow__renderer.html", "classcgv_1_1render_1_1arrow__renderer" ],
        [ "attribute_array_manager", "classcgv_1_1render_1_1attribute__array__manager.html", "classcgv_1_1render_1_1attribute__array__manager" ],
        [ "box_render_data", "classcgv_1_1render_1_1box__render__data.html", "classcgv_1_1render_1_1box__render__data" ],
        [ "box_render_style", "structcgv_1_1render_1_1box__render__style.html", "structcgv_1_1render_1_1box__render__style" ],
        [ "box_renderer", "classcgv_1_1render_1_1box__renderer.html", "classcgv_1_1render_1_1box__renderer" ],
        [ "box_wire_render_data", "classcgv_1_1render_1_1box__wire__render__data.html", "classcgv_1_1render_1_1box__wire__render__data" ],
        [ "box_wire_render_style", "structcgv_1_1render_1_1box__wire__render__style.html", "structcgv_1_1render_1_1box__wire__render__style" ],
        [ "box_wire_renderer", "classcgv_1_1render_1_1box__wire__renderer.html", "classcgv_1_1render_1_1box__wire__renderer" ],
        [ "clod_point_render_style", "structcgv_1_1render_1_1clod__point__render__style.html", "structcgv_1_1render_1_1clod__point__render__style" ],
        [ "cone_render_data", "classcgv_1_1render_1_1cone__render__data.html", "classcgv_1_1render_1_1cone__render__data" ],
        [ "cone_renderer", "classcgv_1_1render_1_1cone__renderer.html", "classcgv_1_1render_1_1cone__renderer" ],
        [ "mesh_render_info", "classcgv_1_1render_1_1mesh__render__info.html", "classcgv_1_1render_1_1mesh__render__info" ],
        [ "render_info", "classcgv_1_1render_1_1render__info.html", "classcgv_1_1render_1_1render__info" ],
        [ "group_render_style", "structcgv_1_1render_1_1group__render__style.html", "structcgv_1_1render_1_1group__render__style" ],
        [ "group_renderer", "classcgv_1_1render_1_1group__renderer.html", "classcgv_1_1render_1_1group__renderer" ],
        [ "line_render_data", "classcgv_1_1render_1_1line__render__data.html", "classcgv_1_1render_1_1line__render__data" ],
        [ "line_render_style", "structcgv_1_1render_1_1line__render__style.html", "structcgv_1_1render_1_1line__render__style" ],
        [ "line_renderer", "classcgv_1_1render_1_1line__renderer.html", "classcgv_1_1render_1_1line__renderer" ],
        [ "normal_renderer", "classcgv_1_1render_1_1normal__renderer.html", "classcgv_1_1render_1_1normal__renderer" ],
        [ "point_render_data", "classcgv_1_1render_1_1point__render__data.html", "classcgv_1_1render_1_1point__render__data" ],
        [ "point_render_style", "structcgv_1_1render_1_1point__render__style.html", "structcgv_1_1render_1_1point__render__style" ],
        [ "point_renderer", "classcgv_1_1render_1_1point__renderer.html", "classcgv_1_1render_1_1point__renderer" ],
        [ "rectangle_render_data", "classcgv_1_1render_1_1rectangle__render__data.html", "classcgv_1_1render_1_1rectangle__render__data" ],
        [ "rectangle_render_style", "structcgv_1_1render_1_1rectangle__render__style.html", "structcgv_1_1render_1_1rectangle__render__style" ],
        [ "rectangle_renderer", "classcgv_1_1render_1_1rectangle__renderer.html", "classcgv_1_1render_1_1rectangle__renderer" ],
        [ "render_data_base", "classcgv_1_1render_1_1render__data__base.html", "classcgv_1_1render_1_1render__data__base" ],
        [ "render_style", "structcgv_1_1render_1_1render__style.html", null ],
        [ "renderer", "classcgv_1_1render_1_1renderer.html", "classcgv_1_1render_1_1renderer" ],
        [ "slab_render_style", "structcgv_1_1render_1_1slab__render__style.html", "structcgv_1_1render_1_1slab__render__style" ],
        [ "slab_renderer", "classcgv_1_1render_1_1slab__renderer.html", "classcgv_1_1render_1_1slab__renderer" ],
        [ "sphere_render_data", "classcgv_1_1render_1_1sphere__render__data.html", "classcgv_1_1render_1_1sphere__render__data" ],
        [ "sphere_render_style", "structcgv_1_1render_1_1sphere__render__style.html", "structcgv_1_1render_1_1sphere__render__style" ],
        [ "sphere_renderer", "classcgv_1_1render_1_1sphere__renderer.html", "classcgv_1_1render_1_1sphere__renderer" ],
        [ "spline_tube_renderer", "classcgv_1_1render_1_1spline__tube__renderer.html", "classcgv_1_1render_1_1spline__tube__renderer" ],
        [ "surface_render_style", "structcgv_1_1render_1_1surface__render__style.html", "structcgv_1_1render_1_1surface__render__style" ],
        [ "surface_renderer", "classcgv_1_1render_1_1surface__renderer.html", "classcgv_1_1render_1_1surface__renderer" ],
        [ "surfel_render_style", "structcgv_1_1render_1_1surfel__render__style.html", "structcgv_1_1render_1_1surfel__render__style" ],
        [ "surfel_renderer", "classcgv_1_1render_1_1surfel__renderer.html", "classcgv_1_1render_1_1surfel__renderer" ],
        [ "volume_render_style", "structcgv_1_1render_1_1volume__render__style.html", "structcgv_1_1render_1_1volume__render__style" ],
        [ "volume_renderer", "classcgv_1_1render_1_1volume__renderer.html", "classcgv_1_1render_1_1volume__renderer" ]
      ] ],
      [ "signal", null, [
        [ "bool_combiner", "classcgv_1_1signal_1_1bool__combiner.html", "classcgv_1_1signal_1_1bool__combiner" ],
        [ "callback_streambuf", "structcgv_1_1signal_1_1callback__streambuf.html", null ],
        [ "callback_stream", "classcgv_1_1signal_1_1callback__stream.html", "classcgv_1_1signal_1_1callback__stream" ]
      ] ],
      [ "type", "namespacecgv_1_1type.html", [
        [ "cond", "namespacecgv_1_1type_1_1cond.html", [
          [ "has_virtual_destructor", "structcgv_1_1type_1_1cond_1_1has__virtual__destructor.html", null ],
          [ "is_abstract", "structcgv_1_1type_1_1cond_1_1is__abstract.html", null ],
          [ "is_base_of", "structcgv_1_1type_1_1cond_1_1is__base__of.html", null ],
          [ "is_const", "structcgv_1_1type_1_1cond_1_1is__const.html", null ],
          [ "is_enum", "structcgv_1_1type_1_1cond_1_1is__enum.html", null ],
          [ "is_standard_type", "structcgv_1_1type_1_1cond_1_1is__standard__type.html", null ]
        ] ],
        [ "ctrl", null, [
          [ "if_", "structcgv_1_1type_1_1ctrl_1_1if__.html", null ]
        ] ],
        [ "func", "namespacecgv_1_1type_1_1func.html", [
          [ "Promote", null, [
            [ "promotion_rank", "structcgv_1_1type_1_1func_1_1Promote_1_1promotion__rank.html", null ]
          ] ],
          [ "clean", "structcgv_1_1type_1_1func_1_1clean.html", null ],
          [ "clean_traits", "structcgv_1_1type_1_1func_1_1clean__traits.html", null ],
          [ "drop_const", "structcgv_1_1type_1_1func_1_1drop__const.html", "structcgv_1_1type_1_1func_1_1drop__const" ],
          [ "drop_const< const T >", "structcgv_1_1type_1_1func_1_1drop__const_3_01const_01T_01_4.html", "structcgv_1_1type_1_1func_1_1drop__const_3_01const_01T_01_4" ],
          [ "drop_const< T & >", "structcgv_1_1type_1_1func_1_1drop__const_3_01T_01_6_01_4.html", "structcgv_1_1type_1_1func_1_1drop__const_3_01T_01_6_01_4" ],
          [ "drop_pointer", "structcgv_1_1type_1_1func_1_1drop__pointer.html", "structcgv_1_1type_1_1func_1_1drop__pointer" ],
          [ "drop_pointer< T * >", "structcgv_1_1type_1_1func_1_1drop__pointer_3_01T_01_5_01_4.html", "structcgv_1_1type_1_1func_1_1drop__pointer_3_01T_01_5_01_4" ],
          [ "drop_ref", "structcgv_1_1type_1_1func_1_1drop__ref.html", "structcgv_1_1type_1_1func_1_1drop__ref" ],
          [ "drop_ref< T & >", "structcgv_1_1type_1_1func_1_1drop__ref_3_01T_01_6_01_4.html", "structcgv_1_1type_1_1func_1_1drop__ref_3_01T_01_6_01_4" ],
          [ "make_argument", "structcgv_1_1type_1_1func_1_1make__argument.html", null ],
          [ "make_const", "structcgv_1_1type_1_1func_1_1make__const.html", null ],
          [ "make_ref", "structcgv_1_1type_1_1func_1_1make__ref.html", null ],
          [ "promote", "structcgv_1_1type_1_1func_1_1promote.html", null ],
          [ "promote_const", "structcgv_1_1type_1_1func_1_1promote__const.html", null ],
          [ "transfer_const", "structcgv_1_1type_1_1func_1_1transfer__const.html", null ]
        ] ],
        [ "info", "namespacecgv_1_1type_1_1info.html", [
          [ "type_access", "structcgv_1_1type_1_1info_1_1type__access.html", "structcgv_1_1type_1_1info_1_1type__access" ],
          [ "type_id", "structcgv_1_1type_1_1info_1_1type__id.html", null ],
          [ "type_name", "structcgv_1_1type_1_1info_1_1type__name.html", "structcgv_1_1type_1_1info_1_1type__name" ],
          [ "type_ptr", "structcgv_1_1type_1_1info_1_1type__ptr.html", null ]
        ] ],
        [ "traits", null, [
          [ "max", "structcgv_1_1type_1_1traits_1_1max.html", null ],
          [ "max_fct", "structcgv_1_1type_1_1traits_1_1max__fct.html", null ],
          [ "member_pointer", "structcgv_1_1type_1_1traits_1_1member__pointer.html", null ],
          [ "min", "structcgv_1_1type_1_1traits_1_1min.html", null ],
          [ "min_fct", "structcgv_1_1type_1_1traits_1_1min__fct.html", null ],
          [ "one", "structcgv_1_1type_1_1traits_1_1one.html", null ],
          [ "one_fct", "structcgv_1_1type_1_1traits_1_1one__fct.html", null ],
          [ "zero", "structcgv_1_1type_1_1traits_1_1zero.html", null ]
        ] ],
        [ "variant", "structcgv_1_1type_1_1variant.html", "structcgv_1_1type_1_1variant" ]
      ] ],
      [ "utils", "namespacecgv_1_1utils.html", [
        [ "line", "structcgv_1_1utils_1_1line.html", "structcgv_1_1utils_1_1line" ],
        [ "typed_token", "structcgv_1_1utils_1_1typed__token.html", "structcgv_1_1utils_1_1typed__token" ],
        [ "big_binary_file", "classcgv_1_1utils_1_1big__binary__file.html", "classcgv_1_1utils_1_1big__binary__file" ],
        [ "Profiler", "classcgv_1_1utils_1_1Profiler.html", null ],
        [ "progression", "structcgv_1_1utils_1_1progression.html", "structcgv_1_1utils_1_1progression" ],
        [ "statistics", "classcgv_1_1utils_1_1statistics.html", "classcgv_1_1utils_1_1statistics" ],
        [ "stopwatch", "classcgv_1_1utils_1_1stopwatch.html", "classcgv_1_1utils_1_1stopwatch" ],
        [ "token", "structcgv_1_1utils_1_1token.html", "structcgv_1_1utils_1_1token" ],
        [ "tokenizer", "classcgv_1_1utils_1_1tokenizer.html", "classcgv_1_1utils_1_1tokenizer" ]
      ] ],
      [ "xml", null, [
        [ "FindElementByNameVisitor", "classcgv_1_1xml_1_1FindElementByNameVisitor.html", "classcgv_1_1xml_1_1FindElementByNameVisitor" ]
      ] ]
    ] ],
    [ "gamepad", null, [
      [ "driver_info", "structgamepad_1_1driver__info.html", "structgamepad_1_1driver__info" ],
      [ "device_info", "structgamepad_1_1device__info.html", "structgamepad_1_1device__info" ],
      [ "gamepad_state", "structgamepad_1_1gamepad__state.html", "structgamepad_1_1gamepad__state" ],
      [ "gamepad_driver", "structgamepad_1_1gamepad__driver.html", "structgamepad_1_1gamepad__driver" ],
      [ "driver_registry", "structgamepad_1_1driver__registry.html", null ]
    ] ],
    [ "stl_reader", null, [
      [ "StlMesh", "classstl__reader_1_1StlMesh.html", "classstl__reader_1_1StlMesh" ]
    ] ],
    [ "vr", "namespacevr.html", [
      [ "gl_vr_display", "classvr_1_1gl__vr__display.html", "classvr_1_1gl__vr__display" ],
      [ "vr_camera", "classvr_1_1vr__camera.html", "classvr_1_1vr__camera" ],
      [ "vr_calibration_base", "classvr_1_1vr__calibration__base.html", "classvr_1_1vr__calibration__base" ],
      [ "vr_driver", "classvr_1_1vr__driver.html", "classvr_1_1vr__driver" ],
      [ "driver_registry", "structvr_1_1driver__registry.html", null ],
      [ "vr_device_info", "structvr_1_1vr__device__info.html", "structvr_1_1vr__device__info" ],
      [ "vr_trackable_info", "structvr_1_1vr__trackable__info.html", "structvr_1_1vr__trackable__info" ],
      [ "vr_hmd_info", "structvr_1_1vr__hmd__info.html", "structvr_1_1vr__hmd__info" ],
      [ "vr_controller_info", "structvr_1_1vr__controller__info.html", "structvr_1_1vr__controller__info" ],
      [ "vr_kit_info", "structvr_1_1vr__kit__info.html", "structvr_1_1vr__kit__info" ],
      [ "vr_tracking_reference_info", "structvr_1_1vr__tracking__reference__info.html", "structvr_1_1vr__tracking__reference__info" ],
      [ "vr_tracking_system_info", "structvr_1_1vr__tracking__system__info.html", "structvr_1_1vr__tracking__system__info" ],
      [ "controller_input_config", "structvr_1_1controller__input__config.html", "structvr_1_1controller__input__config" ],
      [ "vr_kit", "classvr_1_1vr__kit.html", "classvr_1_1vr__kit" ],
      [ "vr_log", "classvr_1_1vr__log.html", "classvr_1_1vr__log" ],
      [ "vr_trackable_state", "structvr_1_1vr__trackable__state.html", "structvr_1_1vr__trackable__state" ],
      [ "vr_controller_state", "structvr_1_1vr__controller__state.html", "structvr_1_1vr__controller__state" ],
      [ "vr_kit_state", "structvr_1_1vr__kit__state.html", "structvr_1_1vr__kit__state" ]
    ] ],
    [ "vr_view_interactor", "classvr__view__interactor.html", "classvr__view__interactor" ]
];