cgv: cgv::render::clod_point_buffer_manager Class Reference
cgv::render::clod_point_buffer_manager Class Reference
Public Member Functions
void init (context &ctx)
void clear (context &ctx)
void resize (GLuint size)
GLuint get_index_buffer ()
get the opengl id used to access the index buffer
GLuint get_draw_parameters ()
get the opengl id used to access the internal draw parameters
GLuint get_reduced_points ()
get the opengl id used to access the internal draw buffer
GLuint num_reduced_points ()
maps draw_parameters to memory and reads size
GLuint size ()
max number of points stored in the managed buffers without resizing
Protected Member Functions
GLuint get_vertex_array ()
Friends
class clod_point_renderer
Detailed Description
Definition at line 28 of file clod_point_renderer.h.
Member Function Documentation
clear()
void cgv::render::clod_point_buffer_manager::clear (context & ctx)
Definition at line 516 of file clod_point_renderer.cxx.
get_draw_parameters()
GLuint cgv::render::clod_point_buffer_manager::get_draw_parameters ()
get the opengl id used to access the internal draw parameters
Definition at line 541 of file clod_point_renderer.cxx.
get_index_buffer()
GLuint cgv::render::clod_point_buffer_manager::get_index_buffer ()
get the opengl id used to access the index buffer
Definition at line 536 of file clod_point_renderer.cxx.
get_reduced_points()
GLuint cgv::render::clod_point_buffer_manager::get_reduced_points ()
get the opengl id used to access the internal draw buffer
Definition at line 546 of file clod_point_renderer.cxx.
get_vertex_array()
GLuint cgv::render::clod_point_buffer_manager::get_vertex_array () protected
Definition at line 481 of file clod_point_renderer.cxx.
init()
void cgv::render::clod_point_buffer_manager::init (context & ctx)
Definition at line 486 of file clod_point_renderer.cxx.
num_reduced_points()
GLuint cgv::render::clod_point_buffer_manager::num_reduced_points ()
maps draw_parameters to memory and reads size
Definition at line 551 of file clod_point_renderer.cxx.
resize()
void cgv::render::clod_point_buffer_manager::resize (GLuint size)
Definition at line 523 of file clod_point_renderer.cxx.
size()
GLuint cgv::render::clod_point_buffer_manager::size ()
max number of points stored in the managed buffers without resizing
Definition at line 560 of file clod_point_renderer.cxx.
Referenced by cgv::render::clod_point_renderer::reduce_buffer_init(), cgv::render::clod_point_renderer::reduce_chunks(), and cgv::render::clod_point_renderer::reduce_points().
Friends And Related Symbol Documentation
clod_point_renderer
friend class clod_point_renderer friend
Definition at line 60 of file clod_point_renderer.h.
The documentation for this class was generated from the following files:
libs/cgv_gl/clod_point_renderer.h
libs/cgv_gl/clod_point_renderer.cxx