cgv: cgv::utils::statistics Class Reference
cgv::utils::statistics Class Reference
incrementally accumulate statistical information
#include <statistics.h>
Public Member Functions
statistics ()
initialize with no value considered yet
statistics (const double &v)
initialize and consider one value
statistics (const double &v, unsigned int n)
initialize and consider n equal values
void init ()
initialize
void init (const double &v)
initialize and consider one value
void init (const double &v, unsigned int n)
initialize and consider n equal values
void update (const double &v)
consider another value
void update (const double &v, unsigned int n)
consider another value count times
double get_average () const
compute average of the considered values
double get_variance () const
compute variance of the considered values
double get_standard_deviation () const
compute standard deviation of the considered values
double get_sum () const
get the sum of the considered variables
double get_sum_of_squares () const
get the sum of the squares of the considered variables
double get_min () const
get the minimum of the considered variables
double get_max () const
get the maximum of the considered variables
unsigned int get_count () const
get the number of considered variables
Protected Attributes
double min
double max
double sum
double sms
unsigned int cnt
Detailed Description
incrementally accumulate statistical information
Definition at line 12 of file statistics.h.
Constructor & Destructor Documentation
statistics() [1/3]
cgv::utils::statistics::statistics ()
initialize with no value considered yet
incrementally accumulate statistical information
initialize with no value considered yet
Definition at line 11 of file statistics.cxx.
References init().
statistics() [2/3]
cgv::utils::statistics::statistics (const double & v)
initialize and consider one value
Definition at line 16 of file statistics.cxx.
References init().
statistics() [3/3]
cgv::utils::statistics::statistics (const double & v, unsigned int n)
initialize and consider n equal values
Definition at line 18 of file statistics.cxx.
References init().
Member Function Documentation
get_average()
double cgv::utils::statistics::get_average () const
compute average of the considered values
Definition at line 50 of file statistics.cxx.
Referenced by get_variance().
get_count()
unsigned int cgv::utils::statistics::get_count () const
get the number of considered variables
Definition at line 70 of file statistics.cxx.
get_max()
double cgv::utils::statistics::get_max () const
get the maximum of the considered variables
Definition at line 68 of file statistics.cxx.
Referenced by cgv::render::texture::write_to_file().
get_min()
double cgv::utils::statistics::get_min () const
get the minimum of the considered variables
Definition at line 66 of file statistics.cxx.
Referenced by cgv::render::texture::write_to_file().
get_standard_deviation()
double cgv::utils::statistics::get_standard_deviation () const
compute standard deviation of the considered values
Definition at line 58 of file statistics.cxx.
References get_variance().
get_sum()
double cgv::utils::statistics::get_sum () const
get the sum of the considered variables
Definition at line 62 of file statistics.cxx.
get_sum_of_squares()
double cgv::utils::statistics::get_sum_of_squares () const
get the sum of the squares of the considered variables
Definition at line 64 of file statistics.cxx.
get_variance()
double cgv::utils::statistics::get_variance () const
compute variance of the considered values
Definition at line 52 of file statistics.cxx.
References get_average().
Referenced by get_standard_deviation().
init() [1/3]
void cgv::utils::statistics::init ()
initialize
Definition at line 20 of file statistics.cxx.
Referenced by statistics(), statistics(), statistics(), update(), and update().
init() [2/3]
void cgv::utils::statistics::init (const double & v)
initialize and consider one value
Definition at line 22 of file statistics.cxx.
init() [3/3]
void cgv::utils::statistics::init (const double & v, unsigned int n)
initialize and consider n equal values
Definition at line 24 of file statistics.cxx.
update() [1/2]
void cgv::utils::statistics::update (const double & v)
consider another value
Definition at line 26 of file statistics.cxx.
References init().
Referenced by cgv::render::texture::write_to_file().
update() [2/2]
void cgv::utils::statistics::update (const double & v, unsigned int n)
consider another value count times
Definition at line 38 of file statistics.cxx.
References init().
Member Data Documentation
cnt
unsigned int cgv::utils::statistics::cnt protected
Definition at line 49 of file statistics.h.
max
double cgv::utils::statistics::max protected
Definition at line 48 of file statistics.h.
min
double cgv::utils::statistics::min protected
Definition at line 48 of file statistics.h.
sms
double cgv::utils::statistics::sms protected
Definition at line 48 of file statistics.h.
sum
double cgv::utils::statistics::sum protected
Definition at line 48 of file statistics.h.
The documentation for this class was generated from the following files:
cgv/utils/statistics.h
cgv/utils/statistics.cxx