cgv: cgv::math::camera< T > Class Template Reference
cgv::math::camera< T > Class Template Reference
extend distorted pinhole with external calibration
#include <camera.h>
Public Types
enum class distortion_result
possible results of applying distortion model
enum class distortion_inversion_result
possible results of inverting distortion model
Public Member Functions
camera ()
standard constructor
template<typename S >
camera (const camera< S > &cam)
copy constructor
distortion_result apply_distortion_model (const fvec< T, 2 > &xd, fvec< T, 2 > &xu, fmat< T, 2, 2 > *J_ptr=0, T epsilon=distortion_inversion_epsilon< T >()) const
apply distortion model from distorted to undistorted image coordinates used in projection direction and return whether successful
distortion_inversion_result invert_distortion_model (const fvec< T, 2 > &xu, fvec< T, 2 > &xd, bool use_xd_as_initial_guess=false, unsigned *iteration_ptr=0, T epsilon=distortion_inversion_epsilon< T >(), unsigned max_nr_iterations=get_standard_max_nr_iterations(), T slow_down=get_standard_slow_down()) const
invert model for image coordinate inversion
Static Public Member Functions
static T get_standard_slow_down ()
slow down factor [0,1] to decrease step size during inverse Jacobian stepping
static unsigned get_standard_max_nr_iterations ()
default maximum number of iterations used for inversion of distortion models
Public Attributes
fmat< T, 3, 4 > pose
external calibration
Detailed Description
template<typename T>
class cgv::math::camera< T >
extend distorted pinhole with external calibration
Definition at line 530 of file camera.h.
Member Function Documentation
apply_distortion_model()
template<typename T > distortion_result cgv::math::distorted_pinhole< T >::apply_distortion_model (const fvec< T, 2 > & xd, fvec< T, 2 > & xu, fmat< T, 2, 2 > * J_ptr = 0, T epsilon = distortion_inversion_epsilon<T>()) const inline inherited
apply distortion model from distorted to undistorted image coordinates used in projection direction and return whether successful
Failure cases are zero denominator in distortion formula or radius larger than max projection radius.
Definition at line 431 of file camera.h.
Referenced by cgv::math::distorted_pinhole< T >::invert_distortion_model().
invert_distortion_model()
template<typename T > distortion_inversion_result cgv::math::distorted_pinhole< T >::invert_distortion_model (const fvec< T, 2 > & xu, fvec< T, 2 > & xd, bool use_xd_as_initial_guess = false, unsigned * iteration_ptr = 0, T epsilon = distortion_inversion_epsilon<T>(), unsigned max_nr_iterations = get_standard_max_nr_iterations(), T slow_down = get_standard_slow_down()) const inline inherited
invert model for image coordinate inversion
Parameters
xu input ... undistorted image coordinates
xd output ... distorted image coordinates
use_xd_as_initial_guess if true the passed values in xd are used as initial guess, otherwise a pseudo inversion of the distortion model is used as initial guess
iteration_ptr if provided, the passed index is used as iteration counter and indicates after the call how many iterations have been performed
epsilon epsilon used to detect division by zero and convergence
max_nr_iterations maximum number of to be taken iterations
slow_down factor in [0,1] to decrease step estimated by Jacobian inverse
Returns
reason of termination where in all case a best guess for xd is provided
Definition at line 473 of file camera.h.
References cgv::math::distorted_pinhole< T >::apply_distortion_model(), cgv::math::inv(), and cgv::math::fvec< T, N >::sqr_length().
The documentation for this class was generated from the following file:
cgv/math/camera.h