cgv: cgv::audio::OALSource Class Reference
cgv::audio::OALSource Class Reference
This class describes a sound source in the scene.
#include <al_context.h>
Public Member Functions
OALSource (const OALSource &)=delete
OALSource (OALSource &&)=default
OALSource & operator= (const OALSource &)=delete
OALSource & operator= (OALSource &&)=default
bool init (OALContext &ctx, std::string sound_name)
This function links a source to a context.
void set_position (cgv::math::fvec< float, 3 > pos)
Sets the source position.
void set_velocity (cgv::math::fvec< float, 3 > vel)
Sets the source velocity.
void set_pitch (float pitch)
Sets the source pitch.
void set_gain (float gain)
Sets the source gain.
void set_looping (bool should_loop)
Sets the looping property of the source.
cgv::math::fvec< float, 3 > get_position () const
Gets the source position.
cgv::math::fvec< float, 3 > get_velocity () const
Gets the source velocity.
float get_pitch () const
Gets the source pitch.
float get_gain () const
Gets the source gain.
bool is_looping () const
Determines if the source has the looping property.
bool is_playing () const
Determines if the source is playing.
void play ()
Commences the playback of the sound buffer.
void pause ()
Pauses the playback of the sound buffer without moving the playhead.
void play_pause (bool should_play)
Explicitly toggles between pausing and playing the sound buffer.
void stop ()
Stops the playback of the sound buffer and moves the playhead to the beginning.
void rewind ()
Moves the playhead to the beginning of the buffer.
Detailed Description
This class describes a sound source in the scene.
Definition at line 229 of file al_context.h.
Member Function Documentation
get_gain()
float cgv::audio::OALSource::get_gain () const
Gets the source gain.
Returns
The current gain of the source.
Definition at line 278 of file al_context.cpp.
get_pitch()
float cgv::audio::OALSource::get_pitch () const
Gets the source pitch.
Returns
The current pitch of the source.
Definition at line 271 of file al_context.cpp.
get_position()
cgv::math::fvec< float, 3 > cgv::audio::OALSource::get_position () const
Gets the source position.
Returns
The current position of the source.
Definition at line 257 of file al_context.cpp.
References cgv::math::fvec< T, N >::data().
get_velocity()
cgv::math::fvec< float, 3 > cgv::audio::OALSource::get_velocity () const
Gets the source velocity.
Returns
The current velocity of the source.
Definition at line 264 of file al_context.cpp.
References cgv::math::fvec< T, N >::data().
init()
bool cgv::audio::OALSource::init (OALContext & ctx, std::string sound_name)
This function links a source to a context.
Parameters
ctx The OpenAL context
[in] sound_name The sounds symbolic name
Returns
True if initialization was successful, False otherwise.
Warning
An internal reference to the given context is made. You need to make sure, that this object does not outlive the context.
See also
OALContext::load_sample()
OALContext::load_samples()
Definition at line 232 of file al_context.cpp.
References cgv::audio::OALContext::get_buffer_id(), cgv::audio::OALContext::get_native_context(), and cgv::audio::OALContext::is_no_error().
is_looping()
bool cgv::audio::OALSource::is_looping () const
Determines if the source has the looping property.
Returns
True if the source is looping its buffer, False otherwise.
Definition at line 285 of file al_context.cpp.
is_playing()
bool cgv::audio::OALSource::is_playing () const
Determines if the source is playing.
Returns
True if the source is currently playing, False otherwise.
Definition at line 292 of file al_context.cpp.
play_pause()
void cgv::audio::OALSource::play_pause (bool should_play)
Explicitly toggles between pausing and playing the sound buffer.
Parameters
[in] should_play True if the source should play, False if it should be paused.
Remarks
This function is provided as convenience to directly control the source with a boolean argument.
Definition at line 303 of file al_context.cpp.
References pause(), and play().
set_gain()
void cgv::audio::OALSource::set_gain (float gain)
Sets the source gain.
Parameters
[in] gain The new gain of the source
Definition at line 250 of file al_context.cpp.
set_looping()
void cgv::audio::OALSource::set_looping (bool should_loop)
Sets the looping property of the source.
Parameters
[in] should_loop True if the source buffer should be looped, False otherwise.
Definition at line 252 of file al_context.cpp.
set_pitch()
void cgv::audio::OALSource::set_pitch (float pitch)
Sets the source pitch.
Parameters
[in] pitch The new pitch of the source
Definition at line 248 of file al_context.cpp.
set_position()
void cgv::audio::OALSource::set_position (cgv::math::fvec< float, 3 > pos)
Sets the source position.
Parameters
[in] pos The new position of the source
Definition at line 244 of file al_context.cpp.
References cgv::math::fvec< T, N >::data().
set_velocity()
void cgv::audio::OALSource::set_velocity (cgv::math::fvec< float, 3 > vel)
Sets the source velocity.
Parameters
[in] vel The new velocity of the source
Definition at line 246 of file al_context.cpp.
References cgv::math::fvec< T, N >::data().
The documentation for this class was generated from the following files:
libs/cgv_oal/al_context.h
libs/cgv_oal/al_context.cpp