cgv: cgv::data::ascii_reflection_handler Class Reference
cgv::data::ascii_reflection_handler Class Reference abstract
read from ascii file
#include <ascii_io_reflection_handlers.h>
Public Types
enum GroupTraversal
@ basic types with helper functions
enum GroupKind
different support group types
Public Member Functions
int reflect_group_begin (GroupKind group_kind, const std::string &group_name, void *group_ptr, cgv::reflect::abst_reflection_traits *rt, unsigned grp_size)
abstract interface to start reflection of a group of members.
void reflect_group_end (GroupKind group_kind)
abstract interface to terminate reflection of a group of members
bool reflect_method_void (const std::string &method_name, cgv::reflect::method_interface *mi_ptr, cgv::reflect::abst_reflection_traits *return_traits, const std::vector< cgv::reflect::abst_reflection_traits * > &param_value_traits)
abstract interface to reflect a method, where return and parameter types are specified as strings.
interface used by reflect and self_reflect functions
virtual bool is_creative () const
give information on whether reflection_handler creates object (defaults to false)
template<typename T >
bool reflect_member (const std::string &member_name, T &member_ref, bool hard_cast=false)
call this to reflect a member by member name and reference to the member.
template<typename T , unsigned n>
bool reflect_member (const std::string &member_name, T(&member_ref)[n])
reflect a member of constant size array type
template<typename T >
bool reflect_member (const std::string &member_name, std::vector< T > &member_ref)
reflect a member of vector type
template<typename T >
bool reflect_member (const std::string &member_name, T *&member_ref)
reflect a member of pointer type.
template<typename M >
bool reflect_method (const std::string &method_name, M m)
call this to reflect a method by method name and reference to the member.
template<typename B >
bool reflect_base (B &base_ref)
reflect a base class with its members
template<typename T , typename S >
bool reflect_array (const std::string &member_name, T *&member_ref, S &size)
reflect a dynamic array member of vector type
Static Public Member Functions
static std::string group_traversal_name (GroupTraversal gt)
return the group traversals as a string
static const char * group_kind_name (GroupKind gk)
return the group kind as a string
static bool is_array_kind (GroupKind gk)
check whether a group kind is of array or vector kind
Protected Member Functions
internal helper functions
GroupTraversal process_structural_group_begin (GroupKind gk, const std::string &member_name, GroupTraversal gt)
type independent part of the reflect_group method that starts the group traversal
bool group_end (GroupKind gk)
updates the nesting info at the end of group and always returns true
template<typename T , typename RT , typename D >
bool self_reflect_member (const std::string &member_name, T &member_ref, const RT &, const D &, bool hard_cast)
implementation of reflection with internal or external self_reflect function
int reflect_array_begin (GroupKind group_kind, const std::string &group_name, void *group_ptr, abst_reflection_traits *rt, unsigned grp_size)
type independent functionality of array reflection
interface to be implemented by derived reflection handlers
virtual bool reflect_member_void (const std::string &member_name, void *member_ptr, abst_reflection_traits *rt)=0
abstract interface to reflect a member variable, where the member type is specified as a string.
Protected Attributes
management of nesting information
std::vector< nesting_info > nesting_info_stack
stack of nesting_info used during the reflection process
Detailed Description
read from ascii file
Definition at line 28 of file ascii_io_reflection_handlers.h.
Member Enumeration Documentation
GroupTraversal
enum cgv::reflect::reflection_handler::GroupTraversal inherited
@ basic types with helper functions
different values for group traversal strategy
Definition at line 81 of file reflection_handler.h.
Member Function Documentation
is_creative()
bool cgv::reflect::reflection_handler::is_creative () const virtual inherited
give information on whether reflection_handler creates object (defaults to false)
give information on whether reflection_handler creates object
Reimplemented in cgv::data::binary_read_reflection_handler, and cgv::data::ascii_read_reflection_handler.
Definition at line 19 of file reflection_handler.cxx.
reflect_group_begin()
int cgv::data::ascii_reflection_handler::reflect_group_begin (GroupKind group_kind, const std::string & group_name, void * group_ptr, cgv::reflect::abst_reflection_traits * rt, unsigned grp_size) virtual
abstract interface to start reflection of a group of members.
The return value gives information about further traversal of the group:
GT_TERMINATE ... terminate traversal completely
GT_SKIP ... skip traversal of group
GT_COMPLETE ... traverse group completely
index i >= 0 ... traverse only the i-th member of the group. Depending on the group kind, the remaining parameters are given as follows:
GK_BASE_CLASS ... group_name and grp_size are undefined, group_ptr is pointer to instance of base class, rt reflects base class
GK_STRUCTURE ... group_name is instance name, group_ptr is pointer to instance, rt reflects type of structure, grp_size is undefined,
GK_VECTOR ... group_name is vector name, group_ptr is pointer to vector data structure, rt reflects element type, grp_size is size of vector
GK_ARRAY ... group_name is array name, group_ptr is pointer to first array element, rt reflects element type, grp_size is size of array.
GK_POINTER ... group_name is pointer name, group_ptr is pointer to first array element, rt reflects type to which pointer poits, grp_size is undefined.
Reimplemented from cgv::reflect::reflection_handler.
Reimplemented in cgv::data::ascii_write_reflection_handler, and cgv::data::ascii_read_reflection_handler.
Definition at line 78 of file ascii_io_reflection_handlers.cxx.
reflect_group_end()
void cgv::data::ascii_reflection_handler::reflect_group_end (GroupKind group_kind) virtual
abstract interface to terminate reflection of a group of members
This function should only be called if group is traversed completely.
Reimplemented from cgv::reflect::reflection_handler.
Definition at line 84 of file ascii_io_reflection_handlers.cxx.
reflect_member() [1/2]
template<typename T > bool cgv::reflect::reflection_handler::reflect_member (const std::string & member_name, T & member_ref, bool hard_cast = false) inherited
call this to reflect a member by member name and reference to the member.
The member type is deduced from the reference via templates. The method uses reflect_member_impl to dispath types with implementation of a self_reflect method and types without. For polymorphic objects with a polymorphic self_reflect() method the parameter hard_cast steers whether the concrete implementation T::self_reflect() is used or the overloaded function member_ref.self_reflect(). This is important for self reflection of base classes in polymorphic objects where hard_cast is set to true. In most other cases one can use the default argument false.
Definition at line 323 of file reflection_handler.h.
Referenced by cgv::reflect::reflection_handler::reflect_array(), cgv::reflect::reflection_handler::reflect_member(), cgv::render::context_config::self_reflect(), cgv::render::render_config::self_reflect(), and vr_view_interactor::self_reflect().
reflect_member() [2/2]
template<typename T > bool cgv::reflect::reflection_handler::reflect_member (const std::string & member_name, T *& member_ref) inherited
reflect a member of pointer type.
This is only a minimal implementation that allows pointers to memory allocated with new. No reference counting or pointers into memory ranges allocated differently are supported. This will be later on.
Definition at line 443 of file reflection_handler.h.
References cgv::reflect::reflection_handler::group_end(), cgv::reflect::reflection_handler::group_traversal_name(), cgv::reflect::reflection_handler::nesting_info_stack, cgv::reflect::reflection_handler::reflect_group_begin(), and cgv::reflect::reflection_handler::reflect_member().
reflect_member_void()
virtual bool cgv::reflect::reflection_handler::reflect_member_void (const std::string & member_name, void * member_ptr, abst_reflection_traits * rt) protected pure virtual inherited
abstract interface to reflect a member variable, where the member type is specified as a string.
Returns whether to continue the reflection.
Implemented in cgv::data::binary_write_reflection_handler, cgv::data::binary_read_reflection_handler, cgv::data::ascii_write_reflection_handler, cgv::data::ascii_read_reflection_handler, cgv::reflect::find_reflection_handler, and cgv::reflect::debug_reflection_handler.
reflect_method()
template<typename M > bool cgv::reflect::reflection_handler::reflect_method (const std::string & method_name, M m) inherited
call this to reflect a method by method name and reference to the member.
The method type is deduced from the reference via templates. This only works, if you additionally include the header <cgv/reflect/method_interface_impl.h>, where the template code is located. This header is not included automatically, because of its length.
To give names to the parameters, append them to the name enclosed in parenthesis, i.e. "sin(x)" or "dot_prod(p,q)".
Definition at line 333 of file reflection_handler.h.
reflect_method_void()
bool cgv::data::io_reflection_handler::reflect_method_void (const std::string & method_name, cgv::reflect::method_interface * mi_ptr, cgv::reflect::abst_reflection_traits * return_traits, const std::vector< cgv::reflect::abst_reflection_traits * > & param_value_traits) virtual inherited
abstract interface to reflect a method, where return and parameter types are specified as strings.
Returns whether to continue the reflection.
Implements cgv::reflect::reflection_handler.
Definition at line 47 of file io_reflection_handler.cxx.
The documentation for this class was generated from the following files:
cgv/data/ascii_io_reflection_handlers.h
cgv/data/ascii_io_reflection_handlers.cxx