cgv: cgv::base::method_action< X, T1 > Class Template Reference
cgv::base::method_action< X, T1 > Class Template Reference
base class for all method actions that take a single argument of type T1 in their signature
#include <action.h>
Public Member Functions
method_action (T1 _v1, bool _default_result_begin, bool _default_result_end)
construct action from signature and default return values
void set_signature (T1 _v1)
set a new signature with which the methods of the traversed nodes are called
bool call_method (void(X::*mp)(T1), bool default_result)
call a void method given a default return value
bool call_method (bool(X::*mp)(T1), bool default_result)
call a bool method given a default return value
Public Member Functions inherited from cgv::base::base_method_action< X >
base_method_action (bool _default_result_begin, bool _default_result_end)
construct from default return values that are passed on to the base class
void select (base_ptr p)
implement the select method and store pointers of type X* and traverse_policy*
bool implements_action () const
simply return whether the stored pointer of type X* is not 0
traverse_policy * get_policy () const
simply return the stored pointer of type traverse_policy*
Public Member Functions inherited from cgv::base::action
action (bool _default_result_begin, bool _default_result_end)
construct with default return values for the begin and end method
void set_default_results (bool _default_result)
sets the value that is returned, whenever no result is obtained from the traversed methods
void set_default_result_begin (bool _default_result_begin)
sets the value that is returned for on_begin events
void set_default_result_end (bool _default_result_end)
sets the value that is returned for on_end events
virtual bool begin ()
perform the enter part of the action on the current object
virtual bool end ()
perform the leave part of the action on the current object
virtual bool has_begin_only () const
check whether the action has registered a single begin method or both begin and end methods
Protected Attributes
T1 v1
Protected Attributes inherited from cgv::base::base_method_action< X >
traverse_policy * tp
X * x
Protected Attributes inherited from cgv::base::action
bool default_result_begin
bool default_result_end
Detailed Description
template<class X, typename T1>
class cgv::base::method_action< X, T1 >
base class for all method actions that take a single argument of type T1 in their signature
Definition at line 86 of file action.h.
Constructor & Destructor Documentation
method_action()
template<class X , typename T1 > cgv::base::method_action< X, T1 >::method_action (T1 _v1, bool _default_result_begin, bool _default_result_end) inline
construct action from signature and default return values
Definition at line 92 of file action.h.
Member Function Documentation
call_method() [1/2]
template<class X , typename T1 > bool cgv::base::method_action< X, T1 >::call_method (bool(X::*)(T1) mp, bool default_result) inline
call a bool method given a default return value
Definition at line 103 of file action.h.
call_method() [2/2]
template<class X , typename T1 > bool cgv::base::method_action< X, T1 >::call_method (void(X::*)(T1) mp, bool default_result) inline
call a void method given a default return value
Definition at line 97 of file action.h.
Referenced by cgv::base::single_method_action< X, R, T1 >::begin(), cgv::base::matched_method_action< X, R1, R2, T1 >::begin(), and cgv::base::matched_method_action< X, R1, R2, T1 >::end().
set_signature()
template<class X , typename T1 > void cgv::base::method_action< X, T1 >::set_signature (T1 _v1) inline
set a new signature with which the methods of the traversed nodes are called
Definition at line 95 of file action.h.
Member Data Documentation
v1
template<class X , typename T1 > T1 cgv::base::method_action< X, T1 >::v1 protected
Definition at line 89 of file action.h.
The documentation for this class was generated from the following file:
cgv/base/action.h