cgv: cgv::math::fvec< T, N > Class Template Reference
cgv::math::fvec< T, N > Class Template Reference
A vector with zero based index.
#include <fvec.h>
Public Types
enum { dims = N }
compile-time constant indicating the dimensionality of the vector
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef T * pointer
typedef const T * const_pointer
typedef T * iterator
typedef const T * const_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
fvec ()
create an uninitialized vector
fvec (const T &a)
create a vector where all N components are initialized to the constant value a
fvec (const T &x, const T &y)
construct and initialize the first two components to the given values
fvec (const T &x, const T &y, const T &z)
construct and initialize the first three components to the given values
fvec (const T &x, const T &y, const T &z, const T &w)
construct and initialize the first four components to the given values
fvec (cgv::type::uint32_type n, const T *a)
create a vector from an array of size n; if n is less than N the remaining N-n components are set to zero
template<typename S >
fvec (cgv::type::uint32_type n, const S *a)
create a vector from an array of size n of a different type; if n is less than N the remaining N-n components are set to zero
template<typename S >
fvec (const fvec< S, N > &other)
construct by copy from a vector of a different type
template<typename S1 , typename S2 >
fvec (const fvec< S1, N - 1 > &other, S2 s)
construct from a vector of one dimension less plus a scalar
template<typename S >
fvec (const fvec< S, N+1 > &other)
construct from vector of one dimension higher by dropping the highest dimension
fvec (const std::array< T, N > &arr)
construct from std::array of same size
void assign (const std::array< T, N > &arr)
set to the contents of the given std::array with same size
void set (const T &x, const T &y)
set the first two components
void set (const T &x, const T &y, const T &z)
set the first three components
void set (const T &x, const T &y, const T &z, const T &w)
set the first four components
void fill (const T &x)
fill the vector with constant value x
void zeros ()
fill the vector with zeros
void zerosh ()
fill the vector with zeros except for the last component, which will be set to one
void ones ()
fill the vector with ones
fvec< T, N+1 > lift () const
convert to homogeneous version by adding a 1
vec< T > to_vec () const
conversion to vector type
T & x ()
return first component
const T & x () const
return first component
T & y ()
return second component
const T & y () const
return second component
T & z ()
return third component
const T & z () const
return third component
T & w ()
return fourth component
const T & w () const
return fourth component
T & operator[] (int i)
return a reference to the component at specified index i
const T & operator[] (int i) const
return a reference to the component at specified index i
T & operator() (int i)
return a reference to the component at specified index i
const T & operator() (int i) const
return a reference to the component at specified index i
T * data ()
return a pointer to the underlying array serving as component storage
const T * data () const
return a pointer to the underlying array serving as component storage
iterator begin ()
return an iterator to the first component of *this
iterator end ()
return an iterator past the last component of *this
const_iterator begin () const
return an iterator to the first component of *this
const_iterator end () const
return an iterator past the last component of *this
reverse_iterator rbegin ()
return a reverse iterator to the first component of the reversed *this that corresponds to the last component of the non-reversed *this
reverse_iterator rend ()
return a reverse iterator past the last component of the reversed *this that corresponds to the component preceding the first component of the non-reversed *this
const_reverse_iterator rbegin () const
return a reverse iterator to the first component of the reversed *this that corresponds to the last component of the non-reversed *this
const_reverse_iterator rend () const
return a reverse iterator past the last component of the reversed *this that corresponds to the component preceding the first component of the non-reversed *this
fvec< T, N > & operator+= (const T &s)
in place addition of a scalar s
fvec< T, N > & operator-= (const T &s)
in place subtraction by scalar s
fvec< T, N > & operator*= (const T &s)
in place multiplication with s
fvec< T, N > & operator/= (const T &s)
in place division by scalar s
template<typename S >
fvec< T, N > & operator+= (const fvec< S, N > &v)
in place vector addition
template<typename S >
fvec< T, N > & operator-= (const fvec< S, N > &v)
in place vector subtraction
template<typename S >
fvec< T, N > & operator*= (const fvec< S, N > &v)
in place componentwise vector multiplication
template<typename S >
fvec< T, N > & operator/= (const fvec< S, N > &v)
in place componentwise vector division
template<typename S >
fvec< T, N > operator+ (const fvec< S, N > &v) const
vector addition
template<typename S >
fvec< T, N > operator- (const fvec< S, N > &v) const
vector subtraction
template<typename S >
fvec< T, N > operator* (const fvec< S, N > &v) const
componentwise vector multiplication
template<typename S >
fvec< T, N > operator/ (const fvec< S, N > &v) const
componentwise vector division
fvec< T, N > operator+ (const T &s) const
componentwise addition of scalar
fvec< T, N > operator- (const T &s) const
componentwise subtraction of scalar
fvec< T, N > operator* (const T &s) const
multiplication with scalar s
fvec< T, N > operator/ (const T &s) const
divide vector by scalar s
fvec< T, N > operator- () const
negate the vector
template<typename S >
bool operator== (const fvec< S, N > &v) const
test for equality
template<typename S >
bool operator!= (const fvec< S, N > &v) const
test for inequality
T sqr_length () const
square length of vector
T length () const
length of the vector L2-Norm
void sign ()
componentwise sign values
void step (const fvec< T, N > &r)
componentwise sign values
void abs ()
componentwise absolute values
void ceil ()
ceil componentwise
void floor ()
floor componentwise
void round ()
round componentwise
T normalize ()
normalize the vector using the L2-Norm and return the length
T safe_normalize ()
normalize the vector using the L2-Norm and return the length; if length is zero the vector remains unchanged
Static Public Member Functions
static fvec< T, N > zeroh ()
constuct a homogeneous zero-vector (yields same result as calling fvec<T, N-1>(0).lift() but is faster)
static fvec< T, N > from_vec (const vec< T > &)
conversion from vector
static cgv::type::uint32_type size ()
return number of components
Protected Attributes
T v [N]
Detailed Description
template<typename T, cgv::type::uint32_type N>
class cgv::math::fvec< T, N >
A vector with zero based index.
Definition at line 26 of file fvec.h.
Member Typedef Documentation
const_iterator
template<typename T , cgv::type::uint32_type N> typedef const T* cgv::math::fvec< T, N >::const_iterator
Definition at line 51 of file fvec.h.
const_pointer
template<typename T , cgv::type::uint32_type N> typedef const T* cgv::math::fvec< T, N >::const_pointer
Definition at line 47 of file fvec.h.
const_reference
template<typename T , cgv::type::uint32_type N> typedef const T& cgv::math::fvec< T, N >::const_reference
Definition at line 39 of file fvec.h.
const_reverse_iterator
template<typename T , cgv::type::uint32_type N> typedef std::reverse_iterator<const_iterator> cgv::math::fvec< T, N >::const_reverse_iterator
Definition at line 55 of file fvec.h.
difference_type
template<typename T , cgv::type::uint32_type N> typedef std::ptrdiff_t cgv::math::fvec< T, N >::difference_type
Definition at line 43 of file fvec.h.
iterator
template<typename T , cgv::type::uint32_type N> typedef T* cgv::math::fvec< T, N >::iterator
Definition at line 49 of file fvec.h.
pointer
template<typename T , cgv::type::uint32_type N> typedef T* cgv::math::fvec< T, N >::pointer
Definition at line 45 of file fvec.h.
reference
template<typename T , cgv::type::uint32_type N> typedef T& cgv::math::fvec< T, N >::reference
Definition at line 37 of file fvec.h.
reverse_iterator
template<typename T , cgv::type::uint32_type N> typedef std::reverse_iterator<iterator> cgv::math::fvec< T, N >::reverse_iterator
Definition at line 53 of file fvec.h.
size_type
template<typename T , cgv::type::uint32_type N> typedef std::size_t cgv::math::fvec< T, N >::size_type
Definition at line 41 of file fvec.h.
value_type
template<typename T , cgv::type::uint32_type N> typedef T cgv::math::fvec< T, N >::value_type
Definition at line 35 of file fvec.h.
Member Enumeration Documentation
anonymous enum
template<typename T , cgv::type::uint32_type N> anonymous enum
compile-time constant indicating the dimensionality of the vector
Definition at line 57 of file fvec.h.
Constructor & Destructor Documentation
fvec() [1/11]
template<typename T , cgv::type::uint32_type N> cgv::math::fvec< T, N >::fvec () inline
create an uninitialized vector
Definition at line 63 of file fvec.h.
fvec() [2/11]
template<typename T , cgv::type::uint32_type N> cgv::math::fvec< T, N >::fvec (const T & a) inline
create a vector where all N components are initialized to the constant value a
Definition at line 65 of file fvec.h.
fvec() [3/11]
template<typename T , cgv::type::uint32_type N> cgv::math::fvec< T, N >::fvec (const T & x, const T & y) inline
construct and initialize the first two components to the given values
Definition at line 67 of file fvec.h.
References cgv::math::fvec< T, N >::set(), cgv::math::fvec< T, N >::x(), and cgv::math::fvec< T, N >::y().
fvec() [4/11]
template<typename T , cgv::type::uint32_type N> cgv::math::fvec< T, N >::fvec (const T & x, const T & y, const T & z) inline
construct and initialize the first three components to the given values
Definition at line 69 of file fvec.h.
References cgv::math::fvec< T, N >::set(), cgv::math::fvec< T, N >::x(), cgv::math::fvec< T, N >::y(), and cgv::math::fvec< T, N >::z().
fvec() [5/11]
template<typename T , cgv::type::uint32_type N> cgv::math::fvec< T, N >::fvec (const T & x, const T & y, const T & z, const T & w) inline
construct and initialize the first four components to the given values
Definition at line 71 of file fvec.h.
References cgv::math::fvec< T, N >::set(), cgv::math::fvec< T, N >::w(), cgv::math::fvec< T, N >::x(), cgv::math::fvec< T, N >::y(), and cgv::math::fvec< T, N >::z().
fvec() [6/11]
template<typename T , cgv::type::uint32_type N> cgv::math::fvec< T, N >::fvec (cgv::type::uint32_type n, const T * a) inline
create a vector from an array of size n; if n is less than N the remaining N-n components are set to zero
Definition at line 73 of file fvec.h.
fvec() [7/11]
template<typename T , cgv::type::uint32_type N> template<typename S > cgv::math::fvec< T, N >::fvec (cgv::type::uint32_type n, const S * a) inline
create a vector from an array of size n of a different type; if n is less than N the remaining N-n components are set to zero
Definition at line 80 of file fvec.h.
fvec() [8/11]
template<typename T , cgv::type::uint32_type N> template<typename S > cgv::math::fvec< T, N >::fvec (const fvec< S, N > & other) inline
construct by copy from a vector of a different type
Definition at line 87 of file fvec.h.
fvec() [9/11]
template<typename T , cgv::type::uint32_type N> template<typename S1 , typename S2 > cgv::math::fvec< T, N >::fvec (const fvec< S1, N - 1 > & other, S2 s) inline
construct from a vector of one dimension less plus a scalar
Definition at line 90 of file fvec.h.
fvec() [10/11]
template<typename T , cgv::type::uint32_type N> template<typename S > cgv::math::fvec< T, N >::fvec (const fvec< S, N+1 > & other) inline
construct from vector of one dimension higher by dropping the highest dimension
Definition at line 93 of file fvec.h.
fvec() [11/11]
template<typename T , cgv::type::uint32_type N> cgv::math::fvec< T, N >::fvec (const std::array< T, N > & arr) inline
construct from std::array of same size
Definition at line 95 of file fvec.h.
Member Function Documentation
abs()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::abs () inline
componentwise absolute values
Definition at line 262 of file fvec.h.
assign()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::assign (const std::array< T, N > & arr) inline
set to the contents of the given std::array with same size
Definition at line 97 of file fvec.h.
begin() [1/2]
template<typename T , cgv::type::uint32_type N> iterator cgv::math::fvec< T, N >::begin () inline
return an iterator to the first component of *this
Definition at line 159 of file fvec.h.
Referenced by cgv::math::fvec< T, N >::rend(), cgv::math::fvec< T, N >::rend(), and cgv::render::clod_point_renderer::set_points().
begin() [2/2]
template<typename T , cgv::type::uint32_type N> const_iterator cgv::math::fvec< T, N >::begin () const inline
return an iterator to the first component of *this
Definition at line 163 of file fvec.h.
ceil()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::ceil () inline
ceil componentwise
Definition at line 269 of file fvec.h.
data() [1/2]
template<typename T , cgv::type::uint32_type N> T * cgv::math::fvec< T, N >::data () inline
return a pointer to the underlying array serving as component storage
Definition at line 151 of file fvec.h.
Referenced by cgv::render::gl::gl_transparent_renderer::blend_texture_over_viewport(), cgv::audio::OALListener::get_orientation(), cgv::audio::OALListener::get_position(), cgv::audio::OALSource::get_position(), cgv::audio::OALListener::get_velocity(), cgv::audio::OALSource::get_velocity(), vr::get_world_to_eye_transform(), cgv::audio::OALListener::set_position(), cgv::audio::OALSource::set_position(), cgv::audio::OALListener::set_velocity(), and cgv::audio::OALSource::set_velocity().
data() [2/2]
template<typename T , cgv::type::uint32_type N> const T * cgv::math::fvec< T, N >::data () const inline
return a pointer to the underlying array serving as component storage
Definition at line 153 of file fvec.h.
end() [1/2]
template<typename T , cgv::type::uint32_type N> iterator cgv::math::fvec< T, N >::end () inline
return an iterator past the last component of *this
Definition at line 161 of file fvec.h.
Referenced by cgv::math::fvec< T, N >::rbegin(), and cgv::math::fvec< T, N >::rbegin().
end() [2/2]
template<typename T , cgv::type::uint32_type N> const_iterator cgv::math::fvec< T, N >::end () const inline
return an iterator past the last component of *this
Definition at line 165 of file fvec.h.
fill()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::fill (const T & x) inline
fill the vector with constant value x
Definition at line 105 of file fvec.h.
References cgv::math::fvec< T, N >::x().
Referenced by cgv::math::fvec< T, N >::ones(), and cgv::math::fvec< T, N >::zeros().
floor()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::floor () inline
floor componentwise
Definition at line 274 of file fvec.h.
from_vec()
template<typename T , cgv::type::uint32_type N> fvec< T, N > cgv::math::fvec< T, N >::from_vec (const vec< T > & v) static
conversion from vector
Definition at line 697 of file fvec.h.
References cgv::math::vec< T >::dim().
length()
template<typename T , cgv::type::uint32_type N> T cgv::math::fvec< T, N >::length () const inline
length of the vector L2-Norm
Definition at line 248 of file fvec.h.
References cgv::math::fvec< T, N >::sqr_length().
Referenced by cgv::media::mesh::dual_contouring< X, T >::compute_cell_vertex(), cgv::media::mesh::simple_mesh< T >::compute_face_normal(), cgv::math::quaternion< T >::exp(), cgv::render::gl::gl_implicit_surface_drawable_base::extract_mesh(), cgv::math::quaternion< T >::log(), cgv::math::fvec< T, N >::normalize(), cgv::render::view::rotate(), cgv::math::fvec< T, N >::safe_normalize(), cgv::render::view::set_eye_keep_extent(), and cgv::render::view::set_eye_keep_view_angle().
lift()
template<typename T , cgv::type::uint32_type N> fvec< T, N+1 > cgv::math::fvec< T, N >::lift () const inline
convert to homogeneous version by adding a 1
Definition at line 113 of file fvec.h.
normalize()
template<typename T , cgv::type::uint32_type N> T cgv::math::fvec< T, N >::normalize () inline
normalize the vector using the L2-Norm and return the length
Definition at line 284 of file fvec.h.
References cgv::math::fvec< T, N >::length().
Referenced by cgv::render::gl::gl_implicit_surface_drawable_base::compute_face_normal(), cgv::media::mesh::convex_polyhedron< T, TCDim >::compute_face_plane(), cgv::media::mesh::simple_mesh< T >::compute_face_tangents(), cgv::media::mesh::simple_mesh< T >::compute_vertex_normals(), cgv::media::mesh::simple_mesh< T >::dual(), cgv::media::mesh::simple_mesh< T >::gyro(), cgv::media::mesh::simple_mesh< T >::join(), cgv::render::gl::gl_implicit_surface_drawable_base::new_vertex(), cgv::math::quaternion< T >::put_axis(), cgv::render::view::put_coordinate_system(), cgv::gui::vr_calibration::read_calibration(), and cgv::gui::vr_calibration::update_driver_calibration().
ones()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::ones () inline
fill the vector with ones
Definition at line 111 of file fvec.h.
References cgv::math::fvec< T, N >::fill().
operator!=()
template<typename T , cgv::type::uint32_type N> template<typename S > bool cgv::math::fvec< T, N >::operator!= (const fvec< S, N > & v) const inline
test for inequality
Definition at line 231 of file fvec.h.
operator()() [1/2]
template<typename T , cgv::type::uint32_type N> T & cgv::math::fvec< T, N >::operator() (int i) inline
return a reference to the component at specified index i
Definition at line 147 of file fvec.h.
operator()() [2/2]
template<typename T , cgv::type::uint32_type N> const T & cgv::math::fvec< T, N >::operator() (int i) const inline
return a reference to the component at specified index i
Definition at line 149 of file fvec.h.
operator*() [1/2]
template<typename T , cgv::type::uint32_type N> template<typename S > fvec< T, N > cgv::math::fvec< T, N >::operator* (const fvec< S, N > & v) const inline
componentwise vector multiplication
Definition at line 206 of file fvec.h.
operator*() [2/2]
template<typename T , cgv::type::uint32_type N> fvec< T, N > cgv::math::fvec< T, N >::operator* (const T & s) const inline
multiplication with scalar s
Definition at line 215 of file fvec.h.
operator*=() [1/2]
template<typename T , cgv::type::uint32_type N> template<typename S > fvec< T, N > & cgv::math::fvec< T, N >::operator*= (const fvec< S, N > & v) inline
in place componentwise vector multiplication
Definition at line 194 of file fvec.h.
operator*=() [2/2]
template<typename T , cgv::type::uint32_type N> fvec< T, N > & cgv::math::fvec< T, N >::operator*= (const T & s) inline
in place multiplication with s
Definition at line 183 of file fvec.h.
operator+() [1/2]
template<typename T , cgv::type::uint32_type N> template<typename S > fvec< T, N > cgv::math::fvec< T, N >::operator+ (const fvec< S, N > & v) const inline
vector addition
Definition at line 200 of file fvec.h.
operator+() [2/2]
template<typename T , cgv::type::uint32_type N> fvec< T, N > cgv::math::fvec< T, N >::operator+ (const T & s) const inline
componentwise addition of scalar
Definition at line 211 of file fvec.h.
operator+=() [1/2]
template<typename T , cgv::type::uint32_type N> template<typename S > fvec< T, N > & cgv::math::fvec< T, N >::operator+= (const fvec< S, N > & v) inline
in place vector addition
Definition at line 188 of file fvec.h.
operator+=() [2/2]
template<typename T , cgv::type::uint32_type N> fvec< T, N > & cgv::math::fvec< T, N >::operator+= (const T & s) inline
in place addition of a scalar s
Definition at line 179 of file fvec.h.
operator-() [1/3]
template<typename T , cgv::type::uint32_type N> fvec< T, N > cgv::math::fvec< T, N >::operator- () const inline
negate the vector
Definition at line 220 of file fvec.h.
operator-() [2/3]
template<typename T , cgv::type::uint32_type N> template<typename S > fvec< T, N > cgv::math::fvec< T, N >::operator- (const fvec< S, N > & v) const inline
vector subtraction
Definition at line 203 of file fvec.h.
operator-() [3/3]
template<typename T , cgv::type::uint32_type N> fvec< T, N > cgv::math::fvec< T, N >::operator- (const T & s) const inline
componentwise subtraction of scalar
Definition at line 213 of file fvec.h.
operator-=() [1/2]
template<typename T , cgv::type::uint32_type N> template<typename S > fvec< T, N > & cgv::math::fvec< T, N >::operator-= (const fvec< S, N > & v) inline
in place vector subtraction
Definition at line 191 of file fvec.h.
operator-=() [2/2]
template<typename T , cgv::type::uint32_type N> fvec< T, N > & cgv::math::fvec< T, N >::operator-= (const T & s) inline
in place subtraction by scalar s
Definition at line 181 of file fvec.h.
operator/() [1/2]
template<typename T , cgv::type::uint32_type N> template<typename S > fvec< T, N > cgv::math::fvec< T, N >::operator/ (const fvec< S, N > & v) const inline
componentwise vector division
Definition at line 209 of file fvec.h.
operator/() [2/2]
template<typename T , cgv::type::uint32_type N> fvec< T, N > cgv::math::fvec< T, N >::operator/ (const T & s) const inline
divide vector by scalar s
Definition at line 217 of file fvec.h.
operator/=() [1/2]
template<typename T , cgv::type::uint32_type N> template<typename S > fvec< T, N > & cgv::math::fvec< T, N >::operator/= (const fvec< S, N > & v) inline
in place componentwise vector division
Definition at line 197 of file fvec.h.
operator/=() [2/2]
template<typename T , cgv::type::uint32_type N> fvec< T, N > & cgv::math::fvec< T, N >::operator/= (const T & s) inline
in place division by scalar s
Definition at line 185 of file fvec.h.
operator==()
template<typename T , cgv::type::uint32_type N> template<typename S > bool cgv::math::fvec< T, N >::operator== (const fvec< S, N > & v) const inline
test for equality
Definition at line 224 of file fvec.h.
operator[]() [1/2]
template<typename T , cgv::type::uint32_type N> T & cgv::math::fvec< T, N >::operator[] (int i) inline
return a reference to the component at specified index i
Definition at line 143 of file fvec.h.
operator[]() [2/2]
template<typename T , cgv::type::uint32_type N> const T & cgv::math::fvec< T, N >::operator[] (int i) const inline
return a reference to the component at specified index i
Definition at line 145 of file fvec.h.
rbegin() [1/2]
template<typename T , cgv::type::uint32_type N> reverse_iterator cgv::math::fvec< T, N >::rbegin () inline
return a reverse iterator to the first component of the reversed *this that corresponds to the last component of the non-reversed *this
Definition at line 167 of file fvec.h.
References cgv::math::fvec< T, N >::end().
rbegin() [2/2]
template<typename T , cgv::type::uint32_type N> const_reverse_iterator cgv::math::fvec< T, N >::rbegin () const inline
return a reverse iterator to the first component of the reversed *this that corresponds to the last component of the non-reversed *this
Definition at line 171 of file fvec.h.
References cgv::math::fvec< T, N >::end().
rend() [1/2]
template<typename T , cgv::type::uint32_type N> reverse_iterator cgv::math::fvec< T, N >::rend () inline
return a reverse iterator past the last component of the reversed *this that corresponds to the component preceding the first component of the non-reversed *this
Definition at line 169 of file fvec.h.
References cgv::math::fvec< T, N >::begin().
rend() [2/2]
template<typename T , cgv::type::uint32_type N> const_reverse_iterator cgv::math::fvec< T, N >::rend () const inline
return a reverse iterator past the last component of the reversed *this that corresponds to the component preceding the first component of the non-reversed *this
Definition at line 173 of file fvec.h.
References cgv::math::fvec< T, N >::begin().
round()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::round () inline
round componentwise
Definition at line 279 of file fvec.h.
safe_normalize()
template<typename T , cgv::type::uint32_type N> T cgv::math::fvec< T, N >::safe_normalize () inline
normalize the vector using the L2-Norm and return the length; if length is zero the vector remains unchanged
Definition at line 292 of file fvec.h.
References cgv::math::fvec< T, N >::length().
set() [1/3]
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::set (const T & x, const T & y) inline
set the first two components
Definition at line 99 of file fvec.h.
References cgv::math::fvec< T, N >::x(), and cgv::math::fvec< T, N >::y().
Referenced by cgv::math::fvec< T, N >::fvec(), cgv::math::fvec< T, N >::fvec(), cgv::math::fvec< T, N >::fvec(), and cgv::render::performance_monitor::performance_monitor().
set() [2/3]
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::set (const T & x, const T & y, const T & z) inline
set the first three components
Definition at line 101 of file fvec.h.
References cgv::math::fvec< T, N >::x(), cgv::math::fvec< T, N >::y(), and cgv::math::fvec< T, N >::z().
set() [3/3]
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::set (const T & x, const T & y, const T & z, const T & w) inline
set the first four components
Definition at line 103 of file fvec.h.
References cgv::math::fvec< T, N >::w(), cgv::math::fvec< T, N >::x(), cgv::math::fvec< T, N >::y(), and cgv::math::fvec< T, N >::z().
sign()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::sign () inline
componentwise sign values
Definition at line 252 of file fvec.h.
size()
template<typename T , cgv::type::uint32_type N> static cgv::type::uint32_type cgv::math::fvec< T, N >::size () inline static
return number of components
Definition at line 125 of file fvec.h.
Referenced by cgv::render::gl::gl_implicit_surface_drawable_base::compute_face_normal(), cgv::app::overlay::get_local_rectangle(), cgv::app::navigator::handle_mouse_event(), cgv::app::color_map_editor::init_frame(), cgv::render::gl::gl_implicit_surface_drawable_base::new_polygon(), and cgv::plot::plot_base::set_plot_uniforms().
sqr_length()
template<typename T , cgv::type::uint32_type N> T cgv::math::fvec< T, N >::sqr_length () const inline
square length of vector
Definition at line 241 of file fvec.h.
Referenced by cgv::math::distorted_pinhole< T >::invert_distortion_model(), and cgv::math::fvec< T, N >::length().
step()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::step (const fvec< T, N > & r) inline
componentwise sign values
Definition at line 257 of file fvec.h.
to_vec()
template<typename T , cgv::type::uint32_type N> vec< T > cgv::math::fvec< T, N >::to_vec () const
conversion to vector type
Definition at line 689 of file fvec.h.
References cgv::math::vec< T >::set_extern_data().
Referenced by cgv::media::mesh::dual_contouring< X, T >::compute_cell_vertex(), cgv::render::gl::gl_implicit_surface_drawable_base::draw(), cgv::render::gl::gl_implicit_surface_drawable_base::new_vertex(), cgv::media::mesh::dual_contouring< X, T >::process_edge_plane(), and cgv::media::mesh::cuberille< X, T, P >::process_slice().
w() [1/2]
template<typename T , cgv::type::uint32_type N> T & cgv::math::fvec< T, N >::w () inline
return fourth component
Definition at line 139 of file fvec.h.
Referenced by cgv::math::quaternion< T >::affin(), cgv::math::fvec< T, N >::fvec(), cgv::app::gizmo::handle(), cgv::app::navigator::handle_mouse_event(), cgv::math::quaternion< T >::operator*=(), cgv::math::ray< T, 3 >::ray(), and cgv::math::fvec< T, N >::set().
w() [2/2]
template<typename T , cgv::type::uint32_type N> const T & cgv::math::fvec< T, N >::w () const inline
return fourth component
Definition at line 141 of file fvec.h.
x() [1/2]
template<typename T , cgv::type::uint32_type N> T & cgv::math::fvec< T, N >::x () inline
return first component
Definition at line 127 of file fvec.h.
Referenced by cgv::math::quaternion< T >::affin(), cgv::media::mesh::simple_mesh< T >::compute_face_tangents(), cgv::render::managed_frame_buffer::ensure(), cgv::math::fvec< T, N >::fill(), cgv::math::fvec< T, N >::fvec(), cgv::math::fvec< T, N >::fvec(), cgv::math::fvec< T, N >::fvec(), cgv::render::context::get_gamma(), cgv::app::navigator::handle_mouse_event(), cgv::app::color_selector::handle_mouse_event(), cgv::app::color_selector::init_frame(), cgv::math::quaternion< T >::operator*=(), cgv::math::quaternion< T >::put_im(), cgv::math::ray< T, 3 >::ray(), cgv::math::fvec< T, N >::set(), cgv::math::fvec< T, N >::set(), cgv::math::fvec< T, N >::set(), cgv::math::quaternion< T >::set(), cgv::math::quaternion< T >::set_normal(), and cgv::app::overlay::update_layout().
x() [2/2]
template<typename T , cgv::type::uint32_type N> const T & cgv::math::fvec< T, N >::x () const inline
return first component
Definition at line 129 of file fvec.h.
y() [1/2]
template<typename T , cgv::type::uint32_type N> T & cgv::math::fvec< T, N >::y () inline
return second component
Definition at line 131 of file fvec.h.
Referenced by cgv::math::quaternion< T >::affin(), cgv::media::mesh::simple_mesh< T >::compute_face_tangents(), cgv::render::managed_frame_buffer::ensure(), cgv::math::fvec< T, N >::fvec(), cgv::math::fvec< T, N >::fvec(), cgv::math::fvec< T, N >::fvec(), cgv::render::context::get_gamma(), cgv::app::gizmo::handle(), cgv::app::color_map_legend::handle_member_change(), cgv::app::performance_monitor::handle_member_change(), cgv::app::navigator::handle_mouse_event(), cgv::math::quaternion< T >::operator*=(), cgv::math::quaternion< T >::put_im(), cgv::math::ray< T, 3 >::ray(), cgv::math::fvec< T, N >::set(), cgv::math::fvec< T, N >::set(), cgv::math::fvec< T, N >::set(), cgv::math::quaternion< T >::set(), cgv::math::quaternion< T >::set_normal(), and cgv::app::overlay::update_layout().
y() [2/2]
template<typename T , cgv::type::uint32_type N> const T & cgv::math::fvec< T, N >::y () const inline
return second component
Definition at line 133 of file fvec.h.
z() [1/2]
template<typename T , cgv::type::uint32_type N> T & cgv::math::fvec< T, N >::z () inline
return third component
Definition at line 135 of file fvec.h.
Referenced by cgv::math::quaternion< T >::affin(), cgv::media::mesh::simple_mesh< T >::compute_face_tangents(), cgv::math::fvec< T, N >::fvec(), cgv::math::fvec< T, N >::fvec(), cgv::render::context::get_gamma(), cgv::app::gizmo::handle(), cgv::app::navigator::handle_mouse_event(), cgv::math::quaternion< T >::operator*=(), cgv::math::quaternion< T >::put_im(), cgv::math::fvec< T, N >::set(), cgv::math::fvec< T, N >::set(), cgv::math::quaternion< T >::set(), and cgv::math::quaternion< T >::set_normal().
z() [2/2]
template<typename T , cgv::type::uint32_type N> const T & cgv::math::fvec< T, N >::z () const inline
return third component
Definition at line 137 of file fvec.h.
zeroh()
template<typename T , cgv::type::uint32_type N> static fvec< T, N > cgv::math::fvec< T, N >::zeroh () inline static
constuct a homogeneous zero-vector (yields same result as calling fvec<T, N-1>(0).lift() but is faster)
Definition at line 115 of file fvec.h.
zeros()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::zeros () inline
fill the vector with zeros
Definition at line 107 of file fvec.h.
References cgv::math::fvec< T, N >::fill().
Referenced by cgv::media::mesh::convex_polyhedron< T, TCDim >::construct_box(), and cgv::math::fmat< T, N, M >::operator*().
zerosh()
template<typename T , cgv::type::uint32_type N> void cgv::math::fvec< T, N >::zerosh () inline
fill the vector with zeros except for the last component, which will be set to one
Definition at line 109 of file fvec.h.
Member Data Documentation
v
template<typename T , cgv::type::uint32_type N> T cgv::math::fvec< T, N >::v[N] protected
Definition at line 29 of file fvec.h.
The documentation for this class was generated from the following file:
cgv/math/fvec.h