cgv: gui_config_file_observer Class Reference
gui_config_file_observer Class Reference
Public Member Functions
gui_config_file_observer (const std::string &fn, const std::string &c)
void add_view (const config_file_view &cfv)
void inc_out_of_date_count ()
void update_view (cgv::gui::view_ptr v)
void update_config_file ()
void multi_observe (base_ptr bp, const std::string &property_assignments, size_t off)
to be implemented method that adds permanent registration for a list of property assignments
Protected Attributes
std::string file_name
std::string content
std::vector< config_file_view > views
unsigned nr_out_of_date
Detailed Description
Definition at line 24 of file config_file.cxx.
Constructor & Destructor Documentation
gui_config_file_observer()
gui_config_file_observer::gui_config_file_observer (const std::string & fn, const std::string & c) inline
Definition at line 32 of file config_file.cxx.
Member Function Documentation
add_view()
void gui_config_file_observer::add_view (const config_file_view & cfv) inline
Definition at line 36 of file config_file.cxx.
inc_out_of_date_count()
void gui_config_file_observer::inc_out_of_date_count () inline
Definition at line 41 of file config_file.cxx.
multi_observe()
void gui_config_file_observer::multi_observe (base_ptr bp, const std::string & property_assignments, size_t off) virtual
to be implemented method that adds permanent registration for a list of property assignments
Implements cgv::base::config_file_observer.
Definition at line 154 of file config_file.cxx.
References cgv::utils::bite_all(), cgv::utils::is_digit(), cgv::utils::is_integer(), cgv::base::base::self_reflect(), cgv::base::base::set_void(), cgv::type::info::TI_BOOL, cgv::type::info::TI_FLT32, cgv::type::info::TI_FLT64, cgv::type::info::TI_INT16, cgv::type::info::TI_INT32, cgv::type::info::TI_INT64, cgv::type::info::TI_INT8, cgv::type::info::TI_STRING, cgv::type::info::TI_UINT16, cgv::type::info::TI_UINT32, cgv::type::info::TI_UINT64, cgv::type::info::TI_UINT8, and cgv::utils::to_string().
update_config_file()
void gui_config_file_observer::update_config_file () inline
Definition at line 55 of file config_file.cxx.
update_view()
void gui_config_file_observer::update_view (cgv::gui::view_ptr v) inline
Definition at line 45 of file config_file.cxx.
Member Data Documentation
content
std::string gui_config_file_observer::content protected
Definition at line 28 of file config_file.cxx.
file_name
std::string gui_config_file_observer::file_name protected
Definition at line 27 of file config_file.cxx.
nr_out_of_date
unsigned gui_config_file_observer::nr_out_of_date protected
Definition at line 30 of file config_file.cxx.
views
std::vector<config_file_view> gui_config_file_observer::views protected
Definition at line 29 of file config_file.cxx.
The documentation for this class was generated from the following file:
cgv/gui/config_file.cxx