cgv: cgv::media::video::abst_video_writer Class Reference
cgv::media::video::abst_video_writer Class Reference abstract
abstract interface for video writers
#include <video_writer.h>
Public Member Functions
virtual abst_video_writer * clone () const =0
construct a copy of the video writer
virtual const char * get_supported_extensions () const =0
return a string containing a colon separated list of extensions that can be read with this video writer
virtual const std::string & get_last_error () const =0
return a reference to the last error message
virtual bool scan_codecs (std::vector< std::string > &codec_names) const
dummy implementation provided that does nothing and returns false
virtual bool set_codec (const std::string &codec_name)
dummy empty implementation provided that does nothing and returns false
virtual std::string get_codec () const
return the currently selected codec, default implementation returns empty string
virtual bool open (const std::string &file_name, const cgv::data::data_format &image_format, float fps, bool interactive)=0
open file from given file name, format and fps
virtual bool write_frame (const cgv::data::const_data_view &image_data)=0
write the next frame
virtual bool close ()=0
close the video file
Public Member Functions inherited from cgv::base::base
virtual std::string get_type_name () const
overload to return the type name of this object. By default the type interface is queried over get_type.
virtual std::string get_default_options () const
overload to provide default options for registration
std::string get_name_or_type_name () const
determine name of instance by checking cgv::base::named interface and in failure fallback to get_type_name()
virtual void on_register ()
overload to handle register events that is sent after the instance has been registered
virtual void unregister ()
overload to handle unregistration of instances
virtual bool on_exit_request ()
overload to handle the appication exit request, return true if exiting is allowed and false otherwise
virtual void stream_stats (std::ostream &)
overload to show the content of this object
virtual data::ref_ptr< named, true > get_named ()
perform downcast to named
virtual data::ref_ptr< node, true > get_node ()
perform downcast to node
virtual data::ref_ptr< group, true > get_group ()
perform downcast to group
virtual data::ref_ptr< const named, true > get_named_const () const
perform downcast to const named
virtual data::ref_ptr< const node, true > get_node_const () const
perform downcast to const node
virtual data::ref_ptr< const group, true > get_group_const () const
perform downcast to const group
template<class T >
data::ref_ptr< T, true > cast ()
cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
data::ref_ptr< const T, true > cast_const ()
const cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
T * get_interface ()
use dynamic type cast to check for the given interface
template<class T >
const T * get_const_interface () const
use dynamic type cast to check for the given interface
virtual void update ()
this virtual update allows for example to ask a view to update the viewed value. The default implementation is empty.
virtual void * get_user_data () const
this virtual method allows to pass application specific data for internal purposes
virtual bool self_reflect (cgv::reflect::reflection_handler &)
used for simple self reflection
virtual std::string get_property_declarations ()
return a semicolon separated list of property declarations
virtual bool set_void (const std::string &property, const std::string &value_type, const void *value_ptr)
abstract interface for the setter of a dynamic property.
virtual void on_set (void *member_ptr)
this callback is called when the set_void method has changed a member and can be overloaded in derived class
virtual bool get_void (const std::string &property, const std::string &value_type, void *value_ptr)
abstract interface for the getter of a dynamic property.
virtual bool call_void (const std::string &method, const std::vector< std::string > &param_value_types, const std::vector< const void * > &param_value_ptrs, const std::string &result_type="", void *result_value_ptr=0)
abstract interface to call an action
void set (const std::string &property, const char *value)
specialization of set method to support const char* as strings
template<typename T >
void set (const std::string &property, const T &value)
set a property of the element to the given value and perform standard conversions if necessary.
template<typename T >
T get (const std::string &property)
query a property of the element and perform standard conversions if necessary.
void multi_set (const std::string &property_assignments, bool report_error=true)
set several properties
bool is_property (const std::string &property_name, std::string *type_name=0)
check if the given name specifies a property.
void * find_member_ptr (const std::string &property_name, std::string *type_name=0)
find a member pointer by name.
Public Member Functions inherited from cgv::data::ref_counted
int get_ref_count () const
read access to current count
Friends
class video_writer
Additional Inherited Members
Protected Member Functions inherited from cgv::base::base
virtual ~base ()
make destructor virtual and not accessible from outside
Protected Member Functions inherited from cgv::data::ref_counted
ref_counted ()
constructor initializes the count to 0
void set_ref_count (int c) const
write access is also const to allow ref counted pointers to const instances
Static Protected Member Functions inherited from cgv::base::base
template<class T >
static data::ref_ptr< T, true > cast_dynamic (base *b)
use dynamic cast for upcast to given class
Detailed Description
abstract interface for video writers
Definition at line 15 of file video_writer.h.
Member Function Documentation
get_codec()
std::string cgv::media::video::abst_video_writer::get_codec () const virtual
return the currently selected codec, default implementation returns empty string
Definition at line 28 of file video_writer.cxx.
Referenced by cgv::media::video::video_writer::get_codec().
scan_codecs()
bool cgv::media::video::abst_video_writer::scan_codecs (std::vector< std::string > & codec_names) const virtual
dummy implementation provided that does nothing and returns false
Definition at line 16 of file video_writer.cxx.
Referenced by cgv::media::video::video_writer::scan_codecs().
set_codec()
bool cgv::media::video::abst_video_writer::set_codec (const std::string & codec_name) virtual
dummy empty implementation provided that does nothing and returns false
dummy empty implementation provided that does nothing
Definition at line 22 of file video_writer.cxx.
Referenced by cgv::media::video::video_writer::set_codec().
Friends And Related Symbol Documentation
video_writer
friend class video_writer friend
Definition at line 18 of file video_writer.h.
The documentation for this class was generated from the following files:
cgv/media/video/video_writer.h
cgv/media/video/video_writer.cxx