cgv: cgv::render::box_wire_renderer Class Reference
cgv::render::box_wire_renderer Class Reference
renderer that supports point splatting
#include <box_wire_renderer.h>
Public Member Functions
void enable_attribute_array_manager (const context &ctx, attribute_array_manager &aam)
call this before setting attribute arrays to manage attribute array in given manager
void disable_attribute_array_manager (const context &ctx, attribute_array_manager &aam)
call this after last render/draw call to ensure that no other users of renderer change attribute arrays of given manager
void set_position_is_center (bool _position_is_center)
set the flag, whether the position is interpreted as the box center
bool enable (context &ctx)
enable box wire renderer
template<typename T >
void set_extent (const context &ctx, const T &extent)
specify a single extent for all boxes
template<typename T >
void set_extent_array (const context &ctx, const std::vector< T > &extents)
extent array specifies box extends in case of position_is_center=true, otherwise the maximum point of each box
template<typename T >
void set_extent_array (const context &ctx, const T *extents, size_t nr_elements, unsigned stride_in_bytes=0)
extent array specifies box extends in case of position_is_center=true, otherwise the maximum point of each box
template<typename T >
void set_box (const context &ctx, const cgv::media::axis_aligned_box< T, 3 > &box)
specify a single box. This sets position_is_center to false as well as position and extent attributes
template<typename T >
void set_box_array (const context &ctx, const std::vector< cgv::media::axis_aligned_box< T, 3 > > &boxes)
specify box array directly. This sets position_is_center to false as well as position and extent array
template<typename T >
void set_box_array (const context &ctx, const cgv::media::axis_aligned_box< T, 3 > *boxes, size_t count)
specify box array directly. This sets position_is_center to false as well as position and extent array
template<typename T >
void set_translation_array (const context &ctx, const std::vector< T > &translations)
template method to set the translations from a vector of vectors of type T, which should have 3 components
template<typename T >
void set_translation_array (const context &ctx, const T *translations, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the translations from a vector of vectors of type T, which should have 3 components
template<typename T >
void set_rotation_array (const context &ctx, const std::vector< T > &rotations)
template method to set the rotation from a vector of quaternions of type T, which should have 4 components
template<typename T >
void set_rotation_array (const context &ctx, const T *rotations, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the rotation from a vector of quaternions of type T, which should have 4 components
bool disable (context &ctx)
disable renderer
void draw (context &ctx, size_t start, size_t count, bool use_strips=false, bool use_adjacency=false, uint32_t strip_restart_index=-1)
Draw a range of vertices or indexed elements.
bool init (context &ctx)
call init() once before using renderer
template<typename T >
void set_normal (const context &ctx, const cgv::math::fvec< T, 3 > &normal)
specify a single normal for all lines
template<typename T >
void set_normal_array (const context &ctx, const std::vector< T > &normals)
templated method to set the normal attribute from a vector of normals of type T, which should have 3 components
template<typename T >
void set_normal_array (const context &ctx, const T *normals, size_t nr_elements, unsigned stride_in_bytes=0)
templated method to set the normal attribute from an array of normals of type T, which should have 3 components
template<typename T >
void set_line_width (const context &ctx, const T &line_width)
specify a single line_width for all lines
template<typename T >
void set_line_width_array (const context &ctx, const std::vector< T > &line_widths)
line_width array specifies box extends in case of position_is_center=true, otherwise the maximum point of each box
template<typename T >
void set_line_width_array (const context &ctx, const T *line_widths, size_t nr_elements, unsigned stride_in_bytes=0)
line_width array specifies box extends in case of position_is_center=true, otherwise the maximum point of each box
template<typename T >
void set_depth_offset (const context &ctx, const T &depth_offset)
specify a single depth_offset for all lines
template<typename T >
void set_depth_offset_array (const context &ctx, const std::vector< T > &depth_offsets)
depth_offset array specifies box extends in case of position_is_center=true, otherwise the maximum point of each box
template<typename T >
void set_depth_offset_array (const context &ctx, const T *depth_offsets, size_t nr_elements, unsigned stride_in_bytes=0)
depth_offset array specifies box extends in case of position_is_center=true, otherwise the maximum point of each box
bool validate_attributes (const context &ctx) const
check additionally the group attributes
void set_group_index_array (const context &ctx, const std::vector< unsigned > &group_indices)
method to set the group index attribute
void set_group_index_array (const context &ctx, const unsigned *group_indices, size_t nr_elements)
method to set the group index attribute
void set_group_index_array (const context &ctx, type_descriptor element_type, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
method to set the group index attribute from a vertex buffer object, the element type must be given as explicit template parameter
template<typename T >
void set_group_index_array (const context &ctx, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the group index color attribute from a vertex buffer object, the element type must be given as explicit template parameter
template<typename T >
void set_group_colors (const context &ctx, const std::vector< T > &colors)
template method to set the group colors from a vector of colors of type T
template<typename T >
void set_group_colors (const context &ctx, const T *colors, size_t nr_elements)
template method to set the group colors from a vector of colors of type T
template<typename T >
void set_group_translations (const context &ctx, const std::vector< T > &group_translations)
template method to set the group translations from a vector of vectors of type T, which should have 3 components
template<typename T >
void set_group_translations (const context &ctx, const T *group_translations, size_t nr_elements)
template method to set the group translations from a vector of vectors of type T, which should have 3 components
template<typename T >
void set_group_rotations (const context &ctx, const std::vector< T > &group_rotations)
template method to set the group rotation from a vector of quaternions of type T, which should have 4 components
template<typename T >
void set_group_rotations (const context &ctx, const T *group_rotations, size_t nr_elements)
template method to set the group rotation from a vector of quaternions of type T, which should have 4 components
shader_define_map & ref_defines ()
access to shader define map to update defines not handled by render style
shader_program & ref_prog ()
derived renderer classes have access to shader program
void set_prog (shader_program &one_shot_prog)
set external shader program up to next call to disable() or render()
void draw_impl (context &ctx, PrimitiveType pt, size_t start, size_t count, bool use_strips=false, bool use_adjacency=false, uint32_t strip_restart_index=-1)
default implementation of draw method with support for indexed rendering and different primitive types
void draw_impl_instanced (context &ctx, PrimitiveType type, size_t start, size_t count, size_t instance_count, bool use_strips=false, bool use_adjacency=false, uint32_t strip_restart_index=-1)
default implementation of instanced draw method with support for indexed rendering and different primitive types
void manage_singleton (context &ctx, const std::string &renderer_name, int &ref_count, int ref_count_change)
used by derived classes to manage singletons
virtual void set_attribute_array_manager (const context &ctx, attribute_array_manager *_aam_ptr=0)
this function is deprecated, please use enable_attribute_array_manager() and disable_attribute_manager() instead
void set_render_style (const render_style &rs)
reference given render style
bool build_program (context &ctx, shader_program &prog, const render_style &rs)
build shader program for specific render style
template<typename T >
void set_position (const context &ctx, const T &position)
templated method to set the position attribute from a single position of type T
template<typename T >
void set_position_array (const context &ctx, const std::vector< T > &positions)
templated method to set the position attribute from a vector of positions of type T
template<typename T >
void set_position_array (const context &ctx, const T *positions, size_t nr_elements, unsigned stride_in_bytes=0)
templated method to set the position attribute from a vector of positions of type T
void set_position_array (const context &ctx, type_descriptor element_type, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes)
method to set the position attribute from a vertex buffer object
template<typename T >
void set_position_array (const context &ctx, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the position attribute from a vertex buffer object, the element type must be given as explicit template parameter
template<typename T >
void set_color (const context &ctx, const T &color)
templated method to set the color attribute from a single color of type T
template<typename T >
void set_color_array (const context &ctx, const std::vector< T > &colors)
template method to set the color attribute from a vector of colors of type T
template<typename T >
void set_color_array (const context &ctx, const T *colors, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the color attribute from a vector of colors of type T
void set_color_array (const context &ctx, type_descriptor element_type, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
method to set the color attribute from a vertex buffer object, the element type must be given as explicit template parameter
template<typename T >
void set_color_array (const context &ctx, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the color attribute from a vertex buffer object, the element type must be given as explicit template parameter
template<typename T >
bool set_indices (const context &ctx, const std::vector< T > &indices, bool keep_on_cpu=false)
Set the indices for indexed rendering from a vector.
template<typename T >
bool set_indices (const context &ctx, const T *indices, size_t nr_indices, bool keep_on_cpu=false)
Set the indices for indexed rendering from an array given as a pointer.
template<typename T >
bool set_indices (const context &ctx, const vertex_buffer &vbo, size_t count)
Set the indices for indexed rendering from a GPU buffer.
bool has_indices () const
return whether indices have been defined
void remove_indices (const context &ctx)
remove previously set indices
const vertex_buffer * get_vertex_buffer_ptr (const context &ctx, const attribute_array_manager &aam, const std::string &attr_name)
const vertex_buffer * get_index_buffer_ptr (const attribute_array_manager &aam)
bool validate_and_enable (context &ctx)
validate attributes and if successful, enable renderer
virtual bool render (context &ctx, size_t start, size_t count, bool use_strips=false, bool use_adjacency=false, uint32_t strip_restart_index=-1)
Convenience function that draws vertex or indexed element with this renderer.
virtual void clear (const context &ctx)
the clear function destructs the shader program
Protected Member Functions
render_style * create_render_style () const
overload to allow instantiation of box_wire_renderer
bool build_shader_program (context &ctx, shader_program &prog, const shader_define_map &defines)
build box wire program
bool has_aam () const
check for attribute array manager
bool has_attribute (const context &ctx, const std::string &name)
check for attribute
const render_style * get_style_ptr () const
access to render style
bool attributes_persist () const
return whether attributes persist after a call to disable
virtual void update_defines (shader_define_map &defines)
overload to update the shader defines based on the current render style; only called if internal shader program is used
template<typename T >
const T & get_style () const
access to style
template<typename C , typename T >
bool set_composed_attribute_array (const context &ctx, const std::string &name, const C *array_ptr, size_t nr_elements, const T &elem)
in case that several attributes are stored interleaved, call this function for the first and ref_composed_attribute_array() for all others
template<typename C , typename T >
bool ref_composed_attribute_array (const context &ctx, const std::string &name, const std::string &name_ref, const C *array_ptr, size_t nr_elements, const T &elem)
in case that several attributes are stored interleaved, call set_composed_attribute_array() for the first and this function for all others
Protected Attributes
bool has_translations
whether array with per box translations has been specified
bool has_rotations
whether array with per box rotations has been specified
bool position_is_center
whether position is box center, if not it is lower left bottom corner
bool has_colors
track whether color attribute is defined
bool has_positions
track whether position attribute is defined
Detailed Description
renderer that supports point splatting
Definition at line 29 of file box_wire_renderer.h.
Member Function Documentation
draw()
void cgv::render::box_wire_renderer::draw (context & ctx, size_t start, size_t count, bool use_strips = false, bool use_adjacency = false, uint32_t strip_restart_index = -1) virtual
Draw a range of vertices or indexed elements.
Call this function only successful enabeling via validate_and_enable() or enable(). Capsulates glDrawArrays and glDrawElements calls. Overloaded implementations of specific renderers choose the to be used gl primitive type and whether to use an instanced draw call.
See also
render()
Parameters
count number of to be drawn vertices/elements
start index of first to be drawn vertex/element
use_strips whether to generate primitives in strips (only for line or triangle primitives)
use_adjacency whether to specify adjacency information (only for line or triangle primitives)
strip_restart_index extraorindary index used to mark end of strips (only for strip based drawing) Strip based drawing can be combined with the use of adjacency information. Default implementation uses triangle primitives.
Reimplemented from cgv::render::renderer.
Definition at line 92 of file box_wire_renderer.cxx.
References cgv::render::renderer::draw_impl().
get_index_buffer_ptr()
const vertex_buffer* cgv::render::renderer::get_index_buffer_ptr (const attribute_array_manager & aam) inline inherited
Returns a pointer to the vertex buffer of type element buffer holding the indices for indexed rendering as managed by the attribute array manager. Returns nullptr if the buffer or attribute array manager does not exist. Take caution when manipulating the buffer.
Definition at line 281 of file renderer.h.
References cgv::render::attribute_array_manager::get_buffer_ptr().
get_vertex_buffer_ptr()
const vertex_buffer* cgv::render::renderer::get_vertex_buffer_ptr (const context & ctx, const attribute_array_manager & aam, const std::string & attr_name) inline inherited
Returns a pointer to the vertex buffer of the given attribute name as managed by the attribute array manager. Returns nullptr if the buffer or attribute array manager does not exist. Take caution when manipulating the buffer.
Definition at line 275 of file renderer.h.
References cgv::render::attribute_array_manager::get_buffer_ptr().
init()
bool cgv::render::line_renderer::init (context & ctx) virtual inherited
call init() once before using renderer
creates default render style and builds shader program based on defines that can be configured with ref_defines() before calling init(). Reconfiguring defines after init() causes rebuild of shader program in enable() function.
Reimplemented from cgv::render::renderer.
Definition at line 68 of file line_renderer.cxx.
References cgv::render::renderer::init(), cgv::render::renderer::ref_prog(), and cgv::render::shader_program::set_attribute().
render()
bool cgv::render::renderer::render (context & ctx, size_t start, size_t count, bool use_strips = false, bool use_adjacency = false, uint32_t strip_restart_index = -1) virtual inherited
Convenience function that draws vertex or indexed element with this renderer.
This function effectively calls validate_and_enable(), draw() and disable(), passes its parameters to draw and returns the result of validate_and_enable(). draw() and disable() are only executed if validate_and_enable() succeeds. For performance reasons this function should not be used for several successive draw calls due to the unnecessary enabling and disabling between render calls. Typically, this function does not need to be overloaded by specific renderers.
See also
draw()
validate_and_enable()
Definition at line 322 of file renderer.cxx.
Referenced by cgv::render::gl::gl_implicit_surface_drawable_base::draw_implicit_surface().
set_group_index_array()
void cgv::render::group_renderer::set_group_index_array (const context & ctx, type_descriptor element_type, const vertex_buffer & vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes = 0) inherited
method to set the group index attribute from a vertex buffer object, the element type must be given as explicit template parameter
template method to set the group index attribute from a vertex buffer object, the element type must be given as explicit template parameter
Definition at line 48 of file group_renderer.cxx.
set_indices() [1/3]
template<typename T > bool cgv::render::renderer::set_indices (const context & ctx, const std::vector< T > & indices, bool keep_on_cpu = false) inline inherited
Set the indices for indexed rendering from a vector.
If an attribute array manager is enabled and keep_on_cpu is false (default), create GPU index buffer and transfer indices into it.
Template Parameters
T index type must be uint8_t, uint16_t, or uint32_t
Parameters
ctx opengl context in which indexed rendering takes place
indices vector of indices
keep_on_cpu flag whether indices should be kept in CPU memory
Returns
this can only fail if indices cannot be copied to GPU buffer
Definition at line 213 of file renderer.h.
Referenced by cgv::render::render_data_base< ColorType >::transfer().
set_indices() [2/3]
template<typename T > bool cgv::render::renderer::set_indices (const context & ctx, const T * indices, size_t nr_indices, bool keep_on_cpu = false) inline inherited
Set the indices for indexed rendering from an array given as a pointer.
If an attribute array manager is enabled and keep_on_cpu is false (default), create GPU index buffer and transfer indices into it.
Template Parameters
T index type must be uint8_t, uint16_t, or uint32_t
Parameters
ctx opengl context in which indexed rendering takes place
indices pointer to array containing the indices
nr_indices number of indices in the array
keep_on_cpu flag whether indices should be kept in CPU memory
Returns
this can only fail if indices cannot be copied to GPU buffer
Definition at line 234 of file renderer.h.
set_indices() [3/3]
template<typename T > bool cgv::render::renderer::set_indices (const context & ctx, const vertex_buffer & vbo, size_t count) inline inherited
Set the indices for indexed rendering from a GPU buffer.
If an attribute array manager is enabled its index buffer is removed through this call.
Template Parameters
T index type must be uint8_t, uint16_t, or uint32_t
Parameters
ctx opengl context in which indexed rendering takes place
vbo GPU buffer
count number of indices in the GPU buffer
Returns
in current implementation this succeeds always
Definition at line 255 of file renderer.h.
set_prog()
void cgv::render::renderer::set_prog (shader_program & one_shot_prog) inherited
set external shader program up to next call to disable() or render()
set external shader program for successive draw call only
Definition at line 148 of file renderer.cxx.
The documentation for this class was generated from the following files:
libs/cgv_gl/box_wire_renderer.h
libs/cgv_gl/box_wire_renderer.cxx