cgv: cgv::gui::vr_calibration Class Reference
cgv::gui::vr_calibration Class Reference
vr key events use the key codes defined in vr::VRKeys
#include <vr_calib.h>
Public Member Functions
void update_calibration_info ()
iterate vr drivers and copy calibration information into map
bool read_calibration (const std::string &file_path, bool update_drivers=true)
read calibration from calibration file
bool write_calibration (const std::string &file_path) const
write calibration to calibration file
bool update_driver_calibration (vr::vr_driver *dp) const
update the calibration of a driver from the stored calibration states
Public Member Functions inherited from vr::vr_calibration_base
vr_calibration_base ()
nothing to be done in contructor
Protected Member Functions
bool update_driver_calibration (vr::vr_driver *dp, const std::map< std::string, vr::vr_trackable_state > &target_reference_states) const
update the calibration of a driver from the given target reference states
vr_calibration ()
constructor is protected to forbid construction of more than one singleton
Protected Member Functions inherited from vr::vr_calibration_base
void set_driver_calibration_matrix (vr_driver *driver, const float calibration_matrix[12]) const
single point of write access to calibration transformation of vr drivers
Protected Attributes
std::map< std::string, std::map< std::string, vr::vr_trackable_state > > calibration_info
Friends
CGV_API vr_calibration & ref_vr_calibration ()
allow ref_vr_calibration() function to construct one instance
Detailed Description
vr key events use the key codes defined in vr::VRKeys
Definition at line 17 of file vr_calib.h.
Constructor & Destructor Documentation
vr_calibration()
cgv::gui::vr_calibration::vr_calibration () protected
constructor is protected to forbid construction of more than one singleton
Definition at line 117 of file vr_calib.cxx.
Member Function Documentation
read_calibration()
bool cgv::gui::vr_calibration::read_calibration (const std::string & file_path, bool update_drivers = true)
read calibration from calibration file
Definition at line 120 of file vr_calib.cxx.
References vr::get_vr_drivers(), cgv::math::fvec< T, N >::normalize(), cgv::math::quaternion< T >::put_matrix(), cgv::utils::split_to_lines(), and update_driver_calibration().
update_calibration_info()
void cgv::gui::vr_calibration::update_calibration_info ()
iterate vr drivers and copy calibration information into map
Definition at line 16 of file vr_calib.cxx.
References vr::get_vr_drivers().
update_driver_calibration() [1/2]
bool cgv::gui::vr_calibration::update_driver_calibration (vr::vr_driver * dp) const
update the calibration of a driver from the stored calibration states
update the calibration of a driver from the given target reference states
Definition at line 109 of file vr_calib.cxx.
References vr::vr_driver::get_driver_name(), and update_driver_calibration().
update_driver_calibration() [2/2]
bool cgv::gui::vr_calibration::update_driver_calibration (vr::vr_driver * dp, const std::map< std::string, vr::vr_trackable_state > & target_reference_states) const protected
update the calibration of a driver from the given target reference states
Definition at line 31 of file vr_calib.cxx.
References vr::vr_driver::enable_calibration_transformation(), vr::vr_driver::get_driver_name(), vr::vr_driver::get_tracking_reference_states(), vr::get_vr_kit(), cgv::math::fvec< T, N >::normalize(), vr::vr_driver::put_calibration_transformation(), vr::vr_kit::query_state(), vr::vr_driver::scan_vr_kits(), vr::vr_calibration_base::set_driver_calibration_matrix(), and vr::VRS_TRACKED.
Referenced by read_calibration(), and update_driver_calibration().
write_calibration()
bool cgv::gui::vr_calibration::write_calibration (const std::string & file_path) const
write calibration to calibration file
Definition at line 179 of file vr_calib.cxx.
Friends And Related Symbol Documentation
ref_vr_calibration
CGV_API vr_calibration & ref_vr_calibration () friend
allow ref_vr_calibration() function to construct one instance
Definition at line 11 of file vr_calib.cxx.
Member Data Documentation
calibration_info
std::map<std::string, std::map<std::string, vr::vr_trackable_state> > cgv::gui::vr_calibration::calibration_info protected
Definition at line 20 of file vr_calib.h.
The documentation for this class was generated from the following files:
libs/cg_vr/vr_calib.h
libs/cg_vr/vr_calib.cxx