cgv: cgv::data::ascii_read_reflection_handler Class Reference
cgv::data::ascii_read_reflection_handler Class Reference
read from ascii file
#include <ascii_io_reflection_handlers.h>
Public Member Functions
ascii_read_reflection_handler (const std::string &file_name, const std::string &_content, unsigned _ver, NamingConvention _nc=NC_SHORT, unsigned _tab=3)
ascii_read_reflection_handler (std::istream &_is, const std::string &_content, unsigned _ver, NamingConvention _nc=NC_SHORT, unsigned _tab=3)
bool is_creative () const
this should return true
void close ()
int reflect_group_begin (GroupKind group_kind, const std::string &group_name, void *group_ptr, cgv::reflect::abst_reflection_traits *rt, unsigned grp_size)
abstract interface to start reflection of a group of members.
bool reflect_member_void (const std::string &member_name, void *member_ptr, cgv::reflect::abst_reflection_traits *rt)
abstract interface to reflect a member variable, where the member type is specified as a string.
Public Member Functions inherited from cgv::data::ascii_reflection_handler
bool reflect_header ()
ascii_reflection_handler (const std::string &_content, unsigned _ver, unsigned _tab=3)
void reflect_group_end (GroupKind group_kind)
abstract interface to terminate reflection of a group of members
Public Member Functions inherited from cgv::data::io_reflection_handler
io_reflection_handler (const std::string &_content, unsigned _ver)
bool failed () const
IOReflectionError get_error_code () const
bool reflect_method_void (const std::string &method_name, cgv::reflect::method_interface *mi_ptr, cgv::reflect::abst_reflection_traits *return_traits, const std::vector< cgv::reflect::abst_reflection_traits * > &param_value_traits)
abstract interface to reflect a method, where return and parameter types are specified as strings.
Public Member Functions inherited from cgv::reflect::reflection_handler
template<typename T >
bool reflect_member (const std::string &member_name, T &member_ref, bool hard_cast=false)
call this to reflect a member by member name and reference to the member.
template<typename M >
bool reflect_method (const std::string &method_name, M m)
call this to reflect a method by method name and reference to the member.
template<typename B >
bool reflect_base (B &base_ref)
reflect a base class with its members
template<typename T , unsigned n>
bool reflect_member (const std::string &member_name, T(&member_ref)[n])
reflect a member of constant size array type
template<typename T >
bool reflect_member (const std::string &member_name, std::vector< T > &member_ref)
reflect a member of vector type
template<typename T >
bool reflect_member (const std::string &member_name, T *&member_ref)
reflect a member of pointer type.
template<typename T , typename S >
bool reflect_array (const std::string &member_name, T *&member_ref, S &size)
reflect a dynamic array member of vector type
virtual ~reflection_handler ()
declare virtual destructor
Protected Member Functions
bool read_reflect_header (const std::string &_content, unsigned _ver)
Protected Member Functions inherited from cgv::data::ascii_reflection_handler
std::string extend_name (const std::string &name, bool assign=true)
Protected Member Functions inherited from cgv::reflect::reflection_handler
GroupTraversal process_structural_group_begin (GroupKind gk, const std::string &member_name, GroupTraversal gt)
type independent part of the reflect_group method that starts the group traversal
bool group_end (GroupKind gk)
updates the nesting info at the end of group and always returns true
template<typename T , typename RT , typename D >
bool self_reflect_member (const std::string &member_name, T &member_ref, const RT &, const D &, bool hard_cast)
implementation of reflection with internal or external self_reflect function
int reflect_array_begin (GroupKind group_kind, const std::string &group_name, void *group_ptr, abst_reflection_traits *rt, unsigned grp_size)
type independent functionality of array reflection
Protected Attributes
std::ifstream file_is
std::istream & is
Protected Attributes inherited from cgv::data::ascii_reflection_handler
unsigned nr_idents
NamingConvention naming_convention
unsigned tab_size
Protected Attributes inherited from cgv::data::io_reflection_handler
unsigned version
std::string file_content
bool in_header
IOReflectionError last_error
Protected Attributes inherited from cgv::reflect::reflection_handler
std::vector< nesting_info > nesting_info_stack
stack of nesting_info used during the reflection process
Additional Inherited Members
Public Types inherited from cgv::reflect::reflection_handler
enum GroupTraversal { GT_TERMINATE = -3 , GT_SKIP = -2 , GT_COMPLETE = -1 }
@ basic types with helper functions
enum GroupKind {
GK_NO_GROUP , GK_BASE_CLASS , GK_STRUCTURE , GK_VECTOR ,
GK_ARRAY , GK_POINTER
}
different support group types
Static Public Member Functions inherited from cgv::data::io_reflection_handler
static std::string get_error_message (IOReflectionError ae)
Static Public Member Functions inherited from cgv::reflect::reflection_handler
static std::string group_traversal_name (GroupTraversal gt)
return the group traversals as a string
static const char * group_kind_name (GroupKind gk)
return the group kind as a string
static bool is_array_kind (GroupKind gk)
check whether a group kind is of array or vector kind
Detailed Description
read from ascii file
Definition at line 50 of file ascii_io_reflection_handlers.h.
Member Function Documentation
reflect_group_begin()
int cgv::data::ascii_read_reflection_handler::reflect_group_begin (GroupKind group_kind, const std::string & group_name, void * group_ptr, cgv::reflect::abst_reflection_traits * rt, unsigned grp_size) virtual
abstract interface to start reflection of a group of members.
The return value gives information about further traversal of the group:
GT_TERMINATE ... terminate traversal completely
GT_SKIP ... skip traversal of group
GT_COMPLETE ... traverse group completely
index i >= 0 ... traverse only the i-th member of the group. Depending on the group kind, the remaining parameters are given as follows:
GK_BASE_CLASS ... group_name and grp_size are undefined, group_ptr is pointer to instance of base class, rt reflects base class
GK_STRUCTURE ... group_name is instance name, group_ptr is pointer to instance, rt reflects type of structure, grp_size is undefined,
GK_VECTOR ... group_name is vector name, group_ptr is pointer to vector data structure, rt reflects element type, grp_size is size of vector
GK_ARRAY ... group_name is array name, group_ptr is pointer to first array element, rt reflects element type, grp_size is size of array.
GK_POINTER ... group_name is pointer name, group_ptr is pointer to first array element, rt reflects type to which pointer poits, grp_size is undefined.
Reimplemented from cgv::data::ascii_reflection_handler.
Definition at line 130 of file ascii_io_reflection_handlers.cxx.
reflect_member_void()
bool cgv::data::ascii_read_reflection_handler::reflect_member_void (const std::string & member_name, void * member_ptr, cgv::reflect::abst_reflection_traits * rt) virtual
abstract interface to reflect a member variable, where the member type is specified as a string.
Returns whether to continue the reflection.
Implements cgv::reflect::reflection_handler.
Definition at line 144 of file ascii_io_reflection_handlers.cxx.
References cgv::reflect::abst_reflection_traits::get_type_id(), cgv::reflect::abst_reflection_traits::has_string_conversions(), cgv::utils::interpret_special(), cgv::reflect::abst_reflection_traits::set_from_string(), and cgv::type::info::TI_STRING.
The documentation for this class was generated from the following files:
cgv/data/ascii_io_reflection_handlers.h
cgv/data/ascii_io_reflection_handlers.cxx