cgv: cgv::app::performance_monitor Class Reference
cgv::app::performance_monitor Class Reference
Classes
struct layout_attributes
Public Member Functions
std::string get_type_name () const override
overload to return the type name of this object. By default the type interface is queried over get_type.
void clear (cgv::render::context &ctx) override
clear all objects living in the context like textures or display lists
void handle_member_change (const cgv::utils::pointer_test &m) override
implement to handle member changes
bool init (cgv::render::context &ctx) override
this method is called after creation or recreation of the context, return whether all necessary functionality is supported
void init_frame (cgv::render::context &ctx) override
this method is called in one pass over all drawables before the draw method
void draw_content (cgv::render::context &ctx) override
void after_finish (cgv::render::context &ctx) override
draw the content of the canvas overlay
void set_invert_color (bool flag)
void enable_monitoring (bool enabled)
void enable_monitoring_only_when_visible (bool enabled)
Public Member Functions inherited from cgv::app::themed_canvas_overlay
themed_canvas_overlay ()
creates an overlay in the bottom left corner with zero size using a canvas for 2d drawing
bool init (cgv::render::context &ctx) override
this method is called after creation or recreation of the context, return whether all necessary functionality is supported
virtual void handle_theme_change (const cgv::gui::theme_info &theme) override
override in your class to handle theme changes
bool get_background_visible () const
void set_background_visible (bool flag)
Public Member Functions inherited from cgv::app::canvas_overlay
canvas_overlay ()
creates an overlay in the bottom left corner with zero size using a canvas for 2d drawing
virtual void on_set (void *member_ptr) override
default implementation of that calls handle_member_change and afterwards upates the member in the gui and post damage to the canvas overlay
void post_damage (bool redraw=true)
ivec2 get_local_mouse_pos (ivec2 mouse_pos) const override
return the mouse position local to the container of this overlay taking the canvas origin into account
bool is_hit (const ivec2 &mouse_pos) const override
Test if the mouse pointer is hovering over this overlay and returns true if this is the case.
bool is_hit_local (const ivec2 &local_mouse_pos) const
See is_hit.
Public Member Functions inherited from cgv::app::overlay
virtual bool self_reflect (cgv::reflect::reflection_handler &_rh)
overload to reflect members of derived classes
virtual void stream_help (std::ostream &os)
overload to stream help information to the given output stream
virtual bool handle (cgv::gui::event &e)
handle incomming events; calls handle_key_events or handle_mouse_events depending on the event type; mouse events will only be handled if the mouse is over the overlay rectangle
virtual bool handle_key_event (cgv::gui::key_event &e)
overload this method to handle key events
virtual bool handle_mouse_event (cgv::gui::mouse_event &e, cgv::ivec2 local_mouse_pos)
overload this method to handle mouse events; local_mouse_pos is the mouse position in the local coordinate space of the overlay rectangle
bool blocks_events () const
return whether this overlay blocks events, i.e. does not pass them to the next event handler
void blocks_events (bool flag)
set whether the overlay blocks events
ivec2 get_viewport_size () const
return the current viewport size
cgv::g2d::irect get_rectangle () const
return the current rectangle area (in screen coordinates) of the overlay taking layout into account
cgv::g2d::irect get_local_rectangle () const
return the current rectangle area of the overlay in local space, i.e. with position set to zero
AlignmentOption get_horizontal_alignment () const
get the horizontal alignment
AlignmentOption get_vertical_alignment () const
get the vertical alignment
vec2 get_percentual_offset () const
get the percentual alignment offset (only valid if get_horizontal_alignment() or get_vertical_alignment() returns AlignmentOption::AO_PERCENTUAL)
void set_alignment (AlignmentOption horizontal, AlignmentOption vertical, vec2 percentual_offset=vec2(-1.0f))
set the alignment options
StretchOption get_stretch () const
get the stretch
vec2 get_percentual_size () const
get the percentual stretch (only valid if get_stretch() returns StretchOption::SO_PERCENTUAL)
void set_stretch (StretchOption stretch, vec2 percentual_size=vec2(-1.0f))
set the stretch option
ivec2 get_margin () const
return the margin as set in the layout parameters
void set_margin (const ivec2 &margin)
set the overlay margin
void set_size (const ivec2 &size)
set the default size of the overlay before stretch gets applied
void set_visibility (bool visible)
set the visibility of the overlay
void toggle_visibility ()
toggle the visibility of the overlay
bool ensure_viewport (cgv::render::context &ctx)
Check whether the viewport size has changed since the last call to this method.
bool ensure_layout (cgv::render::context &ctx)
bool begin_overlay_gui ()
begins a tree node if create default tree node is set in the gui options; automatically creates the layout gui
void end_overlay_gui ()
ends the tree node of the overlay gui
void create_layout_gui ()
provides a default gui implementation for private overlay layout members
void create_gui ()
Creates a tree node containing the overlay layout options and the gui as specified by the derived overlay class.
Public Member Functions inherited from cgv::base::node
node (const std::string &name="")
construct from name
node_ptr get_parent () const
return the parent node
base_ptr get_root () const
return the root node by traversing parents until no more parent is available
void set_parent (node_ptr _parent)
set a new parent node
node_ptr get_node ()
cast upward to node
const_node_ptr get_node_const ()
cast upward to const node
std::string get_type_name () const
overload to return the type name of this object
Public Member Functions inherited from cgv::base::named
named (const std::string &name="")
construct from name
const std::string & get_name () const
return the parent node
void set_name (const std::string &_name)
set a new parent node
named_ptr get_named ()
cast upward to named
const_named_ptr get_named_const ()
cast upward to const named
Public Member Functions inherited from cgv::base::base
virtual std::string get_default_options () const
overload to provide default options for registration
std::string get_name_or_type_name () const
determine name of instance by checking cgv::base::named interface and in failure fallback to get_type_name()
virtual void on_register ()
overload to handle register events that is sent after the instance has been registered
virtual void unregister ()
overload to handle unregistration of instances
virtual bool on_exit_request ()
overload to handle the appication exit request, return true if exiting is allowed and false otherwise
virtual void stream_stats (std::ostream &)
overload to show the content of this object
virtual data::ref_ptr< group, true > get_group ()
perform downcast to group
virtual data::ref_ptr< const named, true > get_named_const () const
perform downcast to const named
virtual data::ref_ptr< const node, true > get_node_const () const
perform downcast to const node
virtual data::ref_ptr< const group, true > get_group_const () const
perform downcast to const group
template<class T >
data::ref_ptr< T, true > cast ()
cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
data::ref_ptr< const T, true > cast_const ()
const cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
T * get_interface ()
use dynamic type cast to check for the given interface
template<class T >
const T * get_const_interface () const
use dynamic type cast to check for the given interface
virtual void update ()
this virtual update allows for example to ask a view to update the viewed value. The default implementation is empty.
virtual void * get_user_data () const
this virtual method allows to pass application specific data for internal purposes
virtual std::string get_property_declarations ()
return a semicolon separated list of property declarations
virtual bool set_void (const std::string &property, const std::string &value_type, const void *value_ptr)
abstract interface for the setter of a dynamic property.
virtual bool get_void (const std::string &property, const std::string &value_type, void *value_ptr)
abstract interface for the getter of a dynamic property.
virtual bool call_void (const std::string &method, const std::vector< std::string > &param_value_types, const std::vector< const void * > &param_value_ptrs, const std::string &result_type="", void *result_value_ptr=0)
abstract interface to call an action
void set (const std::string &property, const char *value)
specialization of set method to support const char* as strings
template<typename T >
void set (const std::string &property, const T &value)
set a property of the element to the given value and perform standard conversions if necessary.
template<typename T >
T get (const std::string &property)
query a property of the element and perform standard conversions if necessary.
void multi_set (const std::string &property_assignments, bool report_error=true)
set several properties
bool is_property (const std::string &property_name, std::string *type_name=0)
check if the given name specifies a property.
void * find_member_ptr (const std::string &property_name, std::string *type_name=0)
find a member pointer by name.
Public Member Functions inherited from cgv::data::ref_counted
int get_ref_count () const
read access to current count
Public Member Functions inherited from cgv::render::drawable
drawable ()
default construction
void hide ()
hide the drawable
void show ()
show the drawable
bool is_visible () const
check whether the drawable is visible
context * get_context () const
access the current context. The context will be available latestly in the init method but not in the contructor.
void set_context (context *_ctx)
set the current focus context, this should only be called by the context itself
view * find_view_as_node (size_t view_idx=0) const
convenience function to find the view control in the current hierarchy
bool get_world_location (int x, int y, const view &V, dvec3 &world_location, double *window_z_ptr=0) const
use given view together with depth buffer of context in order to compute the world location of the point at mouse pointer location (x,y)
void post_redraw ()
posts a redraw event to the current context if one is available
void force_redraw ()
forces a redraw right now. This cannot be called from init, init_frame, draw, finish_draw, finish_frame and clear
virtual void resize (unsigned int w, unsigned int h)
callback to announce resizing of the output window
virtual void draw (context &)
overload to draw the content of this drawable
virtual void finish_draw (context &)
this method is called when the current drawable is left in a tree traversal that calls the draw method
virtual void finish_frame (context &)
this method is called in one pass over all drawables after drawing
Public Member Functions inherited from cgv::base::traverse_policy
traverse_policy (int _policy=TP_ALL+TP_STOP_ON_SUCCESS, bool _active=true, int _focus=-1)
construct default traverse policy that visits everything
int get_policy () const
return the policy without the stop on success flag
bool stop_on_success () const
return whether to stop on success
bool stop_on_failure () const
return whether to stop on failure
void set_policy (int _policy)
set a new policy, always add stop on success flag if needed
int get_focused_child () const
return the focused child or -1 if none is focused
void set_focused_child (int _focused_child)
set the focused child
bool get_active () const
return whether the current node is active
void set_active (bool _active)
set the active flag of the current node
Public Member Functions inherited from cgv::gui::provider
void remove_element (cgv::base::base_ptr)
remove a single element from the gui
void remove_all_elements ()
this method removes all elements from the gui and can be used in a method that rebuilds the complete gui
cgv::base::base_ptr find_element (const std::string &name)
find a gui element by name in the current group, return empty pointer if not found
template<typename T >
data::ref_ptr< view< T > > find_view (const T &value, int *idx_ptr=0)
find a view of a given class member
template<typename T >
data::ref_ptr< control< T > > find_control (T &value, int *idx_ptr=0)
find a control of a given class member
control_ptr find_control_void (void *value_ptr, int *idx_ptr)
access to control of untyped member pointer
view_ptr find_view_void (void *value_ptr, int *idx_ptr)
access to view of untyped member pointer
template<typename T >
void set_control_property (T &value, const std::string &property_name, const std::string &property_value)
Set the property value of all controls of a given class member.
gui_group_ptr get_parent_group () const
use the parent group to append to be managed elements that should be destroyed in a post_recreate_gui event
view_ptr add_view_void (const std::string &label, const void *value_ptr, const std::string &value_type, const std::string &gui_type, const std::string &options, const std::string &align)
add a newly created view to the group
control_ptr add_control_void (const std::string &label, void *value_ptr, abst_control_provider *acp, const std::string &value_type, const std::string &gui_type, const std::string &options, const std::string &align, void *user_data)
add a newly created control to the group
provider ()
default construction
~provider ()
ensure to remove posted recreation callbacks
virtual std::string get_gui_name () const
Derive a name for this instance that can be used in the gui as heading.
virtual std::string get_parent_type () const
Returns the group type that should be used by the class embedding the gui of the provider.
virtual bool ensure_selected_in_tab_group_parent ()
ensure that my UI is selected in the parent group in case this is a tab group, otherwise return false
virtual void update_member (void *member_ptr)
call this to update all views and controls of a member
virtual void update_all_members ()
call this to update all views and controls of all member
virtual std::string get_menu_path () const
return a path in the main menu to select the gui
virtual shortcut get_shortcut () const
return a shortcut to activate the gui without menu navigation
virtual void recreate_gui ()
Recreate the gui of this instance right now.
virtual void post_recreate_gui ()
delayed recreation of gui
void align (const std::string &_align)
send pure alignment information
std::string concat_enum_def (const std::vector< std::string > &names, const std::string &additional_first_name="", const std::string &additional_last_name="")
add a new group to the given parent group, not supported yet
gui_group_ptr add_object_gui (cgv::base::base_ptr object, const std::string &label, const std::string &group_type, const std::string &options, const std::string &align)
void integrate_object_gui (cgv::base::base_ptr object)
call this in create_gui() function to integrate gui of another provider object by setting the parent group and parent provider of the other object
void inline_object_gui (cgv::base::base_ptr object)
integrate (if not explicitly done before) and inline the gui of another object that must be derived from provider
gui_group_ptr add_group (const std::string &label, const std::string &group_type, const std::string &options="", const std::string &align="\n")
add a newly created subgroup to the group
cgv::base::base_ptr add_decorator (const std::string &label, const std::string &decorator_type, const std::string &options="", const std::string &align="\n")
add a newly created decorator to the group
button_ptr add_button (const std::string &label, const std::string &options="", const std::string &align="\n")
use the current gui driver to append a new button with the given label
template<typename T >
data::ref_ptr< view< T > > add_view (const std::string &label, const T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
use this to add a new view to the gui with a given value type, gui type and init options
template<typename T >
data::ref_ptr< control< T > > add_control (const std::string &label, T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
use this to add a new control to the gui with a given value type, gui type and init options
template<typename T >
data::ref_ptr< control< T > > add_control (const std::string &label, control_provider< T > *provider, const std::string &gui_type="", const std::string &options="", const std::string &align="\n", void *user_data=0)
use this to add a new control to the gui, where the control is implemented with a control provider class
template<typename T >
data::ref_ptr< control< T > > add_member_control (cgv::base::base *base_ptr, const std::string &label, T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
add control with callback to cgv::base::on_set method on cgv::gui::control::value_change
bool add_tree_node (const std::string &label, bool &toggle, int level, const std::string &a="\n", gui_group_ptr ggp=gui_group_ptr())
add a collapsable node to the gui (deprecated)
template<typename T >
bool begin_tree_node (const std::string &label, const T &value, bool initial_visibility=false, const std::string &options="", gui_group_ptr ggp=gui_group_ptr())
Begin a sub tree of a tree structured gui.
template<typename T >
void end_tree_node (const T &value)
template specialization that allows to specify value reference plus node_instance by using the result of the function with_instance(value,idx) for the value argument finish a sub tree begun with begin_tree_node
template<typename T >
bool is_tree_node_visible (const T &value) const
return whether the sub tree attached to a value is visible
template<typename T >
void set_tree_node_visibility (const T &value, bool is_visible)
set the visibility status of sub tree attached to a value. This calls the post_recreate method if needed.
bool begin_tree_node_void (const std::string &label, const void *value_ptr, int index=-1, bool initial_visibility=false, const std::string &options="", gui_group_ptr ggp=gui_group_ptr())
void version of the templated functions
void end_tree_node_void (const void *value_ptr, int index=-1)
bool is_tree_node_visible_void (const void *value_ptr, int index) const
void set_tree_node_visibility_void (const void *value_ptr, int index, bool is_visible)
template<typename T >
bool add_gui (const std::string &label, T &value, const std::string &gui_type="", const std::string &options="")
Add a composed gui of the given gui_type for the given value.
Public Member Functions inherited from cgv::gui::event_handler
event_handler ()
default construction
bool grab_focus ()
grab the focus in all parent nodes
bool add_key_control (const std::string &property, const std::string &options, cgv::base::group_ptr group=cgv::base::group_ptr())
add a key control for the given property with the given options.
Protected Member Functions
DEFINE_GENERIC_RENDER_DATA_CLASS (bar_geometry, 3, vec2, position, vec2, size, rgb, color)
void init_styles () override
void create_static_texts (const cgv::render::context &ctx)
void create_dynamic_texts (const cgv::render::context &ctx)
void update_dynamic_texts (const cgv::render::context &ctx)
void update_plot ()
void on_visibility_change () override
called when the overlay visibility is changed through the default gui
void create_gui_impl () override
virtual method to implement the derived class gui creation
Protected Member Functions inherited from cgv::app::themed_canvas_overlay
void begin_content (cgv::render::context &ctx, bool clear_frame_buffer=true)
void init_container_style (const cgv::gui::theme_info &theme)
cgv::g2d::irect get_content_rectangle () const
return the current rectangle area of the themed_overlay content
int padding () const
Protected Member Functions inherited from cgv::app::canvas_overlay
bool ensure_layout (cgv::render::context &ctx)
void post_recreate_layout ()
void clear_damage ()
bool is_damaged () const
void begin_content (cgv::render::context &ctx, bool clear_frame_buffer=true)
void end_content (cgv::render::context &ctx, bool keep_damage=false)
virtual void draw_impl (cgv::render::context &ctx)
void register_shader (const std::string &name, const std::string &filename)
Protected Member Functions inherited from cgv::app::overlay
virtual void on_layout_change ()
called when the overlay layout parameters are changed through the default gui
void update_layout ()
update the layout of the overlay container
Protected Member Functions inherited from cgv::base::base
virtual ~base ()
make destructor virtual and not accessible from outside
Protected Member Functions inherited from cgv::data::ref_counted
ref_counted ()
constructor initializes the count to 0
void set_ref_count (int c) const
write access is also const to allow ref counted pointers to const instances
Protected Member Functions inherited from cgv::gui::provider
void set_parent (gui_group_ptr)
the gui window sets the parent group through this method
void update_parent ()
update the parent group
virtual void on_select ()
called by selection_change_cb whenever the gui of this provider is selected
virtual void on_deselect ()
called by selection_change_cb whenever the gui of this provider is deselected
virtual void selection_change_cb (cgv::base::base_ptr new_child, bool selected)
this is called by the gui group when the selection changes
Protected Attributes
struct cgv::app::performance_monitor::layout_attributes layout
struct {
bool enabled = true
whether measuring is enabled
bool enabled_only_when_visible = false
whether to enable monitoring only if the overlay is visible (uses state of enabled)
cgv::utils::stopwatch timer
timer to count elapsed time
unsigned total_frame_count = 0u
counter for rendered frames since start of measurements
unsigned interval_frame_count = 0u
counter for rendered frames incurrent interval
double interval = 0.25
time interval for measurement averaging
double last_seconds_since_start = 0.0
store total seconds since the last measuring
double delta_time = 0.0
store time of the last rendered frame in seconds
double running_time = 0.0
store time of current running interval in seconds
double avg_fps = 0.0
store the average frames per second
} monitor
measuring state fields
bool invert_color = false
bool show_plot = true
cgv::g2d::generic_2d_renderer bar_renderer
bar_geometry bars
cgv::g2d::shape2d_style border_style
cgv::g2d::shape2d_style bar_style
cgv::g2d::line2d_style line_style
cgv::render::color_map plot_color_map
cgv::g2d::text2d_style text_style
cgv::g2d::text2d_style tick_text_style
cgv::g2d::msdf_text_geometry static_text_geometry
cgv::g2d::msdf_text_geometry dynamic_text_geometry
Protected Attributes inherited from cgv::app::themed_canvas_overlay
bool background_visible_ = true
whether the background is visible (true by default)
Protected Attributes inherited from cgv::app::canvas_overlay
cgv::g2d::canvas overlay_canvas
cgv::g2d::canvas content_canvas
Protected Attributes inherited from cgv::base::node
node_ptr parent
store a pointer to the parent node
Protected Attributes inherited from cgv::base::named
std::string name
store the name as a string
Protected Attributes inherited from cgv::base::traverse_policy
TraversePolicy policy
bool active
int focus
Protected Attributes inherited from cgv::gui::provider
gui_group_ptr parent_group
driver specific handle for the group gui element managing the gui built in the provider
provider * parent_provider
Additional Inherited Members
Public Types inherited from cgv::app::overlay
enum AlignmentOption {
AO_FREE , AO_START , AO_CENTER , AO_END ,
AO_PERCENTUAL
}
enum StretchOption {
SO_NONE , SO_HORIZONTAL , SO_VERTICAL , SO_BOTH ,
SO_PERCENTUAL
}
Static Public Member Functions inherited from cgv::gui::provider
template<typename T >
static bool & ref_tree_node_visible_flag (const T &value)
return a reference to the boolean flag, that tells whether the tree node for the passed value is visible
static bool & ref_tree_node_visible_flag_void (const void *value_ptr, int index=-1)
Public Attributes inherited from cgv::app::overlay
gui_options_t gui_options
options for the GUI creation of this overlay (must be set before GUI creation)
Static Protected Member Functions inherited from cgv::base::base
template<class T >
static data::ref_ptr< T, true > cast_dynamic (base *b)
use dynamic cast for upcast to given class
Detailed Description
Definition at line 15 of file performance_monitor.h.
Constructor & Destructor Documentation
performance_monitor()
cgv::app::performance_monitor::performance_monitor ()
Definition at line 10 of file performance_monitor.cxx.
Member Function Documentation
after_finish()
void cgv::app::performance_monitor::after_finish (cgv::render::context & ctx) override virtual
draw the content of the canvas overlay
Reimplemented from cgv::app::canvas_overlay.
Definition at line 126 of file performance_monitor.cxx.
References cgv::render::drawable::after_finish(), enabled, cgv::render::drawable::is_visible(), and monitor.
clear()
void cgv::app::performance_monitor::clear (cgv::render::context &) override virtual
clear all objects living in the context like textures or display lists
Reimplemented from cgv::app::canvas_overlay.
Definition at line 23 of file performance_monitor.cxx.
References cgv::app::canvas_overlay::clear().
create_dynamic_texts()
void cgv::app::performance_monitor::create_dynamic_texts (const cgv::render::context & ctx) protected
Definition at line 261 of file performance_monitor.cxx.
create_gui_impl()
void cgv::app::performance_monitor::create_gui_impl () override protected virtual
virtual method to implement the derived class gui creation
Reimplemented from cgv::app::overlay.
Definition at line 176 of file performance_monitor.cxx.
References cgv::gui::provider::add_member_control(), cgv::app::themed_canvas_overlay::background_visible_, and monitor.
create_static_texts()
void cgv::app::performance_monitor::create_static_texts (const cgv::render::context & ctx) protected
Definition at line 216 of file performance_monitor.cxx.
draw_content()
void cgv::app::performance_monitor::draw_content (cgv::render::context & ctx) override virtual
Implements cgv::app::canvas_overlay.
Definition at line 93 of file performance_monitor.cxx.
enable_monitoring()
void cgv::app::performance_monitor::enable_monitoring (bool enabled)
Definition at line 159 of file performance_monitor.cxx.
enable_monitoring_only_when_visible()
void cgv::app::performance_monitor::enable_monitoring_only_when_visible (bool enabled)
Definition at line 164 of file performance_monitor.cxx.
get_type_name()
std::string cgv::app::performance_monitor::get_type_name () const inline override virtual
overload to return the type name of this object. By default the type interface is queried over get_type.
overload to return the type name of this object
Reimplemented from cgv::base::base.
Definition at line 95 of file performance_monitor.h.
handle_member_change()
void cgv::app::performance_monitor::handle_member_change (const cgv::utils::pointer_test & m) override virtual
implement to handle member changes
Reimplemented from cgv::app::canvas_overlay.
Definition at line 35 of file performance_monitor.cxx.
References cgv::app::themed_canvas_overlay::background_visible_, cgv::render::drawable::get_context(), cgv::utils::pointer_test::is(), monitor, cgv::app::overlay::set_size(), and cgv::math::fvec< T, N >::y().
init()
bool cgv::app::performance_monitor::init (cgv::render::context &) override virtual
this method is called after creation or recreation of the context, return whether all necessary functionality is supported
Reimplemented from cgv::app::canvas_overlay.
Definition at line 53 of file performance_monitor.cxx.
References cgv::app::canvas_overlay::init().
init_frame()
void cgv::app::performance_monitor::init_frame (cgv::render::context &) override virtual
this method is called in one pass over all drawables before the draw method
Reimplemented from cgv::render::drawable.
Definition at line 74 of file performance_monitor.cxx.
References enabled, cgv::app::overlay::get_rectangle(), cgv::render::drawable::is_visible(), and monitor.
init_styles()
void cgv::app::performance_monitor::init_styles () override protected virtual
Reimplemented from cgv::app::themed_canvas_overlay.
Definition at line 186 of file performance_monitor.cxx.
on_visibility_change()
void cgv::app::performance_monitor::on_visibility_change () override protected virtual
called when the overlay visibility is changed through the default gui
Reimplemented from cgv::app::overlay.
Definition at line 168 of file performance_monitor.cxx.
References cgv::render::drawable::is_visible(), and monitor.
set_invert_color()
void cgv::app::performance_monitor::set_invert_color (bool flag)
Definition at line 153 of file performance_monitor.cxx.
update_dynamic_texts()
void cgv::app::performance_monitor::update_dynamic_texts (const cgv::render::context & ctx) protected
Definition at line 281 of file performance_monitor.cxx.
update_plot()
void cgv::app::performance_monitor::update_plot () protected
Definition at line 306 of file performance_monitor.cxx.
Member Data Documentation
avg_fps
double cgv::app::performance_monitor::avg_fps = 0.0
store the average frames per second
Definition at line 56 of file performance_monitor.h.
bar_renderer
cgv::g2d::generic_2d_renderer cgv::app::performance_monitor::bar_renderer protected
Definition at line 70 of file performance_monitor.h.
bar_style
cgv::g2d::shape2d_style cgv::app::performance_monitor::bar_style protected
Definition at line 75 of file performance_monitor.h.
bars
bar_geometry cgv::app::performance_monitor::bars protected
Definition at line 72 of file performance_monitor.h.
border_style
cgv::g2d::shape2d_style cgv::app::performance_monitor::border_style protected
Definition at line 75 of file performance_monitor.h.
delta_time
double cgv::app::performance_monitor::delta_time = 0.0
store time of the last rendered frame in seconds
Definition at line 52 of file performance_monitor.h.
dynamic_text_geometry
cgv::g2d::msdf_text_geometry cgv::app::performance_monitor::dynamic_text_geometry protected
Definition at line 82 of file performance_monitor.h.
enabled
bool cgv::app::performance_monitor::enabled = true
whether measuring is enabled
Definition at line 38 of file performance_monitor.h.
Referenced by after_finish(), and init_frame().
enabled_only_when_visible
bool cgv::app::performance_monitor::enabled_only_when_visible = false
whether to enable monitoring only if the overlay is visible (uses state of enabled)
Definition at line 40 of file performance_monitor.h.
interval
double cgv::app::performance_monitor::interval = 0.25
time interval for measurement averaging
Definition at line 48 of file performance_monitor.h.
interval_frame_count
unsigned cgv::app::performance_monitor::interval_frame_count = 0u
counter for rendered frames incurrent interval
Definition at line 46 of file performance_monitor.h.
invert_color
bool cgv::app::performance_monitor::invert_color = false protected
Definition at line 67 of file performance_monitor.h.
last_seconds_since_start
double cgv::app::performance_monitor::last_seconds_since_start = 0.0
store total seconds since the last measuring
Definition at line 50 of file performance_monitor.h.
line_style
cgv::g2d::line2d_style cgv::app::performance_monitor::line_style protected
Definition at line 76 of file performance_monitor.h.
plot_color_map
cgv::render::color_map cgv::app::performance_monitor::plot_color_map protected
Definition at line 77 of file performance_monitor.h.
running_time
double cgv::app::performance_monitor::running_time = 0.0
store time of current running interval in seconds
Definition at line 54 of file performance_monitor.h.
show_plot
bool cgv::app::performance_monitor::show_plot = true protected
Definition at line 68 of file performance_monitor.h.
static_text_geometry
cgv::g2d::msdf_text_geometry cgv::app::performance_monitor::static_text_geometry protected
Definition at line 81 of file performance_monitor.h.
text_style
cgv::g2d::text2d_style cgv::app::performance_monitor::text_style protected
Definition at line 80 of file performance_monitor.h.
tick_text_style
cgv::g2d::text2d_style cgv::app::performance_monitor::tick_text_style protected
Definition at line 80 of file performance_monitor.h.
timer
cgv::utils::stopwatch cgv::app::performance_monitor::timer
timer to count elapsed time
Definition at line 42 of file performance_monitor.h.
total_frame_count
unsigned cgv::app::performance_monitor::total_frame_count = 0u
counter for rendered frames since start of measurements
Definition at line 44 of file performance_monitor.h.
The documentation for this class was generated from the following files:
libs/cgv_app/performance_monitor.h
libs/cgv_app/performance_monitor.cxx