cgv: cgv::data::ref_ptr_impl< T, is_ref_counted > Class Template Reference
cgv::data::ref_ptr_impl< T, is_ref_counted > Class Template Reference
Classes
struct counter_type
struct to store the pointer with a count
Public Member Functions
int get_count () const
return current count
Protected Member Functions
void release ()
decrement the count, delete if it is 0
T * ref () const
return the pointer itself
ref_ptr_impl (T *p=0)
construct reference counted pointer
ref_ptr_impl (const ref_ptr_impl< T, false > &r)
copy construct from same pointer type and increment count
template<typename S >
ref_ptr_impl (const ref_ptr_impl< S, false > &s)
copy construct from pointer of derived type with virtual destructor
Protected Attributes
counter_type * counter
store pointer to counter struct
Friends
class ref_ptr_impl< const T, is_ref_counted >
Detailed Description
template<typename T, bool is_ref_counted = false>
class cgv::data::ref_ptr_impl< T, is_ref_counted >
Definition at line 45 of file ref_ptr.h.
Constructor & Destructor Documentation
ref_ptr_impl() [1/3]
template<typename T , bool is_ref_counted = false> cgv::data::ref_ptr_impl< T, is_ref_counted >::ref_ptr_impl (T * p = 0) inline explicit protected
construct reference counted pointer
Definition at line 73 of file ref_ptr.h.
References cgv::data::ref_ptr_impl< T, is_ref_counted >::counter.
ref_ptr_impl() [2/3]
template<typename T , bool is_ref_counted = false> cgv::data::ref_ptr_impl< T, is_ref_counted >::ref_ptr_impl (const ref_ptr_impl< T, false > & r) inline protected
copy construct from same pointer type and increment count
Definition at line 78 of file ref_ptr.h.
References cgv::data::ref_ptr_impl< T, is_ref_counted >::counter.
ref_ptr_impl() [3/3]
template<typename T , bool is_ref_counted = false> template<typename S > cgv::data::ref_ptr_impl< T, is_ref_counted >::ref_ptr_impl (const ref_ptr_impl< S, false > & s) inline protected
copy construct from pointer of derived type with virtual destructor
Definition at line 85 of file ref_ptr.h.
References cgv::data::ref_ptr_impl< T, is_ref_counted >::counter.
Member Function Documentation
get_count()
template<typename T , bool is_ref_counted = false> int cgv::data::ref_ptr_impl< T, is_ref_counted >::get_count () const inline
return current count
Definition at line 99 of file ref_ptr.h.
References cgv::data::ref_ptr_impl< T, is_ref_counted >::counter.
Referenced by cgv::data::ref_ptr< T, is_ref_counted >::empty(), and cgv::data::ref_ptr< T, is_ref_counted >::unique().
ref()
template<typename T , bool is_ref_counted = false> T * cgv::data::ref_ptr_impl< T, is_ref_counted >::ref () const inline protected
return the pointer itself
Definition at line 71 of file ref_ptr.h.
References cgv::data::ref_ptr_impl< T, is_ref_counted >::counter.
Referenced by cgv::data::ref_ptr< T, is_ref_counted >::operator!=(), cgv::data::ref_ptr< T, is_ref_counted >::operator*(), cgv::data::ref_ptr< T, is_ref_counted >::operator->(), cgv::data::ref_ptr< T, is_ref_counted >::operator<(), and cgv::data::ref_ptr< T, is_ref_counted >::operator==().
release()
template<typename T , bool is_ref_counted = false> void cgv::data::ref_ptr_impl< T, is_ref_counted >::release () inline protected
decrement the count, delete if it is 0
Definition at line 59 of file ref_ptr.h.
References cgv::data::ref_ptr_impl< T, is_ref_counted >::counter.
Referenced by cgv::data::ref_ptr< T, is_ref_counted >::clear(), cgv::data::ref_ptr< T, is_ref_counted >::operator=(), and cgv::data::ref_ptr< T, is_ref_counted >::~ref_ptr().
Friends And Related Symbol Documentation
ref_ptr_impl< const T, is_ref_counted >
template<typename T , bool is_ref_counted = false> friend class ref_ptr_impl< const T, is_ref_counted > friend
Definition at line 31 of file ref_ptr.h.
Member Data Documentation
counter
template<typename T , bool is_ref_counted = false> counter_type* cgv::data::ref_ptr_impl< T, is_ref_counted >::counter mutable protected
store pointer to counter struct
Definition at line 57 of file ref_ptr.h.
Referenced by cgv::data::ref_ptr_impl< T, is_ref_counted >::get_count(), cgv::data::ref_ptr_impl< T, is_ref_counted >::ref(), cgv::data::ref_ptr_impl< T, is_ref_counted >::ref_ptr_impl(), cgv::data::ref_ptr_impl< T, is_ref_counted >::ref_ptr_impl(), cgv::data::ref_ptr_impl< T, is_ref_counted >::ref_ptr_impl(), and cgv::data::ref_ptr_impl< T, is_ref_counted >::release().
The documentation for this class was generated from the following file:
cgv/data/ref_ptr.h