cgv: cgv::app::generic_application_plugin< base_drawable > Class Template Reference
cgv::app::generic_application_plugin< base_drawable > Class Template Reference abstract
Extension of application_plugin_base that allows to define a used drawable base class.
#include <application_plugin.h>
Public Member Functions
generic_application_plugin (const std::string &name)
Constructs an instance of the class as a group node with the given name.
virtual void on_set (void *member_ptr)
Default implementation of the pure virtual base class method that delegates the member change evaluation to handle_member_change and performs the default actions of updating all member GUI views and requesting a redraw.
virtual void handle_member_change (const cgv::utils::pointer_test &m)
Empty default implementation to handle member changes from GUI interactions or manual calls to on_set() provided through a convenient evaluation interface.
virtual bool initialize_view_ptr () final
Initializes the view pointer using drawable::find_view_as_node().
template<class T >
cgv::data::ref_ptr< T > register_overlay (const std::string &name)
Registers an overlay instance as a child of this group.
virtual bool handle (cgv::gui::event &e) final
Final implementation of event_handler::handle() to support event handling of registered overlays.
virtual bool handle_event (cgv::gui::event &e)=0
Implement this method to handle any events not blocked by an registered overlay.
unsigned int get_nr_children () const
return the number of children
base_ptr get_child (unsigned int i) const
return the i-th child
virtual unsigned int append_child (base_ptr child)
append child and return index of appended child
virtual unsigned int remove_child (base_ptr child)
remove all elements of the vector that point to child, return the number of removed children
virtual void remove_all_children ()
remove all children
virtual void insert_child (unsigned int i, base_ptr child)
insert a child at the given position
group_ptr get_group ()
cast upward to group
const_group_ptr get_group_const ()
cast upward to const group
virtual data::ref_ptr< const group, true > get_group_const () const
const cast upward to group
std::string get_type_name () const
overload to return the type name of this object
node_ptr get_parent () const
return the parent node
base_ptr get_root () const
return the root node by traversing parents until no more parent is available
void set_parent (node_ptr _parent)
set a new parent node
node_ptr get_node ()
cast upward to node
const_node_ptr get_node_const ()
cast upward to const node
virtual data::ref_ptr< const node, true > get_node_const () const
const cast upward to node
const std::string & get_name () const
return the parent node
void set_name (const std::string &_name)
set a new parent node
named_ptr get_named ()
cast upward to named
const_named_ptr get_named_const ()
cast upward to const named
virtual data::ref_ptr< const named, true > get_named_const () const
const cast upward to named
virtual std::string get_default_options () const
overload to provide default options for registration
std::string get_name_or_type_name () const
determine name of instance by checking cgv::base::named interface and in failure fallback to get_type_name()
virtual void on_register ()
overload to handle register events that is sent after the instance has been registered
virtual void unregister ()
overload to handle unregistration of instances
virtual bool on_exit_request ()
overload to handle the appication exit request, return true if exiting is allowed and false otherwise
virtual void stream_stats (std::ostream &)
overload to show the content of this object
template<class T >
data::ref_ptr< T, true > cast ()
cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
data::ref_ptr< const T, true > cast_const ()
const cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
T * get_interface ()
use dynamic type cast to check for the given interface
template<class T >
const T * get_const_interface () const
use dynamic type cast to check for the given interface
virtual void update ()
this virtual update allows for example to ask a view to update the viewed value. The default implementation is empty.
virtual void * get_user_data () const
this virtual method allows to pass application specific data for internal purposes
int get_ref_count () const
read access to current count
bool grab_focus ()
grab the focus in all parent nodes
virtual void stream_help (std::ostream &os)=0
overload to stream help information to the given output stream
bool add_key_control (const std::string &property, const std::string &options, cgv::base::group_ptr group=cgv::base::group_ptr())
add a key control for the given property with the given options.
int get_policy () const
return the policy without the stop on success flag
bool stop_on_success () const
return whether to stop on success
bool stop_on_failure () const
return whether to stop on failure
void set_policy (int _policy)
set a new policy, always add stop on success flag if needed
int get_focused_child () const
return the focused child or -1 if none is focused
void set_focused_child (int _focused_child)
set the focused child
bool get_active () const
return whether the current node is active
void set_active (bool _active)
set the active flag of the current node
property interface
virtual bool self_reflect (cgv::reflect::reflection_handler &)
used for simple self reflection
virtual std::string get_property_declarations ()
return a semicolon separated list of property declarations
virtual bool set_void (const std::string &property, const std::string &value_type, const void *value_ptr)
abstract interface for the setter of a dynamic property.
virtual bool get_void (const std::string &property, const std::string &value_type, void *value_ptr)
abstract interface for the getter of a dynamic property.
virtual bool call_void (const std::string &method, const std::vector< std::string > &param_value_types, const std::vector< const void * > &param_value_ptrs, const std::string &result_type="", void *result_value_ptr=0)
abstract interface to call an action
void set (const std::string &property, const char *value)
specialization of set method to support const char* as strings
template<typename T >
void set (const std::string &property, const T &value)
set a property of the element to the given value and perform standard conversions if necessary.
template<typename T >
T get (const std::string &property)
query a property of the element and perform standard conversions if necessary.
void multi_set (const std::string &property_assignments, bool report_error=true)
set several properties
bool is_property (const std::string &property_name, std::string *type_name=0)
check if the given name specifies a property.
void * find_member_ptr (const std::string &property_name, std::string *type_name=0)
find a member pointer by name.
update of gui
void remove_element (base_ptr)
remove a single element from the gui
void remove_all_elements ()
this method removes all elements from the gui and can be used in a method that rebuilds the complete gui
base_ptr find_element (const std::string &name)
find a gui element by name in the current group, return empty pointer if not found
template<typename T >
data::ref_ptr< view< T > > find_view (const T &value, int *idx_ptr=0)
find a view of a given class member
template<typename T >
data::ref_ptr< control< T > > find_control (T &value, int *idx_ptr=0)
find a control of a given class member
control_ptr find_control_void (void *value_ptr, int *idx_ptr)
access to control of untyped member pointer
view_ptr find_view_void (void *value_ptr, int *idx_ptr)
access to view of untyped member pointer
template<typename T >
void set_control_property (T &value, const std::string &property_name, const std::string &property_value)
Set the property value of all controls of a given class member.
Protected Member Functions
void link (base_ptr b)
check if the base class is a node and set the parent of the node
void unlink (base_ptr b)
check if the base class is a node and clear the parent of the node
void set_ref_count (int c) const
write access is also const to allow ref counted pointers to const instances
Static Protected Member Functions
template<class T >
static data::ref_ptr< T, true > cast_dynamic (base *b)
use dynamic cast for upcast to given class
Protected Attributes
cgv::render::view * view_ptr
Stores a pointer to the base view.
std::vector< overlay_ptr > overlays
Stores a list of all overlays registered as children of this application plugin.
overlay_ptr last_blocking_overlay_ptr
Stores a pointer to the overlay that handled the previous event.
overlay_ptr blocking_overlay_ptr
Stores a pointer to the overlay that handles the current event.
std::vector< base_ptr > children
store a list of children
node_ptr parent
store a pointer to the parent node
std::string name
store the name as a string
interface used by the parent gui
gui_group_ptr get_parent_group () const
use the parent group to append to be managed elements that should be destroyed in a post_recreate_gui event
view_ptr add_view_void (const std::string &label, const void *value_ptr, const std::string &value_type, const std::string &gui_type, const std::string &options, const std::string &align)
add a newly created view to the group
control_ptr add_control_void (const std::string &label, void *value_ptr, abst_control_provider *acp, const std::string &value_type, const std::string &gui_type, const std::string &options, const std::string &align, void *user_data)
add a newly created control to the group
gui_group_ptr parent_group
driver specific handle for the group gui element managing the gui built in the provider
provider * parent_provider
void set_parent (gui_group_ptr)
the gui window sets the parent group through this method
void update_parent ()
update the parent group
creation of gui
void align (const std::string &_align)
send pure alignment information
std::string concat_enum_def (const std::vector< std::string > &names, const std::string &additional_first_name="", const std::string &additional_last_name="")
add a new group to the given parent group, not supported yet
gui_group_ptr add_object_gui (base_ptr object, const std::string &label, const std::string &group_type, const std::string &options, const std::string &align)
void integrate_object_gui (base_ptr object)
call this in create_gui() function to integrate gui of another provider object by setting the parent group and parent provider of the other object
void inline_object_gui (base_ptr object)
integrate (if not explicitly done before) and inline the gui of another object that must be derived from provider
gui_group_ptr add_group (const std::string &label, const std::string &group_type, const std::string &options="", const std::string &align="\n")
add a newly created subgroup to the group
base_ptr add_decorator (const std::string &label, const std::string &decorator_type, const std::string &options="", const std::string &align="\n")
add a newly created decorator to the group
button_ptr add_button (const std::string &label, const std::string &options="", const std::string &align="\n")
use the current gui driver to append a new button with the given label
template<typename T >
data::ref_ptr< view< T > > add_view (const std::string &label, const T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
use this to add a new view to the gui with a given value type, gui type and init options
template<typename T >
data::ref_ptr< control< T > > add_control (const std::string &label, T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
use this to add a new control to the gui with a given value type, gui type and init options
template<typename T >
data::ref_ptr< control< T > > add_control (const std::string &label, control_provider< T > *provider, const std::string &gui_type="", const std::string &options="", const std::string &align="\n", void *user_data=0)
use this to add a new control to the gui, where the control is implemented with a control provider class
template<typename T >
data::ref_ptr< control< T > > add_member_control (cgv::base::base *base_ptr, const std::string &label, T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
add control with callback to cgv::base::on_set method on cgv::gui::control::value_change
bool add_tree_node (const std::string &label, bool &toggle, int level, const std::string &a="\n", gui_group_ptr ggp=gui_group_ptr())
add a collapsable node to the gui (deprecated)
template<typename T >
bool begin_tree_node (const std::string &label, const T &value, bool initial_visibility=false, const std::string &options="", gui_group_ptr ggp=gui_group_ptr())
Begin a sub tree of a tree structured gui.
template<typename T >
void end_tree_node (const T &value)
template specialization that allows to specify value reference plus node_instance by using the result of the function with_instance(value,idx) for the value argument finish a sub tree begun with begin_tree_node
template<typename T >
bool is_tree_node_visible (const T &value) const
return whether the sub tree attached to a value is visible
template<typename T >
void set_tree_node_visibility (const T &value, bool is_visible)
set the visibility status of sub tree attached to a value. This calls the post_recreate method if needed.
bool begin_tree_node_void (const std::string &label, const void *value_ptr, int index=-1, bool initial_visibility=false, const std::string &options="", gui_group_ptr ggp=gui_group_ptr())
void version of the templated functions
void end_tree_node_void (const void *value_ptr, int index=-1)
bool is_tree_node_visible_void (const void *value_ptr, int index) const
void set_tree_node_visibility_void (const void *value_ptr, int index, bool is_visible)
template<typename T >
bool add_gui (const std::string &label, T &value, const std::string &gui_type="", const std::string &options="")
Add a composed gui of the given gui_type for the given value.
template<typename T >
static bool & ref_tree_node_visible_flag (const T &value)
return a reference to the boolean flag, that tells whether the tree node for the passed value is visible
static bool & ref_tree_node_visible_flag_void (const void *value_ptr, int index=-1)
callbacks
virtual std::string get_gui_name () const
Derive a name for this instance that can be used in the gui as heading.
virtual std::string get_parent_type () const
Returns the group type that should be used by the class embedding the gui of the provider.
virtual bool ensure_selected_in_tab_group_parent ()
ensure that my UI is selected in the parent group in case this is a tab group, otherwise return false
virtual void update_member (void *member_ptr)
call this to update all views and controls of a member
virtual void update_all_members ()
call this to update all views and controls of all member
virtual std::string get_menu_path () const
return a path in the main menu to select the gui
virtual shortcut get_shortcut () const
return a shortcut to activate the gui without menu navigation
virtual void create_gui ()=0
you must overload this for gui creation
virtual void recreate_gui ()
Recreate the gui of this instance right now.
virtual void post_recreate_gui ()
delayed recreation of gui
virtual void on_select ()
called by selection_change_cb whenever the gui of this provider is selected
virtual void on_deselect ()
called by selection_change_cb whenever the gui of this provider is deselected
virtual void selection_change_cb (cgv::base::base_ptr new_child, bool selected)
this is called by the gui group when the selection changes
Detailed Description
template<class base_drawable>
class cgv::app::generic_application_plugin< base_drawable >
Extension of application_plugin_base that allows to define a used drawable base class.
Template Parameters
base_drawable the used drawable type.
Definition at line 97 of file application_plugin.h.
Constructor & Destructor Documentation
generic_application_plugin()
template<class base_drawable > cgv::app::generic_application_plugin< base_drawable >::generic_application_plugin (const std::string & name) inline
Constructs an instance of the class as a group node with the given name.
Parameters
name the name of this node.
Definition at line 102 of file application_plugin.h.
Member Function Documentation
add_gui()
template<typename T > bool cgv::gui::provider::add_gui (const std::string & label, T & value, const std::string & gui_type = "", const std::string & options = "") inline inherited
Add a composed gui of the given gui_type for the given value.
This function returns false if no cgv::base::gui_creator has been registered for the given gui_type. The plugin cg_ext contains registers gui_creators for the most important types of the framework. The supported values for the options parameter are specific for the gui_type. Currently these are not documented and can only be found in the source code of the cg_ext plugin.
Definition at line 247 of file provider.h.
References cgv::gui::create_gui().
Referenced by cgv::plot::plot_base::create_base_config_gui(), cgv::plot::plot3d::create_gui(), and cgv::plot::plot_base::create_plot_gui().
add_key_control()
bool cgv::gui::event_handler::add_key_control (const std::string & property, const std::string & options, cgv::base::group_ptr group = cgv::base::group_ptr()) inherited
add a key control for the given property with the given options.
grab the focus in all parent nodes
This should be called in classes derived from cgv::base::group and event_handler. The group argument should be the this pointer cast to cgv::base_group. If group is not given, a dynamic_cast is performed on the this pointer.
Definition at line 22 of file event_handler.cxx.
References cgv::base::group::append_child(), cgv::data::ref_ptr< T, is_ref_counted >::empty(), cgv::base::base::find_member_ptr(), and cgv::base::base::on_set().
add_member_control()
template<typename T > data::ref_ptr<control<T> > cgv::gui::provider::add_member_control (cgv::base::base * base_ptr, const std::string & label, T & value, const std::string & gui_type = "", const std::string & options = "", const std::string & align = "\n") inline inherited
add control with callback to cgv::base::on_set method on cgv::gui::control::value_change
use this method to add a control of a member and a callback to the on_set method of the cgv::base::base class.
Definition at line 137 of file provider.h.
References cgv::base::base::on_set().
Referenced by cgv::plot::plot_base::create_bar_config_gui(), cgv::plot::plot_base::create_base_config_gui(), cgv::plot::plot3d::create_config_gui(), cgv::plot::plot_base::create_config_gui(), cgv::plot::axis_config::create_gui(), cgv::plot::plot2d::create_gui(), cgv::plot::plot_base::create_gui(), cgv::plot::plot3d::create_line_config_gui(), cgv::plot::plot_base::create_plot_gui(), and cgv::plot::plot_base::create_stick_config_gui().
add_tree_node()
bool cgv::gui::provider::add_tree_node (const std::string & label, bool & toggle, int level, const std::string & a = "\n", gui_group_ptr ggp = gui_group_ptr()) inherited
add a collapsable node to the gui (deprecated)
This method is one possibility to support tree like guis with nodes that can be opened or closed. The other prefarable possibitly builds on the functions begin_tree_node() and end_tree_node().
Each node is represented by a heading with the text provided in the first parameter and of heading level specified in the first parameter. The state of the node is stored in a boolean variable "toggle" that must be supplied by the implementation of the provider. The toggle needs to be initialized in the constructor and is used in the create_gui method to only provide the gui of the subtree if toggle is true. Every time the status of the node is changed, the whole gui is rebuild with the post_recreate_gui method. The value of the toggle is also the return parameter of add_tree_node such the typical code inside the create_gui method looks like
if (add_tree_node("Node", toggle, 2)) {
   align("\a"); // indent gui elements of tree node
   // create gui of subtree
   align("\b"); // undo indentation
}
Definition at line 183 of file provider.cxx.
References cgv::gui::provider::parent_group, cgv::gui::provider::post_recreate_gui(), and cgv::utils::to_string().
begin_tree_node()
template<typename T > bool cgv::gui::provider::begin_tree_node (const std::string & label, const T & value, bool initial_visibility = false, const std::string & options = "", gui_group_ptr ggp = gui_group_ptr()) inline inherited
Begin a sub tree of a tree structured gui.
This function addes a toggle button and a heading for the tree node. The toggle button can be used to show or hide the subtree below the tree node. The heading shows simply the label parameter. The function returns the visibility state of the subtree below the tree node. Therefore its contents should only be specified if the function returns true. In that case one needs to terminate the gui elements added for the tree node with the end_tree_node function. A typical example would be
if (begin_tree_node("Node", composed_value)) {
   align("\a"); // indent gui elements of tree node
   // create gui of composed_value
   align("\b"); // undo indentation
   end_tree_node(composed_value);
}
The state of the toggle button is attached to a boolean flag that is globally managed by the provider. If your this pointer can be converted to cgv::base::base, the on_set callback with a pointer to the flag is called when the user toggles the tree node. To check in the on_set callback for the tree node toggle one can get a reference to the boolean flag with the ref_tree_node_visible_flag method.
To allocate the boolean flag the reference to a value controlled by the tree node is specified. The pointer to the controlled value is used as key for a map that manages the toggle states of all tree node buttons. If there is no superior structure whose value is controlled by the tree node, one can specify any of the values controled by the tree node. It is just important that no two tree nodes use the same value and that the pointer to the value cannot change. The latter is for example the case, when one uses an entry in a std::vector that can change size and reallocate its values. Then one should use the std::vector itself as value. In order to be able to distinguish the different elements of a vector one can extend the key from a value reference to a pair of a value reference plus an index. The index is then the index of the vector element. This is done by specifying with_index(value, idx) in the value argument. An example could look as follows:
if (begin_tree_node("Node", vec)) {
   align("\a"); // indent gui elements of tree node
   for (unsigned i=0; i<vec.size; ++i) {
        if (begin_tree_node(std::string("element ")+cgv::utils::to_string(i), with_index(vec,i))) {
           align("\a"); // indent gui elements of tree node for vector element
           // create gui of vector element
           align("\b"); // undo indentation
           end_tree_node(with_index(vec,i));
        }
    }
    align("\b"); // undo indentation
    end_tree_node(vec);
}
Definition at line 212 of file provider.h.
Referenced by cgv::plot::plot3d::create_config_gui(), cgv::plot::plot_base::create_config_gui(), cgv::plot::axis_config::create_gui(), cgv::plot::plot2d::create_gui(), cgv::plot::plot3d::create_gui(), cgv::plot::plot_base::create_gui(), and cgv::plot::plot_base::create_plot_gui().
call_void()
bool cgv::base::base::call_void (const std::string & method, const std::vector< std::string > & param_value_types, const std::vector< const void * > & param_value_ptrs, const std::string & result_type = "", void * result_value_ptr = 0) virtual inherited
abstract interface to call an action
overload to implement the execution of a method based on the method name and the given parameters
, i.e. a class method based on the action name and the given parameters. The default implementation uses the self_reflect() method to dispatch this call. If not found, the get_void method returns false.
Definition at line 168 of file base.cxx.
concat_enum_def()
std::string cgv::gui::provider::concat_enum_def (const std::vector< std::string > & names, const std::string & additional_first_name = "", const std::string & additional_last_name = "") inherited
add a new group to the given parent group, not supported yet
concatenate names in string to enum declaration and optionally prepend or append given additional names
Add group with the gui of another object inside.
Add a new group, where the group elements are defined by another object that must be derived from provider. You can use the same group types as in the add_group method. concatenate names in string to enum declaration and optionally prepend or append given additional names
Definition at line 43 of file provider.cxx.
end_tree_node()
template<typename T > void cgv::gui::provider::end_tree_node (const T & value) inline inherited
template specialization that allows to specify value reference plus node_instance by using the result of the function with_instance(value,idx) for the value argument finish a sub tree begun with begin_tree_node
This functions should be called only if the corresponding call to begin_tree_node returned true.
Definition at line 222 of file provider.h.
Referenced by cgv::plot::plot3d::create_config_gui(), cgv::plot::plot_base::create_config_gui(), cgv::plot::axis_config::create_gui(), cgv::plot::plot2d::create_gui(), cgv::plot::plot3d::create_gui(), cgv::plot::plot_base::create_gui(), and cgv::plot::plot_base::create_plot_gui().
ensure_selected_in_tab_group_parent()
bool cgv::gui::provider::ensure_selected_in_tab_group_parent () virtual inherited
ensure that my UI is selected in the parent group in case this is a tab group, otherwise return false
ensure that my UI is selected in the closest parent that is a tab group
Definition at line 407 of file provider.cxx.
References cgv::gui::provider::get_parent_group().
find_control()
template<typename T > data::ref_ptr<control<T> > cgv::gui::provider::find_control (T & value, int * idx_ptr = 0) inline inherited
find a control of a given class member
find the next control of the given value in the current group. If the index pointer is given, start at the index to which the pointer points and set this index to the index of the child index of the found control
Definition at line 330 of file provider.h.
References cgv::data::ref_ptr< T, is_ref_counted >::empty().
Referenced by cgv::plot::plot_base::create_plot_gui().
find_member_ptr()
void * cgv::base::base::find_member_ptr (const std::string & property_name, std::string * type_name = 0) inherited
find a member pointer by name.
If not found the null pointer is returned. If the type name string pointer is provided, the type of the property is copied to the referenced string.
Definition at line 360 of file base.cxx.
References cgv::reflect::find_reflection_handler::found_target(), cgv::reflect::find_reflection_handler::get_member_ptr(), cgv::reflect::find_reflection_handler::get_reflection_traits(), and cgv::reflect::abst_reflection_traits::get_type_name().
Referenced by cgv::gui::event_handler::add_key_control().
find_view()
template<typename T > data::ref_ptr<view<T> > cgv::gui::provider::find_view (const T & value, int * idx_ptr = 0) inline inherited
find a view of a given class member
find the next view of the given value in the current group. If the index pointer is given, start at the index to which the pointer points and set this index to the index of the child index of the found view
Definition at line 320 of file provider.h.
References cgv::data::ref_ptr< T, is_ref_counted >::empty().
get()
template<typename T > T cgv::base::base::get (const std::string & property) inline inherited
query a property of the element and perform standard conversions if necessary.
This templated version simply extracts the type of the value from the reference and calls the set_void() method. Note that this only works if the template cgv::type::info::type_name<T> is overloaded for the value type.
Definition at line 192 of file base.h.
get_gui_name()
std::string cgv::gui::provider::get_gui_name () const virtual inherited
Derive a name for this instance that can be used in the gui as heading.
this method uses the following strategy to automatically determine the name shown in guis for a provider instance:
This method uses the following strategy to automatically determine the name shown in guis for a provider instance:
try to cast the object into cgv::base::named, if successful, use get_name() method
check whether get_menu_path() results in a path or name. In case of a path, use the last entry of the path as name.
try to cast to cgv::base::base and use get_type_name().
return "unnamed" otherwise
try to cast the object into cgv::base::named, if successful, use get_name() method
check whether get_menu_path() results in a path or name. In case of a path, use the last entry of the path as name.
try to cast to cgv::base::base and use get_type_name().
return "unnamed" otherwise
Definition at line 383 of file provider.cxx.
References cgv::gui::provider::get_menu_path(), cgv::base::base::get_named(), and cgv::base::base::get_type_name().
Referenced by cgv::gui::provider::update_parent().
get_parent_type()
std::string cgv::gui::provider::get_parent_type () const virtual inherited
Returns the group type that should be used by the class embedding the gui of the provider.
The default is to use a group of type "align_group". Overload this virtual method to use a different group type, such as layout group.
Definition at line 402 of file provider.cxx.
get_property_declarations()
std::string cgv::base::base::get_property_declarations () virtual inherited
return a semicolon separated list of property declarations
return a semicolon separated list of property declarations of the form "name:type", by default an empty list is returned
of the form "name1:type1;name2:type2;...", by default an empty list is returned. The types should by consistent with the names returned by cgv::type::info::type_name::get_name. The default implementation extracts names and types from the self_reflect() method and the meta type information provided by the get_type() method.
Reimplemented in cgv::media::video::video_writer, cgv::media::video::video_reader, cgv::media::image::image_writer, cgv::media::image::image_reader, cgv::base::factory, cgv::base::console, and cgv::base::base_generator.
Definition at line 264 of file base.cxx.
Referenced by cgv::media::image::image_reader::get_property_declarations(), cgv::media::image::image_writer::get_property_declarations(), cgv::media::video::video_reader::get_property_declarations(), and cgv::media::video::video_writer::get_property_declarations().
get_void()
bool cgv::base::base::get_void (const std::string & property, const std::string & value_type, void * value_ptr) virtual inherited
abstract interface for the getter of a dynamic property.
abstract interface for the getter, by default it simply returns false
The default implementation uses the self_reflect() method to find a member with the given property as name. If not found, the get_void method returns false.
Reimplemented in cgv::base::factory, cgv::base::console, cgv::base::base_generator, cgv::media::video::video_writer, cgv::media::video::video_reader, cgv::media::image::image_writer, and cgv::media::image::image_reader.
Definition at line 215 of file base.cxx.
References cgv::reflect::find_reflection_handler::found_valid_target().
Referenced by cgv::media::image::image_reader::get_void(), cgv::media::image::image_writer::get_void(), cgv::media::video::video_reader::get_void(), and cgv::media::video::video_writer::get_void().
handle()
bool cgv::app::application_plugin_base::handle (cgv::gui::event & e) final virtual inherited
Final implementation of event_handler::handle() to support event handling of registered overlays.
Implement handle_event to handle any events that are passed to the instance of this class.
Parameters
e the event to handle.
Returns
true if the event was handled and stopped here, false otherwise.
Implements cgv::gui::event_handler.
Definition at line 16 of file application_plugin.cxx.
References cgv::app::application_plugin_base::blocking_overlay_ptr, cgv::gui::EF_DND, cgv::gui::EID_MOUSE, cgv::gui::mouse_event::get_action(), cgv::gui::event::get_flags(), cgv::gui::event::get_kind(), cgv::gui::mouse_event::get_x(), cgv::gui::mouse_event::get_y(), cgv::app::application_plugin_base::handle_event(), cgv::app::application_plugin_base::last_blocking_overlay_ptr, cgv::gui::MA_ENTER, cgv::gui::MA_LEAVE, cgv::gui::MA_MOVE, cgv::gui::MA_PRESS, cgv::gui::MA_RELEASE, cgv::gui::MA_WHEEL, cgv::app::application_plugin_base::overlays, and cgv::gui::mouse_event::set_action().
handle_event()
virtual bool cgv::app::application_plugin_base::handle_event (cgv::gui::event & e) pure virtual inherited
Implement this method to handle any events not blocked by an registered overlay.
Parameters
e the event to handle.
Returns
true if the event was handled and stopped here, false otherwise.
Referenced by cgv::app::application_plugin_base::handle().
handle_member_change()
template<class base_drawable > virtual void cgv::app::generic_application_plugin< base_drawable >::handle_member_change (const cgv::utils::pointer_test & m) inline virtual
Empty default implementation to handle member changes from GUI interactions or manual calls to on_set() provided through a convenient evaluation interface.
Parameters
m the pointer_test interface used to conveniently evaluate the affected member.
Implements cgv::app::application_plugin_base.
Definition at line 118 of file application_plugin.h.
Referenced by cgv::app::generic_application_plugin< base_drawable >::on_set().
initialize_view_ptr()
template<class base_drawable > virtual bool cgv::app::generic_application_plugin< base_drawable >::initialize_view_ptr () inline final virtual
Initializes the view pointer using drawable::find_view_as_node().
Can be used to check when the view pointer is available and, e.g., perform one-time initializations of dependent members. Due to the non-guaranteed registration order of plugins it is advisable to call this method in drawable::init_frame.
Returns
true when the view pointer is set initially (this will only fire once), false otherwise.
Implements cgv::app::application_plugin_base.
Definition at line 127 of file application_plugin.h.
References cgv::app::application_plugin_base::view_ptr.
is_property()
bool cgv::base::base::is_property (const std::string & property_name, std::string * type_name = 0) inherited
check if the given name specifies a property.
If the type name string pointer is provided, the type of the property is copied to the referenced string.
Definition at line 336 of file base.cxx.
References cgv::utils::bite_all(), and cgv::utils::to_string().
multi_set()
void cgv::base::base::multi_set (const std::string & property_assignments, bool report_error = true) inherited
set several properties
set several properties, which are defined as colon separated assignments, where the types are derived automatically
, which are defined as colon separated assignments, where the types are derived automatically to bool, int, double or std::string.
Definition at line 287 of file base.cxx.
References cgv::utils::bite_all(), cgv::utils::is_digit(), cgv::utils::is_integer(), and cgv::utils::to_string().
Referenced by cgv::base::has_property(), and cgv::render::texture::write_to_file().
on_set()
template<class base_drawable > virtual void cgv::app::generic_application_plugin< base_drawable >::on_set (void * member_ptr) inline virtual
Default implementation of the pure virtual base class method that delegates the member change evaluation to handle_member_change and performs the default actions of updating all member GUI views and requesting a redraw.
Parameters
member_ptr the pointer to the affected member.
Implements cgv::app::application_plugin_base.
Definition at line 108 of file application_plugin.h.
References cgv::app::generic_application_plugin< base_drawable >::handle_member_change(), and cgv::gui::provider::update_member().
post_recreate_gui()
void cgv::gui::provider::post_recreate_gui () virtual inherited
delayed recreation of gui
schedule the recreation of the gui for the next time the program is idle. This mechanism is implemented in a thread save way.
Definition at line 509 of file provider.cxx.
References cgv::gui::get_trigger_server(), cgv::gui::provider::parent_group, and cgv::gui::provider::post_recreate_gui().
Referenced by cgv::gui::provider::add_tree_node(), cgv::gui::provider::begin_tree_node_void(), and cgv::gui::provider::post_recreate_gui().
recreate_gui()
void cgv::gui::provider::recreate_gui () virtual inherited
Recreate the gui of this instance right now.
Use this method to recreate the gui, dont call create gui directly. Be careful when calling the method from a functor that is attached to a gui element generated by this provider. This can cause the gui element to be destroyed before the callback triggering the recreate_gui method has been completely finished, what might make the program crash. Use the post_recreate_gui method instead.
Definition at line 436 of file provider.cxx.
References cgv::gui::provider::create_gui(), cgv::gui::provider::parent_group, and cgv::gui::provider::remove_all_elements().
ref_tree_node_visible_flag()
template<typename T > static bool& cgv::gui::provider::ref_tree_node_visible_flag (const T & value) inline static inherited
return a reference to the boolean flag, that tells whether the tree node for the passed value is visible
T can be with_index(v,i) as in the begin_tree_node function. You typically need this function in an on_set callback to check whether the user has toggled a tree node
Definition at line 217 of file provider.h.
register_overlay()
template<class T > cgv::data::ref_ptr<T> cgv::app::application_plugin_base::register_overlay (const std::string & name) inline inherited
Registers an overlay instance as a child of this group.
Template Parameters
T the overlay class type; must inherit from overlay.
Parameters
name the name of the overlay instance.
Returns
a ref_ptr to the registered overlay instance.
Definition at line 57 of file application_plugin.h.
References cgv::base::group::append_child().
self_reflect()
bool cgv::base::base::self_reflect (cgv::reflect::reflection_handler &) virtual inherited
used for simple self reflection
is used by default implementation of set_void, get_void and get_property_declarations
The overloaded implementation is used by the default implementations of set_void, get_void and get_property_declarations with corresponding reflection handlers. The default implementation of self_reflect is empty.
Reimplemented in cgv::render::render_config.
Definition at line 161 of file base.cxx.
set()
template<typename T > void cgv::base::base::set (const std::string & property, const T & value) inline inherited
set a property of the element to the given value and perform standard conversions if necessary.
This templated version simply extracts the type of the value from the reference and calls the set_void() method. Note that this only works if the template cgv::type::info::type_name<T> is overloaded for the value type.
Definition at line 186 of file base.h.
set_control_property()
template<typename T > void cgv::gui::provider::set_control_property (T & value, const std::string & property_name, const std::string & property_value) inline inherited
Set the property value of all controls of a given class member.
Use this method to loop over all controls of the given value and set their named property to the specified property value.
Definition at line 343 of file provider.h.
set_void()
bool cgv::base::base::set_void (const std::string & property, const std::string & value_type, const void * value_ptr) virtual inherited
abstract interface for the setter of a dynamic property.
abstract interface for the setter, by default it simply returns false
The default implementation uses the self_reflect() method to find a member with the given property as name. If not found, the set_void method returns false.
Reimplemented in cgv::base::factory, cgv::base::console, cgv::base::base_generator, cgv::media::video::video_writer, cgv::media::video::video_reader, cgv::media::image::image_writer, and cgv::media::image::image_reader.
Definition at line 181 of file base.cxx.
Referenced by cgv::media::image::image_reader::set_void(), cgv::media::image::image_writer::set_void(), cgv::media::video::video_reader::set_void(), and cgv::media::video::video_writer::set_void().
Member Data Documentation
view_ptr
cgv::render::view* cgv::app::application_plugin_base::view_ptr protected inherited
Stores a pointer to the base view.
If a specific view is required in an implementation, it is advised to declare a new member with the specific view name in the actual implementation of this class.
Definition at line 33 of file application_plugin.h.
Referenced by cgv::app::application_plugin_base::application_plugin_base(), and cgv::app::generic_application_plugin< base_drawable >::initialize_view_ptr().
The documentation for this class was generated from the following file:
libs/cgv_app/application_plugin.h