cgv: cgv::data::ref_ptr_tag Class Reference
cgv::data::ref_ptr_tag Class Reference
struct used to make ref pointers to ref_counted friends of ref_counted
#include <ref_ptr.h>
Protected Member Functions
void inc_ref_count (const ref_counted *ptr) const
increment the count of a ref counted object
bool dec_ref_count (const ref_counted *ptr) const
decrement the count of a ref counted object and return whether to delete the object
Detailed Description
struct used to make ref pointers to ref_counted friends of ref_counted
Definition at line 22 of file ref_ptr.h.
Member Function Documentation
dec_ref_count()
bool cgv::data::ref_ptr_tag::dec_ref_count (const ref_counted * ptr) const inline protected
decrement the count of a ref counted object and return whether to delete the object
Definition at line 31 of file ref_ptr.h.
References cgv::data::ref_counted::get_ref_count(), and cgv::data::ref_counted::set_ref_count().
inc_ref_count()
void cgv::data::ref_ptr_tag::inc_ref_count (const ref_counted * ptr) const inline protected
increment the count of a ref counted object
Definition at line 26 of file ref_ptr.h.
References cgv::data::ref_counted::get_ref_count(), and cgv::data::ref_counted::set_ref_count().
The documentation for this class was generated from the following file:
cgv/data/ref_ptr.h