cgv: cgv::app::application_plugin_base Class Reference
cgv::app::application_plugin_base Class Reference abstract
Abstract base class for application plugins that provides capability to handle overlays, GUI interaction and event handling.
#include <application_plugin.h>
Public Member Functions
application_plugin_base (const std::string &name)
Provides a base constructor that calls the base class constructor of group.
template<class T >
cgv::data::ref_ptr< T > register_overlay (const std::string &name)
Registers an overlay instance as a child of this group.
unsigned unregister_overlay (overlay_ptr ptr)
Unregisters an overlay instance that is a child of this group.
virtual bool handle (cgv::gui::event &e) final
Final implementation of event_handler::handle() to support event handling of registered overlays.
virtual bool handle_event (cgv::gui::event &e)=0
Implement this method to handle any events not blocked by an registered overlay.
virtual void on_set (void *member_ptr)=0
Implement this method to handle member changes from GUI interactions or manual calls to on_set().
virtual void handle_member_change (const cgv::utils::pointer_test &m)=0
Implement this method to handle member changes from GUI interactions or manual calls to on_set() provided through a convenient evaluation interface.
virtual bool initialize_view_ptr ()=0
Implement this method to initialize the view pointer to a valid value and return whether this was successfull.
Public Member Functions inherited from cgv::base::group
group (const std::string &name="")
construct from name
unsigned int get_nr_children () const
return the number of children
base_ptr get_child (unsigned int i) const
return the i-th child
virtual unsigned int append_child (base_ptr child)
append child and return index of appended child
virtual unsigned int remove_child (base_ptr child)
remove all elements of the vector that point to child, return the number of removed children
virtual void remove_all_children ()
remove all children
virtual void insert_child (unsigned int i, base_ptr child)
insert a child at the given position
group_ptr get_group ()
cast upward to group
const_group_ptr get_group_const ()
cast upward to const group
std::string get_type_name () const
overload to return the type name of this object
Public Member Functions inherited from cgv::base::node
node (const std::string &name="")
construct from name
node_ptr get_parent () const
return the parent node
base_ptr get_root () const
return the root node by traversing parents until no more parent is available
void set_parent (node_ptr _parent)
set a new parent node
node_ptr get_node ()
cast upward to node
const_node_ptr get_node_const ()
cast upward to const node
std::string get_type_name () const
overload to return the type name of this object
Public Member Functions inherited from cgv::base::named
named (const std::string &name="")
construct from name
const std::string & get_name () const
return the parent node
void set_name (const std::string &_name)
set a new parent node
named_ptr get_named ()
cast upward to named
const_named_ptr get_named_const ()
cast upward to const named
Public Member Functions inherited from cgv::base::base
virtual std::string get_default_options () const
overload to provide default options for registration
std::string get_name_or_type_name () const
determine name of instance by checking cgv::base::named interface and in failure fallback to get_type_name()
virtual void on_register ()
overload to handle register events that is sent after the instance has been registered
virtual void unregister ()
overload to handle unregistration of instances
virtual bool on_exit_request ()
overload to handle the appication exit request, return true if exiting is allowed and false otherwise
virtual void stream_stats (std::ostream &)
overload to show the content of this object
virtual data::ref_ptr< const named, true > get_named_const () const
perform downcast to const named
virtual data::ref_ptr< const node, true > get_node_const () const
perform downcast to const node
virtual data::ref_ptr< const group, true > get_group_const () const
perform downcast to const group
template<class T >
data::ref_ptr< T, true > cast ()
cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
data::ref_ptr< const T, true > cast_const ()
const cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
T * get_interface ()
use dynamic type cast to check for the given interface
template<class T >
const T * get_const_interface () const
use dynamic type cast to check for the given interface
virtual void update ()
this virtual update allows for example to ask a view to update the viewed value. The default implementation is empty.
virtual void * get_user_data () const
this virtual method allows to pass application specific data for internal purposes
virtual bool self_reflect (cgv::reflect::reflection_handler &)
used for simple self reflection
virtual std::string get_property_declarations ()
return a semicolon separated list of property declarations
virtual bool set_void (const std::string &property, const std::string &value_type, const void *value_ptr)
abstract interface for the setter of a dynamic property.
virtual bool get_void (const std::string &property, const std::string &value_type, void *value_ptr)
abstract interface for the getter of a dynamic property.
virtual bool call_void (const std::string &method, const std::vector< std::string > &param_value_types, const std::vector< const void * > &param_value_ptrs, const std::string &result_type="", void *result_value_ptr=0)
abstract interface to call an action
void set (const std::string &property, const char *value)
specialization of set method to support const char* as strings
template<typename T >
void set (const std::string &property, const T &value)
set a property of the element to the given value and perform standard conversions if necessary.
template<typename T >
T get (const std::string &property)
query a property of the element and perform standard conversions if necessary.
void multi_set (const std::string &property_assignments, bool report_error=true)
set several properties
bool is_property (const std::string &property_name, std::string *type_name=0)
check if the given name specifies a property.
void * find_member_ptr (const std::string &property_name, std::string *type_name=0)
find a member pointer by name.
Public Member Functions inherited from cgv::data::ref_counted
int get_ref_count () const
read access to current count
Public Member Functions inherited from cgv::gui::provider
void remove_element (base_ptr)
remove a single element from the gui
void remove_all_elements ()
this method removes all elements from the gui and can be used in a method that rebuilds the complete gui
base_ptr find_element (const std::string &name)
find a gui element by name in the current group, return empty pointer if not found
template<typename T >
data::ref_ptr< view< T > > find_view (const T &value, int *idx_ptr=0)
find a view of a given class member
template<typename T >
data::ref_ptr< control< T > > find_control (T &value, int *idx_ptr=0)
find a control of a given class member
control_ptr find_control_void (void *value_ptr, int *idx_ptr)
access to control of untyped member pointer
view_ptr find_view_void (void *value_ptr, int *idx_ptr)
access to view of untyped member pointer
template<typename T >
void set_control_property (T &value, const std::string &property_name, const std::string &property_value)
Set the property value of all controls of a given class member.
gui_group_ptr get_parent_group () const
use the parent group to append to be managed elements that should be destroyed in a post_recreate_gui event
view_ptr add_view_void (const std::string &label, const void *value_ptr, const std::string &value_type, const std::string &gui_type, const std::string &options, const std::string &align)
add a newly created view to the group
control_ptr add_control_void (const std::string &label, void *value_ptr, abst_control_provider *acp, const std::string &value_type, const std::string &gui_type, const std::string &options, const std::string &align, void *user_data)
add a newly created control to the group
provider ()
default construction
~provider ()
ensure to remove posted recreation callbacks
virtual std::string get_gui_name () const
Derive a name for this instance that can be used in the gui as heading.
virtual std::string get_parent_type () const
Returns the group type that should be used by the class embedding the gui of the provider.
virtual bool ensure_selected_in_tab_group_parent ()
ensure that my UI is selected in the parent group in case this is a tab group, otherwise return false
virtual void update_member (void *member_ptr)
call this to update all views and controls of a member
virtual void update_all_members ()
call this to update all views and controls of all member
virtual std::string get_menu_path () const
return a path in the main menu to select the gui
virtual shortcut get_shortcut () const
return a shortcut to activate the gui without menu navigation
virtual void create_gui ()=0
you must overload this for gui creation
virtual void recreate_gui ()
Recreate the gui of this instance right now.
virtual void post_recreate_gui ()
delayed recreation of gui
void align (const std::string &_align)
send pure alignment information
std::string concat_enum_def (const std::vector< std::string > &names, const std::string &additional_first_name="", const std::string &additional_last_name="")
add a new group to the given parent group, not supported yet
gui_group_ptr add_object_gui (base_ptr object, const std::string &label, const std::string &group_type, const std::string &options, const std::string &align)
void integrate_object_gui (base_ptr object)
call this in create_gui() function to integrate gui of another provider object by setting the parent group and parent provider of the other object
void inline_object_gui (base_ptr object)
integrate (if not explicitly done before) and inline the gui of another object that must be derived from provider
gui_group_ptr add_group (const std::string &label, const std::string &group_type, const std::string &options="", const std::string &align="\n")
add a newly created subgroup to the group
base_ptr add_decorator (const std::string &label, const std::string &decorator_type, const std::string &options="", const std::string &align="\n")
add a newly created decorator to the group
button_ptr add_button (const std::string &label, const std::string &options="", const std::string &align="\n")
use the current gui driver to append a new button with the given label
template<typename T >
data::ref_ptr< view< T > > add_view (const std::string &label, const T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
use this to add a new view to the gui with a given value type, gui type and init options
template<typename T >
data::ref_ptr< control< T > > add_control (const std::string &label, T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
use this to add a new control to the gui with a given value type, gui type and init options
template<typename T >
data::ref_ptr< control< T > > add_control (const std::string &label, control_provider< T > *provider, const std::string &gui_type="", const std::string &options="", const std::string &align="\n", void *user_data=0)
use this to add a new control to the gui, where the control is implemented with a control provider class
template<typename T >
data::ref_ptr< control< T > > add_member_control (cgv::base::base *base_ptr, const std::string &label, T &value, const std::string &gui_type="", const std::string &options="", const std::string &align="\n")
add control with callback to cgv::base::on_set method on cgv::gui::control::value_change
bool add_tree_node (const std::string &label, bool &toggle, int level, const std::string &a="\n", gui_group_ptr ggp=gui_group_ptr())
add a collapsable node to the gui (deprecated)
template<typename T >
bool begin_tree_node (const std::string &label, const T &value, bool initial_visibility=false, const std::string &options="", gui_group_ptr ggp=gui_group_ptr())
Begin a sub tree of a tree structured gui.
template<typename T >
void end_tree_node (const T &value)
template specialization that allows to specify value reference plus node_instance by using the result of the function with_instance(value,idx) for the value argument finish a sub tree begun with begin_tree_node
template<typename T >
bool is_tree_node_visible (const T &value) const
return whether the sub tree attached to a value is visible
template<typename T >
void set_tree_node_visibility (const T &value, bool is_visible)
set the visibility status of sub tree attached to a value. This calls the post_recreate method if needed.
bool begin_tree_node_void (const std::string &label, const void *value_ptr, int index=-1, bool initial_visibility=false, const std::string &options="", gui_group_ptr ggp=gui_group_ptr())
void version of the templated functions
void end_tree_node_void (const void *value_ptr, int index=-1)
bool is_tree_node_visible_void (const void *value_ptr, int index) const
void set_tree_node_visibility_void (const void *value_ptr, int index, bool is_visible)
template<typename T >
bool add_gui (const std::string &label, T &value, const std::string &gui_type="", const std::string &options="")
Add a composed gui of the given gui_type for the given value.
Public Member Functions inherited from cgv::gui::event_handler
event_handler ()
default construction
bool grab_focus ()
grab the focus in all parent nodes
virtual void stream_help (std::ostream &os)=0
overload to stream help information to the given output stream
bool add_key_control (const std::string &property, const std::string &options, cgv::base::group_ptr group=cgv::base::group_ptr())
add a key control for the given property with the given options.
Public Member Functions inherited from cgv::base::traverse_policy
traverse_policy (int _policy=TP_ALL+TP_STOP_ON_SUCCESS, bool _active=true, int _focus=-1)
construct default traverse policy that visits everything
int get_policy () const
return the policy without the stop on success flag
bool stop_on_success () const
return whether to stop on success
bool stop_on_failure () const
return whether to stop on failure
void set_policy (int _policy)
set a new policy, always add stop on success flag if needed
int get_focused_child () const
return the focused child or -1 if none is focused
void set_focused_child (int _focused_child)
set the focused child
bool get_active () const
return whether the current node is active
void set_active (bool _active)
set the active flag of the current node
Protected Attributes
cgv::render::view * view_ptr
Stores a pointer to the base view.
std::vector< overlay_ptr > overlays
Stores a list of all overlays registered as children of this application plugin.
overlay_ptr last_blocking_overlay_ptr
Stores a pointer to the overlay that handled the previous event.
overlay_ptr blocking_overlay_ptr
Stores a pointer to the overlay that handles the current event.
Protected Attributes inherited from cgv::base::group
std::vector< base_ptr > children
store a list of children
Protected Attributes inherited from cgv::base::node
node_ptr parent
store a pointer to the parent node
Protected Attributes inherited from cgv::base::named
std::string name
store the name as a string
Protected Attributes inherited from cgv::gui::provider
gui_group_ptr parent_group
driver specific handle for the group gui element managing the gui built in the provider
provider * parent_provider
Protected Attributes inherited from cgv::base::traverse_policy
TraversePolicy policy
bool active
int focus
Additional Inherited Members
Static Public Member Functions inherited from cgv::gui::provider
template<typename T >
static bool & ref_tree_node_visible_flag (const T &value)
return a reference to the boolean flag, that tells whether the tree node for the passed value is visible
static bool & ref_tree_node_visible_flag_void (const void *value_ptr, int index=-1)
Protected Member Functions inherited from cgv::base::group
void link (base_ptr b)
check if the base class is a node and set the parent of the node
void unlink (base_ptr b)
check if the base class is a node and clear the parent of the node
Protected Member Functions inherited from cgv::base::base
virtual ~base ()
make destructor virtual and not accessible from outside
Protected Member Functions inherited from cgv::data::ref_counted
ref_counted ()
constructor initializes the count to 0
void set_ref_count (int c) const
write access is also const to allow ref counted pointers to const instances
Protected Member Functions inherited from cgv::gui::provider
void set_parent (gui_group_ptr)
the gui window sets the parent group through this method
void update_parent ()
update the parent group
virtual void on_select ()
called by selection_change_cb whenever the gui of this provider is selected
virtual void on_deselect ()
called by selection_change_cb whenever the gui of this provider is deselected
virtual void selection_change_cb (cgv::base::base_ptr new_child, bool selected)
this is called by the gui group when the selection changes
Static Protected Member Functions inherited from cgv::base::base
template<class T >
static data::ref_ptr< T, true > cast_dynamic (base *b)
use dynamic cast for upcast to given class
Detailed Description
Abstract base class for application plugins that provides capability to handle overlays, GUI interaction and event handling.
For concrete class implementations see generic_application_plugin and application_plugin.
Definition at line 25 of file application_plugin.h.
Constructor & Destructor Documentation
application_plugin_base()
cgv::app::application_plugin_base::application_plugin_base (const std::string & name)
Provides a base constructor that calls the base class constructor of group.
Parameters
name the name of this node.
Definition at line 9 of file application_plugin.cxx.
References blocking_overlay_ptr, last_blocking_overlay_ptr, and view_ptr.
Member Function Documentation
handle()
bool cgv::app::application_plugin_base::handle (cgv::gui::event & e) final virtual
Final implementation of event_handler::handle() to support event handling of registered overlays.
Implement handle_event to handle any events that are passed to the instance of this class.
Parameters
e the event to handle.
Returns
true if the event was handled and stopped here, false otherwise.
Implements cgv::gui::event_handler.
Definition at line 16 of file application_plugin.cxx.
References blocking_overlay_ptr, cgv::gui::EF_DND, cgv::gui::EID_MOUSE, cgv::gui::mouse_event::get_action(), cgv::gui::event::get_flags(), cgv::gui::event::get_kind(), cgv::gui::mouse_event::get_x(), cgv::gui::mouse_event::get_y(), handle_event(), last_blocking_overlay_ptr, cgv::gui::MA_ENTER, cgv::gui::MA_LEAVE, cgv::gui::MA_MOVE, cgv::gui::MA_PRESS, cgv::gui::MA_RELEASE, cgv::gui::MA_WHEEL, overlays, and cgv::gui::mouse_event::set_action().
handle_event()
virtual bool cgv::app::application_plugin_base::handle_event (cgv::gui::event & e) pure virtual
Implement this method to handle any events not blocked by an registered overlay.
Parameters
e the event to handle.
Returns
true if the event was handled and stopped here, false otherwise.
Referenced by handle().
handle_member_change()
virtual void cgv::app::application_plugin_base::handle_member_change (const cgv::utils::pointer_test & m) pure virtual
Implement this method to handle member changes from GUI interactions or manual calls to on_set() provided through a convenient evaluation interface.
Parameters
m the pointer_test interface used to conveniently evaluate the affected member.
Implemented in cgv::app::generic_application_plugin< base_drawable >, and cgv::app::generic_application_plugin< cgv::render::drawable >.
initialize_view_ptr()
virtual bool cgv::app::application_plugin_base::initialize_view_ptr () pure virtual
Implement this method to initialize the view pointer to a valid value and return whether this was successfull.
Implemented in cgv::app::generic_application_plugin< base_drawable >, and cgv::app::generic_application_plugin< cgv::render::drawable >.
on_set()
virtual void cgv::app::application_plugin_base::on_set (void * member_ptr) pure virtual
Implement this method to handle member changes from GUI interactions or manual calls to on_set().
Parameters
member_ptr the pointer to the affected member.
Reimplemented from cgv::base::base.
Implemented in cgv::app::generic_application_plugin< base_drawable >, and cgv::app::generic_application_plugin< cgv::render::drawable >.
register_overlay()
template<class T > cgv::data::ref_ptr< T > cgv::app::application_plugin_base::register_overlay (const std::string & name) inline
Registers an overlay instance as a child of this group.
Template Parameters
T the overlay class type; must inherit from overlay.
Parameters
name the name of the overlay instance.
Returns
a ref_ptr to the registered overlay instance.
Definition at line 57 of file application_plugin.h.
References cgv::base::group::append_child().
unregister_overlay()
unsigned cgv::app::application_plugin_base::unregister_overlay (overlay_ptr ptr) inline
Unregisters an overlay instance that is a child of this group.
Parameters
ptr the overlay pointer.
name the name of the overlay instance.
Returns
the number of removed children.
Definition at line 71 of file application_plugin.h.
References cgv::base::group::remove_child().
Member Data Documentation
blocking_overlay_ptr
overlay_ptr cgv::app::application_plugin_base::blocking_overlay_ptr protected
Stores a pointer to the overlay that handles the current event.
Definition at line 42 of file application_plugin.h.
Referenced by application_plugin_base(), and handle().
last_blocking_overlay_ptr
overlay_ptr cgv::app::application_plugin_base::last_blocking_overlay_ptr protected
Stores a pointer to the overlay that handled the previous event.
Definition at line 39 of file application_plugin.h.
Referenced by application_plugin_base(), and handle().
overlays
std::vector<overlay_ptr> cgv::app::application_plugin_base::overlays protected
Stores a list of all overlays registered as children of this application plugin.
Definition at line 36 of file application_plugin.h.
Referenced by handle().
view_ptr
cgv::render::view* cgv::app::application_plugin_base::view_ptr protected
Stores a pointer to the base view.
If a specific view is required in an implementation, it is advised to declare a new member with the specific view name in the actual implementation of this class.
Definition at line 33 of file application_plugin.h.
Referenced by application_plugin_base(), and cgv::app::generic_application_plugin< base_drawable >::initialize_view_ptr().
The documentation for this class was generated from the following files:
libs/cgv_app/application_plugin.h
libs/cgv_app/application_plugin.cxx