cgv: cgv::render::group_renderer Class Reference
cgv::render::group_renderer Class Reference
abstract renderer class that provides functionality for grouping primitives
#include <group_renderer.h>
Public Member Functions
void enable_attribute_array_manager (const context &ctx, attribute_array_manager &aam)
call this before setting attribute arrays to manage attribute array in given manager
void disable_attribute_array_manager (const context &ctx, attribute_array_manager &aam)
call this after last render/draw call to ensure that no other users of renderer change attribute arrays of given manager
bool validate_attributes (const context &ctx) const
check additionally the group attributes
bool enable (context &ctx)
overload to activate group style
bool disable (context &ctx)
disable renderer
void set_group_index_array (const context &ctx, const std::vector< unsigned > &group_indices)
method to set the group index attribute
void set_group_index_array (const context &ctx, const unsigned *group_indices, size_t nr_elements)
method to set the group index attribute
void set_group_index_array (const context &ctx, type_descriptor element_type, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
method to set the group index attribute from a vertex buffer object, the element type must be given as explicit template parameter
template<typename T >
void set_group_index_array (const context &ctx, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the group index color attribute from a vertex buffer object, the element type must be given as explicit template parameter
void remove_group_index_array (const context &ctx)
remove the group index attribute
template<typename T >
void set_group_colors (const context &ctx, const std::vector< T > &colors)
template method to set the group colors from a vector of colors of type T
template<typename T >
void set_group_colors (const context &ctx, const T *colors, size_t nr_elements)
template method to set the group colors from a vector of colors of type T
template<typename T >
void set_group_translations (const context &ctx, const std::vector< T > &group_translations)
template method to set the group translations from a vector of vectors of type T, which should have 3 components
template<typename T >
void set_group_translations (const context &ctx, const T *group_translations, size_t nr_elements)
template method to set the group translations from a vector of vectors of type T, which should have 3 components
template<typename T >
void set_group_rotations (const context &ctx, const std::vector< T > &group_rotations)
template method to set the group rotation from a vector of quaternions of type T, which should have 4 components
template<typename T >
void set_group_rotations (const context &ctx, const T *group_rotations, size_t nr_elements)
template method to set the group rotation from a vector of quaternions of type T, which should have 4 components
Public Member Functions inherited from cgv::render::renderer
shader_compile_options & ref_shader_options ()
access to shader program compile options to update settings not handled by render style
shader_program & ref_prog ()
derived renderer classes have access to shader program
void set_prog (shader_program &one_shot_prog)
set external shader program up to next call to disable() or render()
void draw_impl (context &ctx, PrimitiveType pt, size_t start, size_t count, bool use_strips=false, bool use_adjacency=false, uint32_t strip_restart_index=-1)
default implementation of draw method with support for indexed rendering and different primitive types
void draw_impl_instanced (context &ctx, PrimitiveType type, size_t start, size_t count, size_t instance_count, bool use_strips=false, bool use_adjacency=false, uint32_t strip_restart_index=-1)
default implementation of instanced draw method with support for indexed rendering and different primitive types
renderer ()
construct and init attribute tracking flags
virtual ~renderer ()
destructor deletes default renderer style
void manage_singleton (context &ctx, const std::string &renderer_name, int &ref_count, int ref_count_change)
used by derived classes to manage singletons
virtual void set_attribute_array_manager (const context &ctx, attribute_array_manager *_aam_ptr=0)
this function is deprecated, please use enable_attribute_array_manager() and disable_attribute_manager() instead
void set_render_style (const render_style &rs)
reference given render style
bool build_program (context &ctx, shader_program &prog, const render_style &rs)
build shader program for specific render style
virtual bool init (context &ctx)
call init() once before using renderer
template<typename T >
void set_position (const context &ctx, const T &position)
templated method to set the position attribute from a single position of type T
template<typename T >
void set_position_array (const context &ctx, const std::vector< T > &positions)
templated method to set the position attribute from a vector of positions of type T
template<typename T >
void set_position_array (const context &ctx, const T *positions, size_t nr_elements, unsigned stride_in_bytes=0)
templated method to set the position attribute from a vector of positions of type T
void set_position_array (const context &ctx, type_descriptor element_type, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes)
method to set the position attribute from a vertex buffer object
template<typename T >
void set_position_array (const context &ctx, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the position attribute from a vertex buffer object, the element type must be given as explicit template parameter
void remove_position_array (const context &ctx)
remove the position attribute
template<typename T >
void set_color (const context &ctx, const T &color)
templated method to set the color attribute from a single color of type T
template<typename T >
void set_color_array (const context &ctx, const std::vector< T > &colors)
template method to set the color attribute from a vector of colors of type T
template<typename T >
void set_color_array (const context &ctx, const T *colors, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the color attribute from a vector of colors of type T
void set_color_array (const context &ctx, type_descriptor element_type, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
method to set the color attribute from a vertex buffer object, the element type must be given as explicit template parameter
template<typename T >
void set_color_array (const context &ctx, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes=0)
template method to set the color attribute from a vertex buffer object, the element type must be given as explicit template parameter
void remove_color_array (const context &ctx)
remove the color attribute
template<typename T >
bool set_indices (const context &ctx, const std::vector< T > &indices, bool keep_on_cpu=false)
Set the indices for indexed rendering from a vector.
template<typename T >
bool set_indices (const context &ctx, const T *indices, size_t nr_indices, bool keep_on_cpu=false)
Set the indices for indexed rendering from an array given as a pointer.
template<typename T >
bool set_indices (const context &ctx, const vertex_buffer &vbo, size_t count)
Set the indices for indexed rendering from a GPU buffer.
bool has_indices () const
return whether indices have been defined
void remove_indices (const context &ctx)
remove previously set indices
const vertex_buffer * get_vertex_buffer_ptr (const context &ctx, const attribute_array_manager &aam, const std::string &attr_name)
const vertex_buffer * get_index_buffer_ptr (const attribute_array_manager &aam)
bool validate_and_enable (context &ctx)
validate attributes and if successful, enable renderer
virtual void draw (context &ctx, size_t start, size_t count, bool use_strips=false, bool use_adjacency=false, uint32_t strip_restart_index=-1)
Draw a range of vertices or indexed elements.
virtual bool render (context &ctx, size_t start, size_t count, bool use_strips=false, bool use_adjacency=false, uint32_t strip_restart_index=-1)
Convenience function that draws vertex or indexed element with this renderer.
virtual void clear (const context &ctx)
the clear function destructs the shader program
Protected Attributes
bool has_group_indices = false
bool has_group_colors = false
bool has_group_translations = false
bool has_group_rotations = false
Protected Attributes inherited from cgv::render::renderer
bool has_colors = false
track whether color attribute is defined
bool has_positions = false
track whether position attribute is defined
Additional Inherited Members
Protected Member Functions inherited from cgv::render::renderer
bool has_aam () const
check for attribute array manager
bool has_attribute (const context &ctx, const std::string &name)
check for attribute
virtual render_style * create_render_style () const =0
implement this method to create a default render style
const render_style * get_style_ptr () const
access to render style
bool attributes_persist () const
return whether attributes persist after a call to disable
virtual void update_shader_program_options (shader_compile_options &options) const
overload to update the shader program compile options based on the current render style; only called if internal shader program is used
virtual bool build_shader_program (context &ctx, shader_program &prog, const shader_compile_options &options) const
overload to change default behaviour and build a custom shader program based on the passed options
virtual std::string get_default_prog_name () const =0
implement this method to return the name of the default shader program; return an empty string if the renderer handles program creation on its own
template<typename T >
const T & get_style () const
access to style
int get_prog_attribute_location (const context &ctx, const std::string &name, bool error_check=true)
template<typename T >
bool set_attribute_array (const context &ctx, const std::string &name, const T &array)
template<typename T >
bool set_attribute_array (const context &ctx, const std::string &name, const T *array_ptr, size_t nr_elements, unsigned stride)
bool set_attribute_array (const context &ctx, const std::string &name, type_descriptor element_type, const vertex_buffer &vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes)
template<typename C , typename T >
bool set_composed_attribute_array (const context &ctx, const std::string &name, const C *array_ptr, size_t nr_elements, const T &elem)
in case that several attributes are stored interleaved, call this function for the first and ref_composed_attribute_array() for all others
template<typename C , typename T >
bool ref_composed_attribute_array (const context &ctx, const std::string &name, const std::string &name_ref, const C *array_ptr, size_t nr_elements, const T &elem)
in case that several attributes are stored interleaved, call set_composed_attribute_array() for the first and this function for all others
bool remove_attribute_array (const context &ctx, const std::string &name)
Detailed Description
abstract renderer class that provides functionality for grouping primitives
Definition at line 23 of file group_renderer.h.
Member Function Documentation
disable()
bool cgv::render::group_renderer::disable (context & ctx) virtual
disable renderer
Reimplemented from cgv::render::renderer.
Reimplemented in cgv::render::point_renderer, cgv::render::spline_tube_renderer, cgv::render::surface_renderer, cgv::render::surfel_renderer, cgv::render::line_renderer, cgv::render::rectangle_renderer, and cgv::render::sphere_renderer.
Definition at line 83 of file group_renderer.cxx.
References cgv::render::renderer::attributes_persist(), and cgv::render::renderer::disable().
Referenced by cgv::render::point_renderer::disable(), cgv::render::surface_renderer::disable(), and cgv::render::line_renderer::disable().
disable_attribute_array_manager()
void cgv::render::group_renderer::disable_attribute_array_manager (const context & ctx, attribute_array_manager & aam) virtual
call this after last render/draw call to ensure that no other users of renderer change attribute arrays of given manager
Reimplemented from cgv::render::renderer.
Reimplemented in cgv::render::point_renderer, cgv::render::spline_tube_renderer, cgv::render::surface_renderer, cgv::render::surfel_renderer, cgv::render::line_renderer, cgv::render::rectangle_renderer, and cgv::render::sphere_renderer.
Definition at line 16 of file group_renderer.cxx.
References cgv::render::renderer::disable_attribute_array_manager().
Referenced by cgv::render::point_renderer::disable_attribute_array_manager(), cgv::render::surface_renderer::disable_attribute_array_manager(), and cgv::render::line_renderer::disable_attribute_array_manager().
enable()
bool cgv::render::group_renderer::enable (context & ctx) virtual
overload to activate group style
Reimplemented from cgv::render::renderer.
Reimplemented in cgv::render::point_renderer, cgv::render::spline_tube_renderer, cgv::render::surface_renderer, cgv::render::surfel_renderer, cgv::render::line_renderer, cgv::render::normal_renderer, cgv::render::rectangle_renderer, and cgv::render::sphere_renderer.
Definition at line 71 of file group_renderer.cxx.
References cgv::render::renderer::enable(), cgv::render::renderer::ref_prog(), cgv::render::shader_program::set_uniform(), cgv::render::group_render_style::use_group_color, and cgv::render::group_render_style::use_group_transformation.
Referenced by cgv::render::point_renderer::enable(), cgv::render::surface_renderer::enable(), and cgv::render::line_renderer::enable().
enable_attribute_array_manager()
void cgv::render::group_renderer::enable_attribute_array_manager (const context & ctx, attribute_array_manager & aam) virtual
call this before setting attribute arrays to manage attribute array in given manager
Reimplemented from cgv::render::renderer.
Reimplemented in cgv::render::point_renderer, cgv::render::spline_tube_renderer, cgv::render::surface_renderer, cgv::render::surfel_renderer, cgv::render::line_renderer, cgv::render::rectangle_renderer, and cgv::render::sphere_renderer.
Definition at line 9 of file group_renderer.cxx.
References cgv::render::renderer::enable_attribute_array_manager(), and cgv::render::renderer::has_attribute().
Referenced by cgv::render::point_renderer::enable_attribute_array_manager(), cgv::render::surface_renderer::enable_attribute_array_manager(), and cgv::render::line_renderer::enable_attribute_array_manager().
remove_group_index_array()
void cgv::render::group_renderer::remove_group_index_array (const context & ctx)
remove the group index attribute
Definition at line 39 of file group_renderer.cxx.
set_group_colors() [1/2]
template<typename T > void cgv::render::group_renderer::set_group_colors (const context & ctx, const std::vector< T > & colors) inline
template method to set the group colors from a vector of colors of type T
Definition at line 54 of file group_renderer.h.
set_group_colors() [2/2]
template<typename T > void cgv::render::group_renderer::set_group_colors (const context & ctx, const T * colors, size_t nr_elements) inline
template method to set the group colors from a vector of colors of type T
Definition at line 57 of file group_renderer.h.
set_group_index_array() [1/4]
void cgv::render::group_renderer::set_group_index_array (const context & ctx, const std::vector< unsigned > & group_indices)
method to set the group index attribute
Definition at line 22 of file group_renderer.cxx.
set_group_index_array() [2/4]
void cgv::render::group_renderer::set_group_index_array (const context & ctx, const unsigned * group_indices, size_t nr_elements)
method to set the group index attribute
Definition at line 28 of file group_renderer.cxx.
set_group_index_array() [3/4]
template<typename T > void cgv::render::group_renderer::set_group_index_array (const context & ctx, const vertex_buffer & vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes = 0) inline
template method to set the group index color attribute from a vertex buffer object, the element type must be given as explicit template parameter
Definition at line 49 of file group_renderer.h.
References set_group_index_array().
Referenced by set_group_index_array().
set_group_index_array() [4/4]
void cgv::render::group_renderer::set_group_index_array (const context & ctx, type_descriptor element_type, const vertex_buffer & vbo, size_t offset_in_bytes, size_t nr_elements, unsigned stride_in_bytes = 0)
method to set the group index attribute from a vertex buffer object, the element type must be given as explicit template parameter
template method to set the group index attribute from a vertex buffer object, the element type must be given as explicit template parameter
Definition at line 34 of file group_renderer.cxx.
set_group_rotations() [1/2]
template<typename T > void cgv::render::group_renderer::set_group_rotations (const context & ctx, const std::vector< T > & group_rotations) inline
template method to set the group rotation from a vector of quaternions of type T, which should have 4 components
Definition at line 66 of file group_renderer.h.
set_group_rotations() [2/2]
template<typename T > void cgv::render::group_renderer::set_group_rotations (const context & ctx, const T * group_rotations, size_t nr_elements) inline
template method to set the group rotation from a vector of quaternions of type T, which should have 4 components
Definition at line 69 of file group_renderer.h.
set_group_translations() [1/2]
template<typename T > void cgv::render::group_renderer::set_group_translations (const context & ctx, const std::vector< T > & group_translations) inline
template method to set the group translations from a vector of vectors of type T, which should have 3 components
Definition at line 60 of file group_renderer.h.
set_group_translations() [2/2]
template<typename T > void cgv::render::group_renderer::set_group_translations (const context & ctx, const T * group_translations, size_t nr_elements) inline
template method to set the group translations from a vector of vectors of type T, which should have 3 components
Definition at line 63 of file group_renderer.h.
validate_attributes()
bool cgv::render::group_renderer::validate_attributes (const context & ctx) const virtual
check additionally the group attributes
Reimplemented from cgv::render::renderer.
Reimplemented in cgv::render::point_renderer, cgv::render::spline_tube_renderer, cgv::render::surfel_renderer, cgv::render::normal_renderer, cgv::render::rectangle_renderer, and cgv::render::sphere_renderer.
Definition at line 43 of file group_renderer.cxx.
References cgv::render::context::error(), cgv::render::renderer::get_style_ptr(), cgv::render::group_render_style::use_group_color, cgv::render::group_render_style::use_group_transformation, and cgv::render::renderer::validate_attributes().
Referenced by cgv::render::ellipsoid_renderer::validate_attributes(), cgv::render::point_renderer::validate_attributes(), cgv::render::spline_tube_renderer::validate_attributes(), cgv::render::surfel_renderer::validate_attributes(), cgv::render::arrow_renderer::validate_attributes(), cgv::render::cone_renderer::validate_attributes(), cgv::render::normal_renderer::validate_attributes(), cgv::render::rectangle_renderer::validate_attributes(), and cgv::render::sphere_renderer::validate_attributes().
Member Data Documentation
has_group_colors
bool cgv::render::group_renderer::has_group_colors = false protected
Definition at line 27 of file group_renderer.h.
has_group_indices
bool cgv::render::group_renderer::has_group_indices = false protected
Definition at line 26 of file group_renderer.h.
has_group_rotations
bool cgv::render::group_renderer::has_group_rotations = false protected
Definition at line 29 of file group_renderer.h.
has_group_translations
bool cgv::render::group_renderer::has_group_translations = false protected
Definition at line 28 of file group_renderer.h.
The documentation for this class was generated from the following files:
libs/cgv_gl/group_renderer.h
libs/cgv_gl/group_renderer.cxx