cgv: cgv::render::render_component Class Reference
cgv::render::render_component Class Reference
base interface for all render components
#include <context.h>
Public Member Functions
render_component ()
initialize members
virtual bool is_created () const
return whether component has been created
void put_id_void (void *ptr) const
copy the rendering api specific id the component to the memory location of the given pointer.
template<typename T >
void put_id (T &id) const
cast the refence to rendering api specific representation of component id to the specified type
Public Attributes
void * handle
void * internal_format
void * user_data
const context * ctx_ptr
keep pointer to my context
std::string last_error
a string that contains the last error
Detailed Description
base interface for all render components
Definition at line 309 of file context.h.
Constructor & Destructor Documentation
render_component()
cgv::render::render_component::render_component ()
initialize members
Definition at line 2056 of file context.cxx.
References ctx_ptr.
Member Function Documentation
is_created()
bool cgv::render::render_component::is_created () const virtual
return whether component has been created
Reimplemented in cgv::render::render_buffer, and cgv::render::vertex_buffer.
Definition at line 2065 of file context.cxx.
Referenced by cgv::render::shader_program::build_dir(), cgv::render::shader_program::build_files(), cgv::render::shader_program::build_program(), cgv::render::texture::copy(), cgv::render::texture::create(), cgv::render::texture::create(), cgv::render::gl::gl_transparent_renderer::create_and_attach_texture(), cgv::render::texture::create_from_buffer(), cgv::render::texture::create_mipmaps(), vr_test::draw(), cgv::render::attribute_array_binding::enable(), cgv::render::shader_program::enable(), cgv::render::renderer::enable(), cgv::render::managed_frame_buffer::ensure(), vr_test::finish_draw(), cgv::render::volume_renderer::init(), vr_test::init_frame(), cgv::render::a_buffer::init_frame(), cgv::render::gl::gl_depth_peeler::init_frame(), cgv::render::gl::gl_transparent_renderer::init_frame(), cgv::render::volume_renderer::init_noise_texture(), cgv::render::texture::replace(), cgv::render::texture::replace(), cgv::render::texture::replace(), cgv::render::texture::replace_from_buffer(), cgv::render::texture::replace_from_buffer(), cgv::render::texture::write_to_file(), and cgv::render::attribute_array_manager::~attribute_array_manager().
put_id()
template<typename T > void cgv::render::render_component::put_id (T & id) const inline
cast the refence to rendering api specific representation of component id to the specified type
Definition at line 328 of file context.h.
Referenced by cgv::render::gl::print_program_ressources().
put_id_void()
void cgv::render::render_component::put_id_void (void * ptr) const
copy the rendering api specific id the component to the memory location of the given pointer.
For opengl this the passed pointer should be of type GLint or GLuint.
Definition at line 2071 of file context.cxx.
References ctx_ptr.
Member Data Documentation
ctx_ptr
const context* cgv::render::render_component::ctx_ptr
keep pointer to my context
Definition at line 316 of file context.h.
Referenced by cgv::render::shader_program::create(), cgv::render::frame_buffer::create(), cgv::render::render_buffer::create(), put_id_void(), render_component(), cgv::render::shader_code::set_code(), cgv::render::attribute_array_binding::~attribute_array_binding(), cgv::render::attribute_array_manager::~attribute_array_manager(), cgv::render::frame_buffer::~frame_buffer(), cgv::render::render_buffer::~render_buffer(), cgv::render::shader_code::~shader_code(), cgv::render::shader_program::~shader_program(), cgv::render::texture::~texture(), and cgv::render::vertex_buffer::~vertex_buffer().
handle
void* cgv::render::render_component::handle
Definition at line 312 of file context.h.
internal_format
void* cgv::render::render_component::internal_format
Definition at line 313 of file context.h.
last_error
std::string cgv::render::render_component::last_error mutable
a string that contains the last error
Definition at line 318 of file context.h.
Referenced by cgv::render::shader_program::attach_code(), cgv::render::shader_program::attach_code(), cgv::render::shader_program::attach_file(), cgv::render::shader_program::attach_files(), cgv::render::shader_program::attach_program(), cgv::render::texture::bind_as_image(), cgv::render::shader_program::build_program(), cgv::render::texture::copy(), cgv::render::texture::create_from_image(), cgv::render::texture::create_mipmaps(), cgv::render::shader_program::detach_code(), cgv::render::texture::enable(), cgv::render::shader_code::get_last_error(), cgv::render::shader_program::link(), cgv::render::shader_code::read_and_compile(), cgv::render::shader_code::read_code(), cgv::render::shader_code::read_code_file(), cgv::render::texture::replace(), cgv::render::texture::replace(), cgv::render::texture::replace(), cgv::render::texture::replace_from_buffer(), and cgv::render::texture::replace_from_buffer().
user_data
void* cgv::render::render_component::user_data
Definition at line 314 of file context.h.
The documentation for this class was generated from the following files:
cgv/render/context.h
cgv/render/context.cxx