cgv: cgv::gui::trigger Class Reference
cgv::gui::trigger Class Reference
a trigger provides callbacks after a programmable time delay
#include <trigger.h>
Public Member Functions
trigger ()
default construction
bool is_scheduled () const
return whether a trigger is scheduled
bool schedule_one_shot (double delay)
schedule a trigger event in delay seconds, return whether this was successful
bool schedule_recuring (double delay)
start a recuring trigger with the given delay in seconds, return whether this was successful
double get_delay () const
return the delay used for scheduling the last time
bool is_recuring () const
return whether this is a recuring trigger
void stop ()
stop a recuring trigger
Static Public Member Functions
static double get_current_time ()
return the current time
Public Attributes
signal::signal< double, double > shoot
the shoot signal is called when the trigger is pulled and takes the current time and delay as argument
Detailed Description
a trigger provides callbacks after a programmable time delay
Definition at line 13 of file trigger.h.
Member Function Documentation
schedule_one_shot()
bool cgv::gui::trigger::schedule_one_shot (double delay)
schedule a trigger event in delay seconds, return whether this was successful
schedule a trigger event in delay seconds
Definition at line 23 of file trigger.cxx.
References cgv::gui::get_trigger_server().
schedule_recuring()
bool cgv::gui::trigger::schedule_recuring (double delay)
start a recuring trigger with the given delay in seconds, return whether this was successful
start a recuring trigger with the given delay in seconds
Definition at line 36 of file trigger.cxx.
References cgv::gui::get_trigger_server().
Referenced by cgv::gui::get_animation_trigger().
The documentation for this class was generated from the following files:
cgv/gui/trigger.h
cgv/gui/trigger.cxx