cgv: vr_view_interactor Class Reference
vr_view_interactor Class Reference
extends the stereo view interactor for vr support
#include <vr_view_interactor.h>
Public Member Functions
vr event processing
cgv::gui::VREventTypeFlags get_event_type_flags () const
query the currently set event type flags
void set_event_type_flags (cgv::gui::VREventTypeFlags flags)
set the event type flags of to be emitted events
bool vr_event_debugging_enabled () const
check whether vr events are printed to the console window
void enable_vr_event_debugging (bool enable=true)
set whether vr events should be printed to the console window
const vr::vr_kit_state * get_current_vr_state () const
return a pointer to the state of the current vr kit
vr::vr_kit * get_current_vr_kit () const
return a pointer to the current vr kit
void query_vr_states ()
vr viewing
cgv::dvec3 get_view_dir_of_kit (int vr_kit_idx=-1) const
query view direction of a vr kit
cgv::dvec3 get_view_up_dir_of_kit (int vr_kit_idx=-1) const
query view up direction of a vr kit
cgv::dvec3 get_eye_of_kit (int eye=0, int vr_kit_idx=-1) const
query the eye position of a vr kit.
vr rendering
bool seperate_view_drawn () const
check whether separate view is rendered
void draw_separate_view (bool do_draw)
set whether to draw separate view
bool vr_kits_drawn () const
check whether vr kits are drawn
void draw_vr_kits (bool do_draw)
set whether to draw vr kits
void draw_vr_controllers (bool do_draw)
set whether to draw controllers
bool action_zone_drawn () const
check whether action zone is drawn
void draw_action_zone (bool do_draw)
whether to draw action zone
bool blit_vr_views_enabled () const
check whether vr views are blitted
void enable_blit_vr_views (bool enable)
enable vr view blitting
int get_blit_vr_view_width () const
return width of vr view blitting
void set_blit_vr_view_width (int width)
set the width with which vr views are blit
vr render process
int get_rendered_eye () const
return the currently rendered eye
vr::gl_vr_display * get_rendered_display () const
return the vr kit currently rendered return a pointer to the current vr kit
vr::vr_kit * get_rendered_vr_kit () const
return pointer to rendered vr kit or nullptr if birds eye view is rendered
int get_rendered_vr_kit_index () const
return index of rendered vr kit or -1 if birds eye view is rendered
void on_set (void *member_ptr)
void stream_stats (std::ostream &)
overload to show the content of this object
bool init (cgv::render::context &ctx)
void clear (cgv::render::context &ctx)
bool handle_vr_events (cgv::gui::event &e)
overload and implement this method to handle events
bool handle (cgv::gui::event &e)
overload and implement this method to handle events
void stream_help (std::ostream &os)
overload to stream help information to the given output stream
void render_vr_kits (cgv::render::context &ctx)
void init_frame (cgv::render::context &)
this method is called in one pass over all drawables before the draw method
void draw_vr_kits (cgv::render::context &ctx)
draw the vr kits in the current view
void draw_action_zone (cgv::render::context &ctx)
draw the action zone of the current vr kit
void draw (cgv::render::context &)
draw all
void finish_frame (cgv::render::context &)
this method is called in one pass over all drawables after drawing
void after_finish (cgv::render::context &ctx)
this method is called in one pass over all drawables after finish frame
bool self_reflect (cgv::reflect::reflection_handler &srh)
you must overload this for gui creation
void create_gui ()
you must overload this for gui creation
Public Member Functions inherited from vr::vr_calibration_base
vr_calibration_base ()
nothing to be done in contructor
Protected Attributes
cgv::ivec4 cgv_viewport
void * fbo_handle
head tracking
cgv::mat3 head_tracker_orientation
head orientation from tracker orientation
cgv::vec3 head_tracker_position
head position from tracker location
calibation of tracker coordinate system
the calibration affects the tracked poses as follows:
mat3 rotation = cgv::math::rotate3<float>(tracking_rotation, vec3(0, 1, 0)); mat3 orientation_world = rotation * orientation_raw; vec3 position_world = rotation * (position_raw - tracking_rotation_origin) + tracking_origin;
or more brief: O = R*Q; p = R*(q-q0) + o;
p = R*(q-q0) + o; o = p - R*(q - q0);
to identify the current focus point f in world coordinates with the raw tracker position q and the rotation origin also with q we compute
q0 = q; o = p;
Now rotation will happen around calibration point.
float tracking_rotation
rotation angle around the y-axis
cgv::vec3 tracking_rotation_origin
location in tracking coordinate system around which rotation is defined
cgv::vec3 tracking_origin
origin of tracking coordinate system given in world coordinates
std::string calibration_file_path
path to calibration file
bool separate_view
whether the window shows a separate view onto the scene or the one of the current vr kit
bool dont_render_kits
whether to not render for kits
bool blit_vr_views
whether to blit in the views of the vr kits
int blit_width
float blit_aspect_scale
scale of aspect ratio used for blitting
int none_separate_view
selection of view of current hmd used in case of no separate view (1 ... left, 2 ... right, 3 ... both)
int head_tracker
int rendered_eye
rendered_eye: 0...monitor,1...left eye,2...right eye
vr::gl_vr_display * rendered_display_ptr
int rendered_display_index
cgv::gui::VREventTypeFlags event_flags
bool debug_vr_events
VRkitVisType vis_type
VRkitVisType hmd_vis_type
VRkitVisType controller_vis_type
VRkitVisType tracker_vis_type
VRkitVisType base_vis_type
bool show_action_zone
cgv::rgb fence_color1
cgv::rgb fence_color2
float fence_frequency
float fence_line_width
void * current_vr_handle
int current_vr_handle_index
std::string kit_enum_definition
std::vector< vr::vr_kit_state > kit_states
std::vector< void * > new_kits
std::vector< void * > kits
std::vector< void * > old_kits
int pose_query
type of pose query according to vr::vr_kit::query_state function's 2nd parameter
cgv::render::box_renderer br
cgv::render::surface_render_style brs
cgv::render::sphere_render_style srs
std::string hmd_mesh_file_name
std::string controller_mesh_file_name
std::string tracker_mesh_file_name
std::string base_mesh_file_name
float mesh_scales [4]
void calibrate_driver ()
perform driver calibration
vr::vr_kit * get_vr_kit_from_index (int i) const
void configure_kits ()
void on_status_change (void *handle, int controller_index, vr::VRStatus old_status, vr::VRStatus new_status)
virtual void on_device_change (void *handle, bool attach)
void add_trackable_spheres (const float *pose, int i, std::vector< cgv::vec4 > &spheres, std::vector< cgv::rgb > &sphere_colors)
helper to visualize pose with colored spheres
void set_tracking_rotation (float tr)
float get_tracking_rotation ()
void set_tracking_origin (cgv::vec3 ori)
cgv::vec3 get_tracking_origin ()
vr_view_interactor (const char *name)
std::string get_type_name () const
return the type name
Additional Inherited Members
Protected Member Functions inherited from vr::vr_calibration_base
void set_driver_calibration_matrix (vr_driver *driver, const float calibration_matrix[12]) const
single point of write access to calibration transformation of vr drivers
Detailed Description
extends the stereo view interactor for vr support
Besides adding the crg_vr_view plugin to your project, you can configure the vr_view_interactor in your cgv::render::drawable::init() function similar to the following example:
#include <vr_view_interactor.h>
bool your_class::init(cgv::render::context& ctx)
{
    cgv::gui::connect_vr_server(true);
    auto view_ptr = find_view_as_node();
    if (view_ptr) {
        // if the view points to a vr_view_interactor
        vr_view_ptr = dynamic_cast<vr_view_interactor*>(view_ptr);
        if (vr_view_ptr) {
            // configure vr event processing
            vr_view_ptr->set_event_type_flags(
                cgv::gui::VREventTypeFlags(
                    cgv::gui::VRE_KEY +
                    cgv::gui::VRE_THROTTLE+
                    cgv::gui::VRE_STICK +
                    cgv::gui::VRE_STICK_KEY +
                    cgv::gui::VRE_POSE
                ));
            vr_view_ptr->enable_vr_event_debugging(false);
            // configure vr rendering
            vr_view_ptr->draw_action_zone(false);
            vr_view_ptr->draw_vr_kits(true);
            vr_view_ptr->enable_blit_vr_views(true);
            vr_view_ptr->set_blit_vr_view_width(200);
        }
    }
    // more application specific init here
    return true;
}
Definition at line 68 of file vr_view_interactor.h.
Constructor & Destructor Documentation
vr_view_interactor()
vr_view_interactor::vr_view_interactor (const char * name)
Definition at line 24 of file vr_view_interactor.cxx.
Member Function Documentation
action_zone_drawn()
bool vr_view_interactor::action_zone_drawn () const inline
check whether action zone is drawn
Definition at line 258 of file vr_view_interactor.h.
add_trackable_spheres()
void vr_view_interactor::add_trackable_spheres (const float * pose, int i, std::vector< cgv::vec4 > & spheres, std::vector< cgv::rgb > & sphere_colors) protected
helper to visualize pose with colored spheres
Definition at line 687 of file vr_view_interactor.cxx.
References cgv::math::fmat< T, N, M >::col().
Referenced by draw_vr_kits().
after_finish()
void vr_view_interactor::after_finish (cgv::render::context & ctx)
this method is called in one pass over all drawables after finish frame
Definition at line 437 of file vr_view_interactor.cxx.
References blit_aspect_scale, vr::gl_vr_display::blit_fbo(), blit_vr_views, vr::gl_vr_display::disable_fbo(), dont_render_kits, vr::gl_vr_display::get_height(), cgv::render::context::get_height(), cgv::render::context::get_render_pass(), vr::gl_vr_display::get_width(), cgv::render::context::get_width(), none_separate_view, cgv::render::context::recover_from_external_frame_buffer_change(), cgv::render::context::recover_from_external_viewport_change(), rendered_eye, cgv::render::RP_MAIN, separate_view, vr::vr_kit::submit_frame(), and vr::VRS_DETACHED.
blit_vr_views_enabled()
bool vr_view_interactor::blit_vr_views_enabled () const inline
check whether vr views are blitted
Definition at line 262 of file vr_view_interactor.h.
calibrate_driver()
void vr_view_interactor::calibrate_driver () protected
perform driver calibration
Definition at line 207 of file vr_view_interactor.cxx.
References get_current_vr_kit(), vr::vr_kit::get_driver(), vr::vr_calibration_base::set_driver_calibration_matrix(), tracking_origin, tracking_rotation, and tracking_rotation_origin.
Referenced by handle().
clear()
void vr_view_interactor::clear (cgv::render::context & ctx)
Definition at line 327 of file vr_view_interactor.cxx.
configure_kits()
void vr_view_interactor::configure_kits () protected
Definition at line 495 of file vr_view_interactor.cxx.
create_gui()
void vr_view_interactor::create_gui ()
you must overload this for gui creation
Definition at line 937 of file vr_view_interactor.cxx.
References blit_aspect_scale, blit_vr_views, calibration_file_path, dont_render_kits, none_separate_view, pose_query, separate_view, tracking_origin, tracking_rotation, and tracking_rotation_origin.
draw()
void vr_view_interactor::draw (cgv::render::context & ctx)
draw all
Definition at line 929 of file vr_view_interactor.cxx.
References draw_action_zone(), and draw_vr_kits().
draw_action_zone() [1/2]
void vr_view_interactor::draw_action_zone (bool do_draw)
whether to draw action zone
Definition at line 102 of file vr_view_interactor.cxx.
Referenced by draw(), and vr_test::init().
draw_action_zone() [2/2]
void vr_view_interactor::draw_action_zone (cgv::render::context & ctx)
draw the action zone of the current vr kit
Definition at line 881 of file vr_view_interactor.cxx.
References cgv::render::attribute_array_binding::disable_global_array(), cgv::render::attribute_array_binding::enable_global_array(), vr::vr_driver::get_action_zone_height(), cgv::gui::trigger::get_current_time(), vr::vr_kit::get_driver(), vr::vr_driver::put_action_zone_bounary(), vr::vr_driver::put_up_direction(), cgv::render::context::ref_default_shader_program(), cgv::render::context::set_color(), and cgv::render::attribute_array_binding::set_global_attribute_array().
draw_separate_view()
void vr_view_interactor::draw_separate_view (bool do_draw)
set whether to draw separate view
Definition at line 75 of file vr_view_interactor.cxx.
References separate_view.
draw_vr_controllers()
void vr_view_interactor::draw_vr_controllers (bool do_draw)
set whether to draw controllers
Definition at line 93 of file vr_view_interactor.cxx.
draw_vr_kits() [1/2]
void vr_view_interactor::draw_vr_kits (bool do_draw)
set whether to draw vr kits
whether to draw vr kits
Definition at line 84 of file vr_view_interactor.cxx.
Referenced by draw(), and vr_test::init().
draw_vr_kits() [2/2]
void vr_view_interactor::draw_vr_kits (cgv::render::context & ctx)
draw the vr kits in the current view
Definition at line 707 of file vr_view_interactor.cxx.
References add_trackable_spheres(), vr::vr_kit_info::controller, vr::vr_kit_state::controller, cgv::render::render_info::draw_all(), vr::vr_kit::get_device_info(), vr::vr_kit::get_driver(), vr::get_vrmesh_file_name(), vr::get_vrmesh_render_info(), vr::vr_kit_state::hmd, vr::max_nr_controllers, cgv::render::context::mul_modelview_matrix(), cgv::render::context::pop_modelview_matrix(), vr::vr_trackable_state::pose, cgv::render::context::push_modelview_matrix(), vr::vr_kit::put_eye_to_head_matrix(), vr::vr_kit::query_state(), cgv::render::ref_sphere_renderer(), cgv::render::renderer::render(), cgv::render::renderer::set_color_array(), cgv::render::renderer::set_render_style(), cgv::render::sphere_renderer::set_sphere_array(), vr::vr_trackable_state::status, vr::vr_controller_state::time_stamp, vr::vr_controller_info::type, and vr::VRS_TRACKED.
enable_blit_vr_views()
void vr_view_interactor::enable_blit_vr_views (bool enable)
enable vr view blitting
Definition at line 110 of file vr_view_interactor.cxx.
References blit_vr_views.
Referenced by vr_test::init().
enable_vr_event_debugging()
void vr_view_interactor::enable_vr_event_debugging (bool enable = true)
set whether vr events should be printed to the console window
Definition at line 66 of file vr_view_interactor.cxx.
Referenced by vr_test::init().
finish_frame()
void vr_view_interactor::finish_frame (cgv::render::context & ctx)
this method is called in one pass over all drawables after drawing
Definition at line 432 of file vr_view_interactor.cxx.
get_blit_vr_view_width()
int vr_view_interactor::get_blit_vr_view_width () const inline
return width of vr view blitting
Definition at line 266 of file vr_view_interactor.h.
get_current_vr_kit()
vr::vr_kit * vr_view_interactor::get_current_vr_kit () const
return a pointer to the current vr kit
Definition at line 135 of file vr_view_interactor.cxx.
Referenced by calibrate_driver(), vr_test::draw(), and vr_test::init_frame().
get_current_vr_state()
const vr::vr_kit_state * vr_view_interactor::get_current_vr_state () const
return a pointer to the state of the current vr kit
Definition at line 127 of file vr_view_interactor.cxx.
Referenced by vr_test::draw().
get_event_type_flags()
cgv::gui::VREventTypeFlags vr_view_interactor::get_event_type_flags () const
query the currently set event type flags
Definition at line 172 of file vr_view_interactor.cxx.
get_eye_of_kit()
cgv::dvec3 vr_view_interactor::get_eye_of_kit (int eye = 0, int vr_kit_idx = -1) const
query the eye position of a vr kit.
parameter eye is one of -1 .. left eye 0 .. cyclopic eye 1 .. right eye if parameter vr_kit_idx defaults to -1, the eye position of the current vr kit is returned if there are not vr kits or the vr_kit_idx parameter is invalid the eye position of the vr_view_interactor is returned
Definition at line 162 of file vr_view_interactor.cxx.
Referenced by vr_test::draw().
get_rendered_display()
vr::gl_vr_display * vr_view_interactor::get_rendered_display () const inline
return the vr kit currently rendered return a pointer to the current vr kit
Definition at line 277 of file vr_view_interactor.h.
get_rendered_eye()
int vr_view_interactor::get_rendered_eye () const inline
return the currently rendered eye
Definition at line 274 of file vr_view_interactor.h.
Referenced by vr_test::draw(), and vr_test::init_frame().
get_rendered_vr_kit()
vr::vr_kit * vr_view_interactor::get_rendered_vr_kit () const inline
return pointer to rendered vr kit or nullptr if birds eye view is rendered
Definition at line 279 of file vr_view_interactor.h.
Referenced by vr_test::draw(), init_frame(), and vr_test::init_frame().
get_rendered_vr_kit_index()
int vr_view_interactor::get_rendered_vr_kit_index () const inline
return index of rendered vr kit or -1 if birds eye view is rendered
Definition at line 281 of file vr_view_interactor.h.
get_tracking_origin()
cgv::vec3 vr_view_interactor::get_tracking_origin () inline
Definition at line 127 of file vr_view_interactor.h.
get_tracking_rotation()
float vr_view_interactor::get_tracking_rotation () inline
Definition at line 120 of file vr_view_interactor.h.
get_type_name()
std::string vr_view_interactor::get_type_name () const
return the type name
Definition at line 222 of file vr_view_interactor.cxx.
get_view_dir_of_kit()
cgv::dvec3 vr_view_interactor::get_view_dir_of_kit (int vr_kit_idx = -1) const
query view direction of a vr kit
if parameter vr_kit_idx defaults to -1, the view direction of the current vr kit is returned if there are not vr kits or the vr_kit_idx parameter is invalid the view direction of the vr_view_interactor is returned
Definition at line 142 of file vr_view_interactor.cxx.
Referenced by vr_test::draw().
get_view_up_dir_of_kit()
cgv::dvec3 vr_view_interactor::get_view_up_dir_of_kit (int vr_kit_idx = -1) const
query view up direction of a vr kit
if parameter vr_kit_idx defaults to -1, the view up direction of the current vr kit is returned if there are not vr kits or the vr_kit_idx parameter is invalid the view up direction of the vr_view_interactor is returned
Definition at line 151 of file vr_view_interactor.cxx.
Referenced by vr_test::draw().
get_vr_kit_from_index()
vr::vr_kit * vr_view_interactor::get_vr_kit_from_index (int i) const protected
Definition at line 490 of file vr_view_interactor.cxx.
handle()
bool vr_view_interactor::handle (cgv::gui::event & e)
overload and implement this method to handle events
Definition at line 352 of file vr_view_interactor.cxx.
References calibrate_driver(), cgv::math::fmat< T, N, M >::col(), vr::vr_kit_state::controller, cgv::gui::EF_VR, cgv::gui::EID_KEY, cgv::gui::EID_POSE, cgv::gui::EM_CTRL, cgv::gui::EM_SHIFT, cgv::gui::key_event::get_action(), cgv::gui::event::get_flags(), cgv::gui::key_event::get_key(), cgv::gui::event::get_kind(), cgv::gui::event::get_modifiers(), cgv::gui::pose_event::get_orientation(), cgv::gui::pose_event::get_position(), cgv::gui::pose_event::get_trackable_index(), handle_vr_events(), head_tracker_orientation, head_tracker_position, cgv::gui::KA_PRESS, cgv::gui::KEY_Space, vr::max_nr_controllers, vr::vr_trackable_state::pose, separate_view, vr::vr_trackable_state::status, cgv::gui::event::stream_out(), tracking_origin, tracking_rotation, tracking_rotation_origin, and vr::VRS_TRACKED.
handle_vr_events()
bool vr_view_interactor::handle_vr_events (cgv::gui::event & e)
overload and implement this method to handle events
factored our vr event handling
Definition at line 333 of file vr_view_interactor.cxx.
References cgv::gui::EID_KEY, cgv::gui::event::get_kind(), cgv::gui::KA_PRESS, cgv::gui::KA_RELEASE, tracking_origin, and vr::VR_INPUT0.
Referenced by handle().
init()
bool vr_view_interactor::init (cgv::render::context & ctx)
Definition at line 307 of file vr_view_interactor.cxx.
init_frame()
void vr_view_interactor::init_frame (cgv::render::context & ctx)
this method is called in one pass over all drawables before the draw method
Definition at line 659 of file vr_view_interactor.cxx.
References dont_render_kits, vr::get_eye_projection_transform(), cgv::render::context::get_render_pass(), get_rendered_vr_kit(), vr::get_world_to_eye_transform(), rendered_eye, cgv::render::RP_MAIN, separate_view, cgv::render::context::set_modelview_matrix(), and cgv::render::context::set_projection_matrix().
on_device_change()
void vr_view_interactor::on_device_change (void * handle, bool attach) protected virtual
Definition at line 194 of file vr_view_interactor.cxx.
on_set()
void vr_view_interactor::on_set (void * member_ptr)
Definition at line 227 of file vr_view_interactor.cxx.
on_status_change()
void vr_view_interactor::on_status_change (void * handle, int controller_index, vr::VRStatus old_status, vr::VRStatus new_status) protected
Definition at line 184 of file vr_view_interactor.cxx.
query_vr_states()
void vr_view_interactor::query_vr_states ()
Definition at line 575 of file vr_view_interactor.cxx.
render_vr_kits()
void vr_view_interactor::render_vr_kits (cgv::render::context & ctx)
Definition at line 601 of file vr_view_interactor.cxx.
self_reflect()
bool vr_view_interactor::self_reflect (cgv::reflect::reflection_handler & srh)
you must overload this for gui creation
Definition at line 1015 of file vr_view_interactor.cxx.
References blit_aspect_scale, blit_vr_views, calibration_file_path, none_separate_view, cgv::reflect::reflection_handler::reflect_member(), separate_view, tracking_origin, tracking_rotation, and tracking_rotation_origin.
seperate_view_drawn()
bool vr_view_interactor::seperate_view_drawn () const inline
check whether separate view is rendered
Definition at line 248 of file vr_view_interactor.h.
set_blit_vr_view_width()
void vr_view_interactor::set_blit_vr_view_width (int width)
set the width with which vr views are blit
Definition at line 118 of file vr_view_interactor.cxx.
Referenced by vr_test::init().
set_event_type_flags()
void vr_view_interactor::set_event_type_flags (cgv::gui::VREventTypeFlags flags)
set the event type flags of to be emitted events
Definition at line 177 of file vr_view_interactor.cxx.
Referenced by vr_test::init().
set_tracking_origin()
void vr_view_interactor::set_tracking_origin (cgv::vec3 ori) inline
Definition at line 123 of file vr_view_interactor.h.
set_tracking_rotation()
void vr_view_interactor::set_tracking_rotation (float tr) inline
Definition at line 116 of file vr_view_interactor.h.
stream_help()
void vr_view_interactor::stream_help (std::ostream & os)
overload to stream help information to the given output stream
Definition at line 294 of file vr_view_interactor.cxx.
stream_stats()
void vr_view_interactor::stream_stats (std::ostream & os)
overload to show the content of this object
Definition at line 302 of file vr_view_interactor.cxx.
vr_event_debugging_enabled()
bool vr_view_interactor::vr_event_debugging_enabled () const inline
check whether vr events are printed to the console window
Definition at line 211 of file vr_view_interactor.h.
vr_kits_drawn()
bool vr_view_interactor::vr_kits_drawn () const inline
check whether vr kits are drawn
Definition at line 252 of file vr_view_interactor.h.
Member Data Documentation
base_mesh_file_name
std::string vr_view_interactor::base_mesh_file_name protected
Definition at line 185 of file vr_view_interactor.h.
base_vis_type
VRkitVisType vr_view_interactor::base_vis_type protected
Definition at line 158 of file vr_view_interactor.h.
blit_aspect_scale
float vr_view_interactor::blit_aspect_scale protected
scale of aspect ratio used for blitting
Definition at line 143 of file vr_view_interactor.h.
Referenced by after_finish(), create_gui(), and self_reflect().
blit_vr_views
bool vr_view_interactor::blit_vr_views protected
whether to blit in the views of the vr kits
Definition at line 139 of file vr_view_interactor.h.
Referenced by after_finish(), create_gui(), enable_blit_vr_views(), and self_reflect().
blit_width
int vr_view_interactor::blit_width protected
Definition at line 141 of file vr_view_interactor.h.
br
cgv::render::box_renderer vr_view_interactor::br protected
Definition at line 180 of file vr_view_interactor.h.
brs
cgv::render::surface_render_style vr_view_interactor::brs protected
Definition at line 181 of file vr_view_interactor.h.
calibration_file_path
std::string vr_view_interactor::calibration_file_path protected
path to calibration file
Definition at line 114 of file vr_view_interactor.h.
Referenced by create_gui(), and self_reflect().
cgv_viewport
cgv::ivec4 vr_view_interactor::cgv_viewport protected
Definition at line 71 of file vr_view_interactor.h.
controller_mesh_file_name
std::string vr_view_interactor::controller_mesh_file_name protected
Definition at line 185 of file vr_view_interactor.h.
controller_vis_type
VRkitVisType vr_view_interactor::controller_vis_type protected
Definition at line 158 of file vr_view_interactor.h.
current_vr_handle
void* vr_view_interactor::current_vr_handle protected
Definition at line 165 of file vr_view_interactor.h.
current_vr_handle_index
int vr_view_interactor::current_vr_handle_index protected
Definition at line 166 of file vr_view_interactor.h.
debug_vr_events
bool vr_view_interactor::debug_vr_events protected
Definition at line 155 of file vr_view_interactor.h.
dont_render_kits
bool vr_view_interactor::dont_render_kits protected
whether to not render for kits
Definition at line 137 of file vr_view_interactor.h.
Referenced by after_finish(), create_gui(), and init_frame().
event_flags
cgv::gui::VREventTypeFlags vr_view_interactor::event_flags protected
Definition at line 152 of file vr_view_interactor.h.
fbo_handle
void* vr_view_interactor::fbo_handle protected
Definition at line 72 of file vr_view_interactor.h.
fence_color1
cgv::rgb vr_view_interactor::fence_color1 protected
Definition at line 160 of file vr_view_interactor.h.
fence_color2
cgv::rgb vr_view_interactor::fence_color2 protected
Definition at line 160 of file vr_view_interactor.h.
fence_frequency
float vr_view_interactor::fence_frequency protected
Definition at line 161 of file vr_view_interactor.h.
fence_line_width
float vr_view_interactor::fence_line_width protected
Definition at line 162 of file vr_view_interactor.h.
head_tracker
int vr_view_interactor::head_tracker protected
Definition at line 146 of file vr_view_interactor.h.
head_tracker_orientation
cgv::mat3 vr_view_interactor::head_tracker_orientation protected
head orientation from tracker orientation
Definition at line 77 of file vr_view_interactor.h.
Referenced by handle().
head_tracker_position
cgv::vec3 vr_view_interactor::head_tracker_position protected
head position from tracker location
Definition at line 79 of file vr_view_interactor.h.
Referenced by handle().
hmd_mesh_file_name
std::string vr_view_interactor::hmd_mesh_file_name protected
Definition at line 185 of file vr_view_interactor.h.
hmd_vis_type
VRkitVisType vr_view_interactor::hmd_vis_type protected
Definition at line 158 of file vr_view_interactor.h.
kit_enum_definition
std::string vr_view_interactor::kit_enum_definition protected
Definition at line 167 of file vr_view_interactor.h.
kit_states
std::vector<vr::vr_kit_state> vr_view_interactor::kit_states protected
Definition at line 169 of file vr_view_interactor.h.
kits
std::vector<void*> vr_view_interactor::kits protected
Definition at line 173 of file vr_view_interactor.h.
mesh_scales
float vr_view_interactor::mesh_scales[4] protected
Definition at line 187 of file vr_view_interactor.h.
new_kits
std::vector<void*> vr_view_interactor::new_kits protected
Definition at line 171 of file vr_view_interactor.h.
none_separate_view
int vr_view_interactor::none_separate_view protected
selection of view of current hmd used in case of no separate view (1 ... left, 2 ... right, 3 ... both)
Definition at line 145 of file vr_view_interactor.h.
Referenced by after_finish(), create_gui(), and self_reflect().
old_kits
std::vector<void*> vr_view_interactor::old_kits protected
Definition at line 175 of file vr_view_interactor.h.
pose_query
int vr_view_interactor::pose_query protected
type of pose query according to vr::vr_kit::query_state function's 2nd parameter
Definition at line 177 of file vr_view_interactor.h.
Referenced by create_gui().
rendered_display_index
int vr_view_interactor::rendered_display_index protected
Definition at line 150 of file vr_view_interactor.h.
rendered_display_ptr
vr::gl_vr_display* vr_view_interactor::rendered_display_ptr protected
Definition at line 149 of file vr_view_interactor.h.
rendered_eye
int vr_view_interactor::rendered_eye protected
rendered_eye: 0...monitor,1...left eye,2...right eye
Definition at line 148 of file vr_view_interactor.h.
Referenced by after_finish(), and init_frame().
separate_view
bool vr_view_interactor::separate_view protected
whether the window shows a separate view onto the scene or the one of the current vr kit
Definition at line 135 of file vr_view_interactor.h.
Referenced by after_finish(), create_gui(), draw_separate_view(), handle(), init_frame(), and self_reflect().
show_action_zone
bool vr_view_interactor::show_action_zone protected
Definition at line 159 of file vr_view_interactor.h.
srs
cgv::render::sphere_render_style vr_view_interactor::srs protected
Definition at line 182 of file vr_view_interactor.h.
tracker_mesh_file_name
std::string vr_view_interactor::tracker_mesh_file_name protected
Definition at line 185 of file vr_view_interactor.h.
tracker_vis_type
VRkitVisType vr_view_interactor::tracker_vis_type protected
Definition at line 158 of file vr_view_interactor.h.
tracking_origin
cgv::vec3 vr_view_interactor::tracking_origin protected
origin of tracking coordinate system given in world coordinates
Definition at line 110 of file vr_view_interactor.h.
Referenced by calibrate_driver(), create_gui(), handle(), handle_vr_events(), and self_reflect().
tracking_rotation
float vr_view_interactor::tracking_rotation protected
rotation angle around the y-axis
Definition at line 106 of file vr_view_interactor.h.
Referenced by calibrate_driver(), create_gui(), handle(), and self_reflect().
tracking_rotation_origin
cgv::vec3 vr_view_interactor::tracking_rotation_origin protected
location in tracking coordinate system around which rotation is defined
Definition at line 108 of file vr_view_interactor.h.
Referenced by calibrate_driver(), create_gui(), handle(), and self_reflect().
vis_type
VRkitVisType vr_view_interactor::vis_type protected
Definition at line 158 of file vr_view_interactor.h.
The documentation for this class was generated from the following files:
plugins/crg_vr_view/vr_view_interactor.h
plugins/crg_vr_view/vr_view_interactor.cxx