var dir_284aa825dfcd36fc77eb764ce6199a8f =
[
    [ "app.cxx", "app_8cxx_source.html", null ],
    [ "application_plugin.cxx", "application__plugin_8cxx_source.html", null ],
    [ "application_plugin.h", "application__plugin_8h_source.html", null ],
    [ "canvas_overlay.cxx", "canvas__overlay_8cxx_source.html", null ],
    [ "canvas_overlay.h", "canvas__overlay_8h_source.html", null ],
    [ "cgv_app.pj", "cgv__app_8pj_source.html", null ],
    [ "color_map_editor.cxx", "color__map__editor_8cxx_source.html", null ],
    [ "color_map_editor.h", "color__map__editor_8h_source.html", null ],
    [ "color_map_legend.cxx", "color__map__legend_8cxx_source.html", null ],
    [ "color_map_legend.h", "color__map__legend_8h_source.html", null ],
    [ "color_map_reader.h", "color__map__reader_8h_source.html", null ],
    [ "color_map_writer.h", "color__map__writer_8h_source.html", null ],
    [ "color_selector.cxx", "color__selector_8cxx_source.html", null ],
    [ "color_selector.h", "color__selector_8h_source.html", null ],
    [ "gizmo.cxx", "gizmo_8cxx_source.html", null ],
    [ "gizmo.h", "gizmo_8h_source.html", null ],
    [ "lib_begin.h", "libs_2cgv__app_2lib__begin_8h_source.html", null ],
    [ "navigator.cxx", "navigator_8cxx_source.html", null ],
    [ "navigator.h", "navigator_8h_source.html", null ],
    [ "overlay.cxx", "overlay_8cxx_source.html", null ],
    [ "overlay.h", "overlay_8h_source.html", null ],
    [ "performance_monitor.cxx", "libs_2cgv__app_2performance__monitor_8cxx_source.html", null ],
    [ "performance_monitor.h", "libs_2cgv__app_2performance__monitor_8h_source.html", null ],
    [ "themed_canvas_overlay.cxx", "themed__canvas__overlay_8cxx_source.html", null ],
    [ "themed_canvas_overlay.h", "themed__canvas__overlay_8h_source.html", null ]
];