# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jstaib/Entwicklung/cgv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jstaib/Entwicklung/cgv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jstaib/Entwicklung/cgv/CMakeFiles /home/jstaib/Entwicklung/cgv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jstaib/Entwicklung/cgv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 3rd

# Build rule for target.
3rd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3rd
.PHONY : 3rd

# fast build rule for target.
3rd/fast:
	$(MAKE) -f 3rd/CMakeFiles/3rd.dir/build.make 3rd/CMakeFiles/3rd.dir/build
.PHONY : 3rd/fast

#=============================================================================
# Target rules for targets named FLTK2

# Build rule for target.
FLTK2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FLTK2
.PHONY : FLTK2

# fast build rule for target.
FLTK2/fast:
	$(MAKE) -f 3rd/fltk/CMakeFiles/FLTK2.dir/build.make 3rd/fltk/CMakeFiles/FLTK2.dir/build
.PHONY : FLTK2/fast

#=============================================================================
# Target rules for targets named tools

# Build rule for target.
tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools
.PHONY : tools

# fast build rule for target.
tools/fast:
	$(MAKE) -f tool/CMakeFiles/tools.dir/build.make tool/CMakeFiles/tools.dir/build
.PHONY : tools/fast

#=============================================================================
# Target rules for targets named ppp

# Build rule for target.
ppp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppp
.PHONY : ppp

# fast build rule for target.
ppp/fast:
	$(MAKE) -f tool/ppp_tool/CMakeFiles/ppp.dir/build.make tool/ppp_tool/CMakeFiles/ppp.dir/build
.PHONY : ppp/fast

#=============================================================================
# Target rules for targets named shader_test

# Build rule for target.
shader_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shader_test
.PHONY : shader_test

# fast build rule for target.
shader_test/fast:
	$(MAKE) -f tool/shader_test/CMakeFiles/shader_test.dir/build.make tool/shader_test/CMakeFiles/shader_test.dir/build
.PHONY : shader_test/fast

#=============================================================================
# Target rules for targets named cgv

# Build rule for target.
cgv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv
.PHONY : cgv

# fast build rule for target.
cgv/fast:
	$(MAKE) -f cgv/CMakeFiles/cgv.dir/build.make cgv/CMakeFiles/cgv.dir/build
.PHONY : cgv/fast

#=============================================================================
# Target rules for targets named cgv_base

# Build rule for target.
cgv_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_base
.PHONY : cgv_base

# fast build rule for target.
cgv_base/fast:
	$(MAKE) -f cgv/base/CMakeFiles/cgv_base.dir/build.make cgv/base/CMakeFiles/cgv_base.dir/build
.PHONY : cgv_base/fast

#=============================================================================
# Target rules for targets named cgv_data

# Build rule for target.
cgv_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_data
.PHONY : cgv_data

# fast build rule for target.
cgv_data/fast:
	$(MAKE) -f cgv/data/CMakeFiles/cgv_data.dir/build.make cgv/data/CMakeFiles/cgv_data.dir/build
.PHONY : cgv_data/fast

#=============================================================================
# Target rules for targets named cgv_gui

# Build rule for target.
cgv_gui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_gui
.PHONY : cgv_gui

# fast build rule for target.
cgv_gui/fast:
	$(MAKE) -f cgv/gui/CMakeFiles/cgv_gui.dir/build.make cgv/gui/CMakeFiles/cgv_gui.dir/build
.PHONY : cgv_gui/fast

#=============================================================================
# Target rules for targets named cgv_math

# Build rule for target.
cgv_math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_math
.PHONY : cgv_math

# fast build rule for target.
cgv_math/fast:
	$(MAKE) -f cgv/math/CMakeFiles/cgv_math.dir/build.make cgv/math/CMakeFiles/cgv_math.dir/build
.PHONY : cgv_math/fast

#=============================================================================
# Target rules for targets named cgv_media

# Build rule for target.
cgv_media: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_media
.PHONY : cgv_media

# fast build rule for target.
cgv_media/fast:
	$(MAKE) -f cgv/media/CMakeFiles/cgv_media.dir/build.make cgv/media/CMakeFiles/cgv_media.dir/build
.PHONY : cgv_media/fast

#=============================================================================
# Target rules for targets named cgv_os

# Build rule for target.
cgv_os: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_os
.PHONY : cgv_os

# fast build rule for target.
cgv_os/fast:
	$(MAKE) -f cgv/os/CMakeFiles/cgv_os.dir/build.make cgv/os/CMakeFiles/cgv_os.dir/build
.PHONY : cgv_os/fast

#=============================================================================
# Target rules for targets named cgv_reflect

# Build rule for target.
cgv_reflect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_reflect
.PHONY : cgv_reflect

# fast build rule for target.
cgv_reflect/fast:
	$(MAKE) -f cgv/reflect/CMakeFiles/cgv_reflect.dir/build.make cgv/reflect/CMakeFiles/cgv_reflect.dir/build
.PHONY : cgv_reflect/fast

#=============================================================================
# Target rules for targets named cgv_render

# Build rule for target.
cgv_render: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_render
.PHONY : cgv_render

# fast build rule for target.
cgv_render/fast:
	$(MAKE) -f cgv/render/CMakeFiles/cgv_render.dir/build.make cgv/render/CMakeFiles/cgv_render.dir/build
.PHONY : cgv_render/fast

#=============================================================================
# Target rules for targets named cgv_signal

# Build rule for target.
cgv_signal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_signal
.PHONY : cgv_signal

# fast build rule for target.
cgv_signal/fast:
	$(MAKE) -f cgv/signal/CMakeFiles/cgv_signal.dir/build.make cgv/signal/CMakeFiles/cgv_signal.dir/build
.PHONY : cgv_signal/fast

#=============================================================================
# Target rules for targets named cgv_type

# Build rule for target.
cgv_type: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_type
.PHONY : cgv_type

# fast build rule for target.
cgv_type/fast:
	$(MAKE) -f cgv/type/CMakeFiles/cgv_type.dir/build.make cgv/type/CMakeFiles/cgv_type.dir/build
.PHONY : cgv_type/fast

#=============================================================================
# Target rules for targets named cgv_utils

# Build rule for target.
cgv_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_utils
.PHONY : cgv_utils

# fast build rule for target.
cgv_utils/fast:
	$(MAKE) -f cgv/utils/CMakeFiles/cgv_utils.dir/build.make cgv/utils/CMakeFiles/cgv_utils.dir/build
.PHONY : cgv_utils/fast

#=============================================================================
# Target rules for targets named libs

# Build rule for target.
libs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libs
.PHONY : libs

# fast build rule for target.
libs/fast:
	$(MAKE) -f libs/CMakeFiles/libs.dir/build.make libs/CMakeFiles/libs.dir/build
.PHONY : libs/fast

#=============================================================================
# Target rules for targets named ppp_lib

# Build rule for target.
ppp_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppp_lib
.PHONY : ppp_lib

# fast build rule for target.
ppp_lib/fast:
	$(MAKE) -f libs/ppp/CMakeFiles/ppp_lib.dir/build.make libs/ppp/CMakeFiles/ppp_lib.dir/build
.PHONY : ppp_lib/fast

#=============================================================================
# Target rules for targets named cgv_gl

# Build rule for target.
cgv_gl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_gl
.PHONY : cgv_gl

# fast build rule for target.
cgv_gl/fast:
	$(MAKE) -f libs/cgv_gl/CMakeFiles/cgv_gl.dir/build.make libs/cgv_gl/CMakeFiles/cgv_gl.dir/build
.PHONY : cgv_gl/fast

#=============================================================================
# Target rules for targets named glsu

# Build rule for target.
glsu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glsu
.PHONY : glsu

# fast build rule for target.
glsu/fast:
	$(MAKE) -f libs/glsu/CMakeFiles/glsu.dir/build.make libs/glsu/CMakeFiles/glsu.dir/build
.PHONY : glsu/fast

#=============================================================================
# Target rules for targets named cgv_reflect_types

# Build rule for target.
cgv_reflect_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_reflect_types
.PHONY : cgv_reflect_types

# fast build rule for target.
cgv_reflect_types/fast:
	$(MAKE) -f libs/cgv_reflect_types/CMakeFiles/cgv_reflect_types.dir/build.make libs/cgv_reflect_types/CMakeFiles/cgv_reflect_types.dir/build
.PHONY : cgv_reflect_types/fast

#=============================================================================
# Target rules for targets named plot

# Build rule for target.
plot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plot
.PHONY : plot

# fast build rule for target.
plot/fast:
	$(MAKE) -f libs/plot/CMakeFiles/plot.dir/build.make libs/plot/CMakeFiles/plot.dir/build
.PHONY : plot/fast

#=============================================================================
# Target rules for targets named plugins

# Build rule for target.
plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugins
.PHONY : plugins

# fast build rule for target.
plugins/fast:
	$(MAKE) -f plugins/CMakeFiles/plugins.dir/build.make plugins/CMakeFiles/plugins.dir/build
.PHONY : plugins/fast

#=============================================================================
# Target rules for targets named cg_fltk

# Build rule for target.
cg_fltk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cg_fltk
.PHONY : cg_fltk

# fast build rule for target.
cg_fltk/fast:
	$(MAKE) -f plugins/cg_fltk/CMakeFiles/cg_fltk.dir/build.make plugins/cg_fltk/CMakeFiles/cg_fltk.dir/build
.PHONY : cg_fltk/fast

#=============================================================================
# Target rules for targets named crg_grid

# Build rule for target.
crg_grid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crg_grid
.PHONY : crg_grid

# fast build rule for target.
crg_grid/fast:
	$(MAKE) -f plugins/crg_grid/CMakeFiles/crg_grid.dir/build.make plugins/crg_grid/CMakeFiles/crg_grid.dir/build
.PHONY : crg_grid/fast

#=============================================================================
# Target rules for targets named crg_stereo_view

# Build rule for target.
crg_stereo_view: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crg_stereo_view
.PHONY : crg_stereo_view

# fast build rule for target.
crg_stereo_view/fast:
	$(MAKE) -f plugins/crg_stereo_view/CMakeFiles/crg_stereo_view.dir/build.make plugins/crg_stereo_view/CMakeFiles/crg_stereo_view.dir/build
.PHONY : crg_stereo_view/fast

#=============================================================================
# Target rules for targets named cmi_io

# Build rule for target.
cmi_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmi_io
.PHONY : cmi_io

# fast build rule for target.
cmi_io/fast:
	$(MAKE) -f plugins/cmi_io/CMakeFiles/cmi_io.dir/build.make plugins/cmi_io/CMakeFiles/cmi_io.dir/build
.PHONY : cmi_io/fast

#=============================================================================
# Target rules for targets named apps

# Build rule for target.
apps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apps
.PHONY : apps

# fast build rule for target.
apps/fast:
	$(MAKE) -f apps/CMakeFiles/apps.dir/build.make apps/CMakeFiles/apps.dir/build
.PHONY : apps/fast

#=============================================================================
# Target rules for targets named cgv_viewer

# Build rule for target.
cgv_viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgv_viewer
.PHONY : cgv_viewer

# fast build rule for target.
cgv_viewer/fast:
	$(MAKE) -f apps/cgv_viewer/CMakeFiles/cgv_viewer.dir/build.make apps/cgv_viewer/CMakeFiles/cgv_viewer.dir/build
.PHONY : cgv_viewer/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... 3rd"
	@echo "... FLTK2"
	@echo "... tools"
	@echo "... ppp"
	@echo "... shader_test"
	@echo "... cgv"
	@echo "... cgv_base"
	@echo "... cgv_data"
	@echo "... cgv_gui"
	@echo "... cgv_math"
	@echo "... cgv_media"
	@echo "... cgv_os"
	@echo "... cgv_reflect"
	@echo "... cgv_render"
	@echo "... cgv_signal"
	@echo "... cgv_type"
	@echo "... cgv_utils"
	@echo "... libs"
	@echo "... ppp_lib"
	@echo "... cgv_gl"
	@echo "... glsu"
	@echo "... cgv_reflect_types"
	@echo "... plot"
	@echo "... plugins"
	@echo "... cg_fltk"
	@echo "... crg_grid"
	@echo "... crg_stereo_view"
	@echo "... cmi_io"
	@echo "... apps"
	@echo "... cgv_viewer"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

