cgv: cgv::type::info::type_name< T > Struct Template Reference
cgv::type::info::type_name< T > Struct Template Reference
traits class with a static function get_name() of type const char* that returns the type name of the template argument T.
#include <type_name.h>
Static Public Member Functions
static const char * get_name ()
return special name for standard types or type name from RTTI cleaned from keywords for all other types
Detailed Description
template<typename T>
struct cgv::type::info::type_name< T >
traits class with a static function get_name() of type const char* that returns the type name of the template argument T.
The standard types have the following textual names:
"bool"
"int[8|16|32|64]"
"uint[8|16|32|64]"
"flt[32|64]"
"wchar"
"string"
"wstring"
all other types are derived from the RTTI with the extract_type_name function applied to the type_info structure returned by typeid.
Definition at line 53 of file type_name.h.
Member Function Documentation
get_name()
template<typename T > static const char * cgv::type::info::type_name< T >::get_name () inline static
return special name for standard types or type name from RTTI cleaned from keywords for all other types
Definition at line 56 of file type_name.h.
References cgv::type::info::type_name< T >::get_name().
Referenced by cgv::base::object_constructor_impl< T >::get_constructed_type_name(), cgv::base::object_constructor_impl_1< T, CA >::get_constructed_type_name(), cgv::base::object_constructor_impl_2< T, CA1, CA2 >::get_constructed_type_name(), cgv::type::info::type_name< T >::get_name(), cgv::base::base::get_type_name(), cgv::base::object_constructor::get_type_name(), cgv::reflect::reflection_traits_impl< T, B, base_is_abst >::get_type_name(), and cgv::reflect::reflection_traits_impl< T, B, true >::get_type_name().
The documentation for this struct was generated from the following file:
cgv/type/info/type_name.h