cgv: cgv::media::mesh::streaming_mesh_callback_handler Struct Reference
cgv::media::mesh::streaming_mesh_callback_handler Struct Reference abstract
pure abstract interface to handle callbacks of a streaming mesh
#include <streaming_mesh.h>
Public Member Functions
virtual void new_vertex (unsigned int vertex_index)=0
called when a new vertex is generated
virtual void new_polygon (const std::vector< unsigned int > &vertex_indices)=0
announces a new polygon defines by the vertex indices stored in the given vector
virtual void before_drop_vertex (unsigned int vertex_index)=0
drop the currently first vertex that has the given global vertex index
Detailed Description
pure abstract interface to handle callbacks of a streaming mesh
Definition at line 12 of file streaming_mesh.h.
Member Function Documentation
before_drop_vertex()
virtual void cgv::media::mesh::streaming_mesh_callback_handler::before_drop_vertex (unsigned int vertex_index) pure virtual
drop the currently first vertex that has the given global vertex index
Implemented in cgv::render::gl::gl_implicit_surface_drawable_base.
Referenced by cgv::media::mesh::streaming_mesh< T >::drop_vertex().
new_polygon()
virtual void cgv::media::mesh::streaming_mesh_callback_handler::new_polygon (const std::vector< unsigned int > & vertex_indices) pure virtual
announces a new polygon defines by the vertex indices stored in the given vector
Implemented in cgv::render::gl::gl_implicit_surface_drawable_base.
Referenced by cgv::media::mesh::streaming_mesh< T >::new_polygon(), cgv::media::mesh::streaming_mesh< T >::new_quad(), and cgv::media::mesh::streaming_mesh< T >::new_triangle().
new_vertex()
virtual void cgv::media::mesh::streaming_mesh_callback_handler::new_vertex (unsigned int vertex_index) pure virtual
called when a new vertex is generated
Implemented in cgv::render::gl::gl_implicit_surface_drawable_base.
Referenced by cgv::media::mesh::streaming_mesh< T >::new_vertex().
The documentation for this struct was generated from the following file:
cgv/media/mesh/streaming_mesh.h