cgv: cgv::base::factory_impl< T > Struct Template Reference
cgv::base::factory_impl< T > Struct Template Reference
implementation of factory for objects of type T using the standard constructor
#include <register.h>
Public Member Functions
base_ptr create_object_impl ()
overload to create an object
std::string get_type_name () const
overload to return the type name of this object. By default the type interface is queried over get_type.
virtual std::string get_object_options () const
return the options string used for object registration
const std::string & get_created_type_name () const
overload to return the type name of the objects that the factory can create
std::string get_property_declarations ()
support creation of object by setting create property to true
bool set_void (const std::string &property, const std::string &value_type, const void *value_ptr)
abstract interface for the setter of a dynamic property.
bool get_void (const std::string &property, const std::string &value_type, void *value_ptr)
abstract interface for the getter of a dynamic property.
bool is_singleton_factory () const
return whether the factory can only generate one instance of the given type
base_ptr get_singleton () const
return pointer to singleton
void release_singleton ()
release the singleton pointer
base_ptr create_object ()
overload to create an object
virtual std::string get_default_options () const
overload to provide default options for registration
std::string get_name_or_type_name () const
determine name of instance by checking cgv::base::named interface and in failure fallback to get_type_name()
virtual void on_register ()
overload to handle register events that is sent after the instance has been registered
virtual void unregister ()
overload to handle unregistration of instances
virtual bool on_exit_request ()
overload to handle the appication exit request, return true if exiting is allowed and false otherwise
virtual void stream_stats (std::ostream &)
overload to show the content of this object
virtual data::ref_ptr< named, true > get_named ()
cast upward to named
virtual data::ref_ptr< node, true > get_node ()
cast upward to node
virtual data::ref_ptr< group, true > get_group ()
cast upward to group
virtual data::ref_ptr< const named, true > get_named_const () const
const cast upward to named
virtual data::ref_ptr< const node, true > get_node_const () const
const cast upward to node
virtual data::ref_ptr< const group, true > get_group_const () const
const cast upward to group
template<class T >
data::ref_ptr< T, true > cast ()
cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
data::ref_ptr< const T, true > cast_const ()
const cast to arbitrary class, but use the casts to named, node and group from the interface
template<class T >
T * get_interface ()
use dynamic type cast to check for the given interface
template<class T >
const T * get_const_interface () const
use dynamic type cast to check for the given interface
virtual void update ()
this virtual update allows for example to ask a view to update the viewed value. The default implementation is empty.
virtual void * get_user_data () const
this virtual method allows to pass application specific data for internal purposes
int get_ref_count () const
read access to current count
property interface
virtual bool self_reflect (cgv::reflect::reflection_handler &)
used for simple self reflection
virtual void on_set (void *member_ptr)
this callback is called when the set_void method has changed a member and can be overloaded in derived class
virtual bool call_void (const std::string &method, const std::vector< std::string > &param_value_types, const std::vector< const void * > &param_value_ptrs, const std::string &result_type="", void *result_value_ptr=0)
abstract interface to call an action
void set (const std::string &property, const char *value)
specialization of set method to support const char* as strings
template<typename T >
void set (const std::string &property, const T &value)
set a property of the element to the given value and perform standard conversions if necessary.
template<typename T >
T get (const std::string &property)
query a property of the element and perform standard conversions if necessary.
void multi_set (const std::string &property_assignments, bool report_error=true)
set several properties
bool is_property (const std::string &property_name, std::string *type_name=0)
check if the given name specifies a property.
void * find_member_ptr (const std::string &property_name, std::string *type_name=0)
find a member pointer by name.
Protected Member Functions
void set_ref_count (int c) const
write access is also const to allow ref counted pointers to const instances
Static Protected Member Functions
template<class T >
static data::ref_ptr< T, true > cast_dynamic (base *b)
use dynamic cast for upcast to given class
Protected Attributes
std::string created_type_name
store the type name of the to be created objects
bool is_singleton
store whether the factory can only create one object
base_ptr singleton
pointer to the single object created by the factory in case is_singleton is true
std::string object_options
store the options used for registering newly created objects
Detailed Description
template<class T>
struct cgv::base::factory_impl< T >
implementation of factory for objects of type T using the standard constructor
Definition at line 264 of file register.h.
Member Function Documentation
call_void()
bool cgv::base::base::call_void (const std::string & method, const std::vector< std::string > & param_value_types, const std::vector< const void * > & param_value_ptrs, const std::string & result_type = "", void * result_value_ptr = 0) virtual inherited
abstract interface to call an action
overload to implement the execution of a method based on the method name and the given parameters
, i.e. a class method based on the action name and the given parameters. The default implementation uses the self_reflect() method to dispatch this call. If not found, the get_void method returns false.
Definition at line 168 of file base.cxx.
find_member_ptr()
void * cgv::base::base::find_member_ptr (const std::string & property_name, std::string * type_name = 0) inherited
find a member pointer by name.
If not found the null pointer is returned. If the type name string pointer is provided, the type of the property is copied to the referenced string.
Definition at line 360 of file base.cxx.
References cgv::reflect::find_reflection_handler::found_target(), cgv::reflect::find_reflection_handler::get_member_ptr(), cgv::reflect::find_reflection_handler::get_reflection_traits(), and cgv::reflect::abst_reflection_traits::get_type_name().
Referenced by cgv::gui::event_handler::add_key_control().
get()
template<typename T > T cgv::base::base::get (const std::string & property) inline inherited
query a property of the element and perform standard conversions if necessary.
This templated version simply extracts the type of the value from the reference and calls the set_void() method. Note that this only works if the template cgv::type::info::type_name<T> is overloaded for the value type.
Definition at line 192 of file base.h.
get_type_name()
template<class T > std::string cgv::base::factory_impl< T >::get_type_name () const inline virtual
overload to return the type name of this object. By default the type interface is queried over get_type.
overload to return the type name of this object
Reimplemented from cgv::base::base.
Definition at line 269 of file register.h.
References cgv::base::factory::get_created_type_name().
get_void()
bool cgv::base::factory::get_void (const std::string & property, const std::string & value_type, void * value_ptr) virtual inherited
abstract interface for the getter of a dynamic property.
abstract interface for the getter, by default it simply returns false
The default implementation uses the self_reflect() method to find a member with the given property as name. If not found, the get_void method returns false.
Reimplemented from cgv::base::base.
Definition at line 855 of file register.cxx.
is_property()
bool cgv::base::base::is_property (const std::string & property_name, std::string * type_name = 0) inherited
check if the given name specifies a property.
If the type name string pointer is provided, the type of the property is copied to the referenced string.
Definition at line 336 of file base.cxx.
References cgv::utils::bite_all(), and cgv::utils::to_string().
multi_set()
void cgv::base::base::multi_set (const std::string & property_assignments, bool report_error = true) inherited
set several properties
set several properties, which are defined as colon separated assignments, where the types are derived automatically
, which are defined as colon separated assignments, where the types are derived automatically to bool, int, double or std::string.
Definition at line 287 of file base.cxx.
References cgv::utils::bite_all(), cgv::utils::is_digit(), cgv::utils::is_integer(), and cgv::utils::to_string().
Referenced by cgv::base::has_property(), and cgv::render::texture::write_to_file().
self_reflect()
bool cgv::base::base::self_reflect (cgv::reflect::reflection_handler &) virtual inherited
used for simple self reflection
is used by default implementation of set_void, get_void and get_property_declarations
The overloaded implementation is used by the default implementations of set_void, get_void and get_property_declarations with corresponding reflection handlers. The default implementation of self_reflect is empty.
Reimplemented in cgv::render::shader_config, and cgv::render::render_config.
Definition at line 161 of file base.cxx.
set()
template<typename T > void cgv::base::base::set (const std::string & property, const T & value) inline inherited
set a property of the element to the given value and perform standard conversions if necessary.
This templated version simply extracts the type of the value from the reference and calls the set_void() method. Note that this only works if the template cgv::type::info::type_name<T> is overloaded for the value type.
Definition at line 186 of file base.h.
set_void()
bool cgv::base::factory::set_void (const std::string & property, const std::string & value_type, const void * value_ptr) virtual inherited
abstract interface for the setter of a dynamic property.
abstract interface for the setter, by default it simply returns false
The default implementation uses the self_reflect() method to find a member with the given property as name. If not found, the set_void method returns false.
Reimplemented from cgv::base::base.
Definition at line 841 of file register.cxx.
References cgv::base::factory::create_object(), and cgv::base::register_object().
The documentation for this struct was generated from the following file:
cgv/base/register.h