cgv: cgv::math::thin_hyper_plate_spline< T > Struct Template Reference
cgv::math::thin_hyper_plate_spline< T > Struct Template Reference
A thin hyperplate spline which represents 3d deformations 3d extension of the thin plate spline.
#include <thin_plate_spline.h>
Public Member Functions
vec< T > map_position (const vec< T > &p)
deform 2d point p
mat< T > map_positions (const mat< T > &points)
deform 3d points stored as columns of the matrix points
Public Attributes
mat< T > controlpoints
mat< T > weights
mat< T > affine_transformation
Detailed Description
template<typename T>
struct cgv::math::thin_hyper_plate_spline< T >
A thin hyperplate spline which represents 3d deformations 3d extension of the thin plate spline.
Definition at line 154 of file thin_plate_spline.h.
Member Function Documentation
map_position()
template<typename T > vec< T > cgv::math::thin_hyper_plate_spline< T >::map_position (const vec< T > & p) inline
deform 2d point p
Definition at line 161 of file thin_plate_spline.h.
References cgv::math::mat< T >::col(), cgv::math::mat< T >::nrows(), and cgv::math::vec< T >::size().
Referenced by cgv::math::thin_hyper_plate_spline< T >::map_positions().
map_positions()
template<typename T > mat< T > cgv::math::thin_hyper_plate_spline< T >::map_positions (const mat< T > & points) inline
deform 3d points stored as columns of the matrix points
Definition at line 193 of file thin_plate_spline.h.
References cgv::math::mat< T >::col(), cgv::math::thin_hyper_plate_spline< T >::map_position(), cgv::math::mat< T >::ncols(), cgv::math::mat< T >::nrows(), and cgv::math::mat< T >::set_col().
Member Data Documentation
affine_transformation
template<typename T > mat<T> cgv::math::thin_hyper_plate_spline< T >::affine_transformation
Definition at line 158 of file thin_plate_spline.h.
controlpoints
template<typename T > mat<T> cgv::math::thin_hyper_plate_spline< T >::controlpoints
Definition at line 156 of file thin_plate_spline.h.
weights
template<typename T > mat<T> cgv::math::thin_hyper_plate_spline< T >::weights
Definition at line 157 of file thin_plate_spline.h.
The documentation for this struct was generated from the following file:
cgv/math/thin_plate_spline.h