cgv: cgv::math::thin_plate_spline< T > Struct Template Reference
cgv::math::thin_plate_spline< T > Struct Template Reference
A thin plate spline which represents 2d deformations See Fred L.
#include <thin_plate_spline.h>
Public Member Functions
vec< T > map_position (const vec< T > &p)
deform a 2d point
vec< T > map_affine_position (const vec< T > &p)
mat< T > map_positions (const mat< T > &points)
deform 2d points stored as columns of the matrix points
Static Public Member Functions
static T U (const T &sqr_dist)
basis function
Public Attributes
mat< T > controlpoints
mat< T > weights
mat< T > affine_transformation
Detailed Description
template<typename T>
struct cgv::math::thin_plate_spline< T >
A thin plate spline which represents 2d deformations See Fred L.
Bookstein: "Principal Warps: Thin-Plate Splines and the Decomposition of Deformation", 1989, IEEE Transactions on Pattern Analysis and Machine Intelligence, Vol. II, No. 6
Definition at line 14 of file thin_plate_spline.h.
Member Function Documentation
map_affine_position()
template<typename T > vec< T > cgv::math::thin_plate_spline< T >::map_affine_position (const vec< T > & p) inline
Definition at line 41 of file thin_plate_spline.h.
map_position()
template<typename T > vec< T > cgv::math::thin_plate_spline< T >::map_position (const vec< T > & p) inline
deform a 2d point
Definition at line 21 of file thin_plate_spline.h.
References cgv::math::mat< T >::col(), cgv::math::mat< T >::nrows(), cgv::math::vec< T >::size(), and cgv::math::thin_plate_spline< T >::U().
Referenced by cgv::math::thin_plate_spline< T >::map_positions().
map_positions()
template<typename T > mat< T > cgv::math::thin_plate_spline< T >::map_positions (const mat< T > & points) inline
deform 2d points stored as columns of the matrix points
Definition at line 64 of file thin_plate_spline.h.
References cgv::math::mat< T >::col(), cgv::math::thin_plate_spline< T >::map_position(), cgv::math::mat< T >::ncols(), cgv::math::mat< T >::nrows(), and cgv::math::mat< T >::set_col().
U()
template<typename T > static T cgv::math::thin_plate_spline< T >::U (const T & sqr_dist) inline static
basis function
Definition at line 76 of file thin_plate_spline.h.
Referenced by cgv::math::thin_plate_spline< T >::map_position().
Member Data Documentation
affine_transformation
template<typename T > mat<T> cgv::math::thin_plate_spline< T >::affine_transformation
Definition at line 18 of file thin_plate_spline.h.
controlpoints
template<typename T > mat<T> cgv::math::thin_plate_spline< T >::controlpoints
Definition at line 16 of file thin_plate_spline.h.
weights
template<typename T > mat<T> cgv::math::thin_plate_spline< T >::weights
Definition at line 17 of file thin_plate_spline.h.
The documentation for this struct was generated from the following file:
cgv/math/thin_plate_spline.h