cgv: cgv::math::fray< T, 3 > Struct Template Reference
cgv::math::fray< T, 3 > Struct Template Reference
Partial specialization of fray class for 3 dimensions.
#include <fray.h>
Public Member Functions
fray ()
Construct an invalid ray with origin at zero and undefined direction.
fray (const fvec< T, 3 > &origin, const fvec< T, 3 > &direction)
Construct a ray with given origin and direction.
fray (const fvec< T, 2 > &screen_coord, const fvec< unsigned, 2 > &viewport_size, const fvec< T, 3 > &eye_position, const fmat< T, 4, 4 > &view_projection_matrix)
Construct a ray from a given screen coordinate and view parameters.
fvec< T, 3 > position (T t) const
Return the position of the ray at the given distance (ray parameter t) from its origin.
Public Attributes
fvec< T, 3 > origin
fvec< T, 3 > direction
Detailed Description
template<typename T>
struct cgv::math::fray< T, 3 >
Partial specialization of fray class for 3 dimensions.
Definition at line 32 of file fray.h.
Constructor & Destructor Documentation
fray() [1/3]
template<typename T > cgv::math::fray< T, 3 >::fray () inline
Construct an invalid ray with origin at zero and undefined direction.
Definition at line 37 of file fray.h.
fray() [2/3]
template<typename T > cgv::math::fray< T, 3 >::fray (const fvec< T, 3 > & origin, const fvec< T, 3 > & direction) inline
Construct a ray with given origin and direction.
Definition at line 43 of file fray.h.
fray() [3/3]
template<typename T > cgv::math::fray< T, 3 >::fray (const fvec< T, 2 > & screen_coord, const fvec< unsigned, 2 > & viewport_size, const fvec< T, 3 > & eye_position, const fmat< T, 4, 4 > & view_projection_matrix) inline
Construct a ray from a given screen coordinate and view parameters.
This is typically used to create a viewing ray that originates at the eye and goes through a pixel on the screen.
Parameters
screen_coord The screen pixel coordinate with (0,0) in the bottom left corner.
viewport_size The screen size in pixels.
eye_position The location of the eye/camera.
view_projection_matrix The current view and projection matrix with no (or identity) model transformation.
Definition at line 52 of file fray.h.
References cgv::math::fvec< T, N >::w(), cgv::math::fvec< T, N >::x(), and cgv::math::fvec< T, N >::y().
Member Function Documentation
position()
template<typename T > fvec< T, 3 > cgv::math::fray< T, 3 >::position (T t) const inline
Return the position of the ray at the given distance (ray parameter t) from its origin.
Definition at line 64 of file fray.h.
Member Data Documentation
direction
template<typename T > fvec<T, 3> cgv::math::fray< T, 3 >::direction
Definition at line 34 of file fray.h.
origin
template<typename T > fvec<T, 3> cgv::math::fray< T, 3 >::origin
Definition at line 33 of file fray.h.
The documentation for this struct was generated from the following file:
cgv/math/fray.h