cgv: cgv::type::variant< T > Struct Template Reference
cgv::type::variant< T > Struct Template Reference
convenience template to access a value pointed to by a void pointer where the type of the value is given by a string as it results from cgv::type::info::type_name<T>::get_name().
#include <variant.h>
Static Public Member Functions
static T get (const std::string &value_type, const void *value_ptr)
convert the value pointed to by value_ptr of type value_type to type T and return it
static void set (const T &value, const std::string &value_type, void *value_ptr)
convert the first parameter of type T into value_type and store the value at the location pointed to by value_ptr
Detailed Description
template<typename T>
struct cgv::type::variant< T >
convenience template to access a value pointed to by a void pointer where the type of the value is given by a string as it results from cgv::type::info::type_name<T>::get_name().
The template argument T is the type into which the stored type is to be converted. With the get method the pointed to value can be read out and with the set method written. If type T is not equal to the stored type, an automatic conversion is performed. A specialization for std::string converts number types to strings with the help of atoi and atof.
Definition at line 20 of file variant.h.
Member Function Documentation
get()
template<typename T > static T cgv::type::variant< T >::get (const std::string & value_type, const void * value_ptr) inline static
convert the value pointed to by value_ptr of type value_type to type T and return it
Definition at line 23 of file variant.h.
References cgv::type::info::get_type_name(), cgv::type::info::TI_BOOL, cgv::type::info::TI_FLT32, cgv::type::info::TI_FLT64, cgv::type::info::TI_INT16, cgv::type::info::TI_INT32, cgv::type::info::TI_INT64, cgv::type::info::TI_INT8, cgv::type::info::TI_STRING, cgv::type::info::TI_UINT16, cgv::type::info::TI_UINT32, cgv::type::info::TI_UINT64, cgv::type::info::TI_UINT8, cgv::type::info::TI_WCHAR, cgv::type::info::TI_WSTRING, and cgv::utils::wstr2str().
Referenced by cgv::gui::layout_table::set_void().
set()
template<typename T > static void cgv::type::variant< T >::set (const T & value, const std::string & value_type, void * value_ptr) inline static
convert the first parameter of type T into value_type and store the value at the location pointed to by value_ptr
Definition at line 56 of file variant.h.
References cgv::type::info::get_type_name(), cgv::utils::str2wstr(), cgv::type::info::TI_BOOL, cgv::type::info::TI_FLT32, cgv::type::info::TI_FLT64, cgv::type::info::TI_INT16, cgv::type::info::TI_INT32, cgv::type::info::TI_INT64, cgv::type::info::TI_INT8, cgv::type::info::TI_STRING, cgv::type::info::TI_UINT16, cgv::type::info::TI_UINT32, cgv::type::info::TI_UINT64, cgv::type::info::TI_UINT8, cgv::type::info::TI_WCHAR, cgv::type::info::TI_WSTRING, and cgv::utils::to_string().
The documentation for this struct was generated from the following file:
cgv/type/variant.h