cgv: cgv::utils::progression Struct Reference
cgv::utils::progression Struct Reference
progression provides a simple possibility to show progression of process in console.
#include <progression.h>
Public Member Functions
progression ()
create empty progression
progression (const std::string &process, size_t total, int count)
create from total enumerations and number of times to print progression
void init (const std::string &process, size_t total, int count)
reinitialize
void step ()
next iteration
Public Attributes
double next_shown
double next_step
double percent
double percent_step
cgv::type::int64_type enumerations
Detailed Description
progression provides a simple possibility to show progression of process in console.
Definition at line 13 of file progression.h.
Constructor & Destructor Documentation
progression() [1/2]
cgv::utils::progression::progression ()
create empty progression
Definition at line 10 of file progression.cxx.
progression() [2/2]
cgv::utils::progression::progression (const std::string & process, size_t total, int count)
create from total enumerations and number of times to print progression
Definition at line 16 of file progression.cxx.
References init().
Member Function Documentation
init()
void cgv::utils::progression::init (const std::string & process, size_t total, int count)
reinitialize
Definition at line 22 of file progression.cxx.
Referenced by cgv::media::mesh::cuberille< X, T, P >::extract(), cgv::media::mesh::dual_contouring< X, T >::extract(), cgv::media::mesh::marching_cubes_base< X, T >::extract_impl(), and progression().
step()
void cgv::utils::progression::step ()
next iteration
Definition at line 36 of file progression.cxx.
Referenced by cgv::media::mesh::cuberille< X, T, P >::extract(), cgv::media::mesh::dual_contouring< X, T >::extract(), and cgv::media::mesh::marching_cubes_base< X, T >::extract_impl().
Member Data Documentation
enumerations
cgv::type::int64_type cgv::utils::progression::enumerations
Definition at line 19 of file progression.h.
next_shown
double cgv::utils::progression::next_shown
Definition at line 15 of file progression.h.
next_step
double cgv::utils::progression::next_step
Definition at line 16 of file progression.h.
percent
double cgv::utils::progression::percent
Definition at line 17 of file progression.h.
percent_step
double cgv::utils::progression::percent_step
Definition at line 18 of file progression.h.
The documentation for this struct was generated from the following files:
cgv/utils/progression.h
cgv/utils/progression.cxx