name: Build and Install the CGV framework

on: push

jobs:
  build:
    name: "${{ matrix.os }} (${{ matrix.compiler }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cxx_compiler: g++
            compiler_flags: -O0 -g0
            install_deps: "sudo apt-get update && sudo apt-get install -y libglx-dev libglew-dev libxft-dev libxinerama-dev libxi-dev"
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            cxx_compiler: clang++
            compiler_flags: -O0 -g0
            install_deps: "sudo apt-get update && sudo apt-get install -y clang libglx-dev libglew-dev libxft-dev libxinerama-dev libxi-dev"
          - os: windows-latest
            compiler: msvc
            c_compiler: cl
            cxx_compiler: cl
            compiler_flags: "/INCREMENTAL:NO"
            install_deps: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Install build tools
        uses: lukka/get-cmake@latest

      - name: Setup ccache
        if: runner.os != 'Windows'
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          verbose: 1

      - name: Setup VS Environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        if: matrix.install_deps != ''
        run: ${{ matrix.install_deps }}

      - name: Configure with CMake
        run: >-
          cmake -B build -G Ninja
          -D CMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -D CMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}
          ${{ runner.os != 'Windows' && '-D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache' || '' }}
          ${{ matrix.compiler_flags != '' && format('-D CMAKE_C_FLAGS="{0}" -D CMAKE_CXX_FLAGS="{0}"', matrix.compiler_flags) || '' }}
          -D CMAKE_INSTALL_PREFIX=../install

      - name: Build
        run: cmake --build build
