name: Build and Install the CGV framework

on: push

jobs:
  build-ubuntu:
    name: "Ubuntu: Build and Install the CGV framework"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Install build tools
        uses: lukka/get-cmake@latest

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          key: ${{ runner.os }}-ccache

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglx-dev libglew-dev libxft-dev libxinerama-dev libxi-dev

      - name: Configure with CMake
        run: cmake -B build -G Ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -D CMAKE_INSTALL_PREFIX=../install -D CMAKE_CXX_FLAGS="-O0 -g0" -D CMAKE_C_FLAGS="-O0 -g0" -D CMAKE_CXX_FLAGS="-O0 -g0" -D CMAKE_C_FLAGS="-O0 -g0"

      - name: Reset cache statistics
        if: always()
        run: ccache --zero-stats 

      - name: Build
        run: cmake --build build

      - name: Show cache statistics
        if: always()
        run: ccache --show-stats --verbose

  build-windows:
    name: "Windows: Build and Install the CGV framework"
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Install build tools
        uses: lukka/get-cmake@latest
      
      - name: Setup VS Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          key: ${{ runner.os }}-ccache

      - name: Configure with CMake
        run: cmake -B build -G Ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -D CMAKE_INSTALL_PREFIX=../install -D CMAKE_CXX_FLAGS="/Od /DEBUG:NONE" -D CMAKE_C_FLAGS="/Od /DEBUG:NONE"

      - name: Reset cache statistics
        if: always()
        run: ccache --zero-stats 

      - name: Build
        run: cmake --build build

      - name: Show cache statistics
        if: always()
        run: ccache --show-stats --verbose
