name: Build and Install the CGV framework

on: push

jobs:
  build-ubuntu:
    name: "Ubuntu: Build and Install the CGV framework"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Build Docker Image
        run: docker build . -t build-image
      - name: Run Build
        run: docker run -v $(pwd):/app build-image

  build-windows:
    name: "Windows: Build and Install the CGV framework"
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup VS Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - run: mkdir build

      - name: Run CMake
        working-directory: build
        run: cmake .. -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=../install -D CMAKE_CXX_COMPILER=cl -D CMAKE_C_COMPILER=cl

      - name: Build and Install
        working-directory: ./build
        run: cmake --build . --target install
